- scripts/load.bety.sh
I accidentally reverted a lot of code added by @robkooper when I made commit 5184fa8fcd58a212e6960231b9f86928e3027b54 (see comment at that commit for more info)
This reverts to 729a8f47e8954ff8038ce7a4ffa924a832e7faa6 with the intended minor addition of the purdue site maintainer name.
See comment at https://github.com/PecanProject/pecan/commit/5184fa8fcd58a212e6960231b9f86928e3027b54
> Reverted changes to load-bety.sh script

- modules/data.atmosphere/R/met2CF.ALMA.R
- modules/data.atmosphere/tests/testthat/test.met2CF.ALMA.R
Met conversion function for the PalEON site-level MIP. Will probably need some additional tweaking for the regional MIP files.
> met2CF.PalEON

- modules/data.atmosphere/R/closest_xy.R
- modules/data.atmosphere/R/download.NARR.R
- modules/data.atmosphere/R/met2CF.NARR.R
- modules/data.atmosphere/R/site.lst.R
- modules/data.atmosphere/inst/scripts/met.workflow.NARR.R
- modules/data.atmosphere/inst/scripts/met.workflow.params.NARR.R
work on NARR specific workflow and params scripts, changes for CF variable naming, work on inserting new inputs and dbfiles into the database
> NARR workflow

- models/ed/R/met2model.ED2.R
Return a data frame with the filename, hostname, start/end year and format info.
Fix issue with CO2
@bcow @jam2767 @mdietze can you check this quickly, make sure it is correct. I tried to use the ameriflux and niwot but ED threw a core dump (even with the data in the sites folder).
> return an data frame with the result #329

- models/sipnet/R/met2model.SIPNET.R
- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/met2CF.NARR.R
- modules/data.atmosphere/R/site.lst.R
- modules/data.atmosphere/inst/scripts/met.workflow.NARR.R
- modules/data.atmosphere/inst/scripts/met.workflow.params.NARR.R
- modules/data.atmosphere/inst/scripts/test.extract.NARR.R
- utils/R/convert.input.R
Not fully functional yet - I have only added functions for NARR and they still need debugging
> Beginning of met.process.R

- db/R/dbfiles.R
- models/sipnet/R/met2model.SIPNET.R
- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/metgapfill.R
- utils/R/convert.input.R
Caveats:
1) Does not use remote.R
2) Only works for full years of data
3) The majority of the sites I've tested have run into trouble in metgapfill (as far as I can tell because they don't meet requirements, not because there is a flaw in the code)
> met.process for Ameriflux to SIPNET on localhost only

- contrib/browndog/PEcAn#AmerifluxSiteRaw_convert.R
- contrib/browndog/PEcAn#AmerifluxSite_convert.R
- contrib/browndog/PEcAn#Ameriflux_convert.R
- contrib/browndog/PEcAn#Sipnet_convert.R
Added initial set of Polyglot scripts.
> Created contrib/browndog folder

- db/R/dbfiles.R
- models/dalec/R/met2model.DALEC.R
- models/ed/R/met2model.ED2.R
- models/linkages/R/met2model.LINKAGES.R
- models/sipnet/R/met2model.SIPNET.R
- modules/data.atmosphere/R/download.Ameriflux.R
- modules/data.atmosphere/R/download.NARR.R
- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/metgapfill.R
- settings/R/read.settings.R
- utils/R/convert.input.R
- utils/R/remote.R
SIPNET, DALEC, LINKAGES and ED2 for NARR and Ameriflux on the localhost, without changes to pecan.xml
> Conversion for NARR and Ameriflux for four met2model fucntions

- web/02-modelsite.php
- web/sites.php
This is a cleanup of checkbox pull request. I will close the original checkbox pull request.
> Allow for filtering on those files that exist on the host.

- modules/rtm/DESCRIPTION
> Changed package name to PEcAnRTM

- modules/data.land/R/fia2ED.R
Added a filter to remove "DEAD" from FIA DB so it does not get to CSS files for ED that brings it back to life.
> added filter to remove DEAD from FIA DB

- modules/data.land/R/fia2ED.R
Changed the significant digits on lat and lon in the name of css and pss output and also added radius to output name.
> Changed the naming of css and pss output files.

- tests/README.md
Note the double -- between vanilla and settings
> Minor edit to tests/README.md to correct typo

- tests/pecan.testbnl.sipnet.xml
> Added BNL server sipnet test

- modules/data.atmosphere/R/download.Ameriflux.R
- modules/data.atmosphere/R/met.process.R
Fix for Ameriflux in met.process
> spelling error in Ameriflux vs. AmeriFlux

- modules/data.atmosphere/R/met.process.R
- web/workflow.R
web workflow line 94: result is a string, not a list object
met process: may have written else statements too spaced out - pulled them together
> web workflow: met.process result fixed

- modules/data.atmosphere/R/met2CF.Ameriflux.R
- modules/data.atmosphere/R/metgapfill.R
in met2CF.Ameriflux and metgapfill
> added dbfile.name to results

- web/02-modelsite.php
Now can show the site markers that contains the searching keywords at "Site". Look at https://github.com/PecanProject/pecan/issues/346
> Add a search function to filt sites from map 

- modules/meta.analysis/R/approx.posterior.R
Commit da4b2176b7dd0e0b44612f4d7d31e8d25bce4c6a inadvertently caused fitted posterior to be misnamed. Fixed here.
Also added try() statements to allow code to proceed even if one or more candidate distributions could not be fit.
> fix approx.posterior.R

- web/03-inputs.php
- web/03a-ameriflux.php
- web/03a-narr.php
- web/04-runpecan.php
- web/07-analysis.php
Put 07-analysis.php file, which allows the end-user to select an ensemble size of 1 or greater (integer).
#517 is the git pecan issue that this branch is associated with.
> Ensemble analysis

- settings/R/read.settings.R
> added 'folder' to check settings workflow insert statement; fixes #531

- scripts/add.models.sh
> Captitalize PEcAn.BIOCRO in add.model.sh

- models/ed/inst/ED2IN.r46
This should be OK, but maybe there was a reason these changes were made?
> Updates to correct old paths

- scripts/build.sh
- web/workflow.R
merge the tests/workflow.R into web/workflow.R for issue #483
> workflow.R clean up

- models/sipnet/R/write.configs.SIPNET.R
I can't get tests to work on pecan2. First the Ameriflux met file for the test isn't located where expected (random glitch or problem with the met code, I don't know). After manually locating the file the model run still aborts, but the logfile isn't where expected so I have no idea why. 
So, resubmitting to get Jenkins to run the test for me.
This definitely fixes the error from last night, but apologies in advance for whatever the next one turns out to be...
> Pda.updates

- web/04-runpecan.php
- web/07-analysis.php
Added sensitivity analysis to 07-analysis.php and modified the pecan.xml file to add the sensitivity settings to the configuration (04-runpecan.php)
#517 is the git pecan issue that this branch is associated with.
> Sensitivity analysis

- models/ed/R/met2model.ED2.R
- modules/data.atmosphere/R/download.NARR.R
- modules/data.atmosphere/R/extract.nc.R
- modules/data.atmosphere/R/met2CF.Ameriflux.R
- modules/data.atmosphere/R/met2CF.NARR.R
- modules/data.atmosphere/R/permute.nc.R
This is the second half of #371, this will run on the Brown Dog machines.
@bcow please check to make sure I didn't remove something by accident. I tried to cleanup the code to make it easier to read and follow the same pattern as all the other pieces of code. All the met functions will return a data.frame that can be used to insert them in the database.
No need to pull this before FluxCamp if you are not sure.
> Met use browndog 2

- web/04-runpecan.php
@ankurdesai  This will make the output files be group writeable. This allows the user to rerun analysis inside the output folder.
> set umask to 0002

- documentation/tutorials/MCMC/MCMC_Concepts.Rmd
- modules/photosynthesis/R/fitA.R
- modules/photosynthesis/R/plots.R
- modules/photosynthesis/vignettes/ResponseCurves.Rmd
This is for the Thurs pre-lunch session at Flux Course and used the photosynthesis module as an example. There are also a few small fixes in that module as well.  I'd really appreciate it if one or more people could test this tutorial (which is in documentation/tutorials/MCMC)
> Created a new tutorial about the basics of working with MCMC.

- modules/meta.analysis/R/approx.posterior.R
Two small reverts from changes in 33ee2a5edb1422a52706fa4a826d3bf970d1f24f
> Approx.posterior reverts

- utils/modellauncher/modellauncher.c
fixes compile errors with modellauncher. Tested using mpich2 1.6 and openmpi 1.4 and 1.8
Compile using `mpicc -o modellauncher modellauncher.c`
In response to #613
> make modellauncher compile

- web/04-runpecan.php
> Fixed bug that stopped ensemble and quantiles analysis.

- db/R/dbfiles.R
- db/R/utils.R
- modules/data.atmosphere/R/met.process.R
- tests/workflow.R
make sure only file is put in settings #585
This also fixes some errors in met.process.
> fix path settings

- web/01-introduction.php
- web/02-modelsite.php
- web/03-inputs.php
- web/03a-ameriflux.php
- web/03a-narr.php
- web/04-runpecan.php
- web/05-running.php
- web/06-edit.php
- web/07-analysis.php
- web/07-continue.php
- web/08-finished.php
- web/checkfailed.php
- web/checksite.php
- web/config.example.php
- web/dataset.php
- web/delete.php
- web/history.php
- web/index.php
- web/loadfile.php
- web/login.php
- web/models.php
- web/savefile.php
- web/sites.php
This makes it so only people with a certain page level access can run
and delete runs. The following section will need to be inserted in
config.php for this to work.
```
run/delete.
$authentication=true;
$min_run_level=2;
$min_delete_level=2;
```
> check to see if user can run/delete #630

- models/preles/DESCRIPTION
- scripts/install.dependencies.R
I think the build failed because the Preles R package location has not been specified yet. For now I took it off the dependencies so it won't look for it.
> Preles package was on my machine so I took it off dependecies for now.

- models/preles/R/runPRELES.jobsh.R
- models/preles/R/write.config.PRELES.R
Argument names were wrong and out of order for .R scripts.
> Preles: fixed order and naming of arguments 

- web/04-runpecan.php
- web/08-finished.php
- web/sites.css
Notes, User and Date Time of run added inside info tag that sits at the top of the pecan.xml file.  Notes field is also added to the workflows table and displayed on the 08-finished.php file.
The pull request will close issue 134.
> Ensemble notes 134

- models/preles/DESCRIPTION
- models/preles/R/write.config.PRELES.R
Preles run wrote out jobs.sh but could not execute it.
> I forgot to write out an apostrophe in jobs.sh

- models/preles/R/write.config.PRELES.R
I overlooked the name of the function I called in jobs.sh. Never again will I do this.
> Called name of function wrong in PRELES package

- models/ed/inst/ED2IN.rgit
I really wish they would stop adding stuff to the ED2IN
> Updated the ED2IN to run with the current version of ED2

- settings/R/read.settings.R
- web/04-runpecan.php
- web/config.example.php
Added new option to hostlist called folder which specifies the folder on the remote host to use. If the user specifies a username that will be appended as well as the workflow. For example this becomes: <folder>/<username>/<workflowid>/run or out.
@bcow let me know if this works.
> Specify remote directory

- models/preles/R/runPRELES.jobsh.R
- models/preles/man/runPRELES.jobsh.Rd
I think this resolves #626 . I had changed the actual preles package to make a param argument required, but didn't realize they had an optional one with defaults. Also, I added changes that were made by roxygen.
> PRELES Package parameter handling changes

- models/preles/R/runPRELES.jobsh.R
Was processing met files incorrectly, necessitating a direct path and name to met file.
> Fix for PRELES package.

- modules/uncertainty/R/get.samples.R
- utils/R/ensemble.R
- utils/R/run.write.configs.R
- web/workflow.R
Closes #730 
I made the changes for passing the sampling method from settings to downstream code. Right now only halton sequence and uniform sampling is implemented.
Shall we migrate get.ensemble.samples function to uncertainty module (where get.parameter.samples are)?
> Fixing halton

- README.md
Changed links to point to gitbook instead of wiki.
> Changes to README links in preperation to close wiki

- models/gday/DESCRIPTION
- models/gday/LICENSE
- models/gday/NAMESPACE
- models/gday/R/write.config.GDAY.R
- models/gday/inst/template.job
- models/gday/man/write.config.GDAY.Rd
- models/gday/tests/testthat.R
- models/gday/tests/testthat/README.txt
Hi,
I just copied @tonygardella MAESPA branch template. I don't suppose this will anyway work without further plumbing but it is a start.
M
> Gday Package

- models/ed/R/write.configs.ed.R
- models/maat/R/write.config.MAAT.R
- models/maat/tests/testthat.R
- models/maat/tests/testthat/test.model2netcdf.MAAT.R
- scripts/build.sh
Add MAAT to build script.  Other small updates.
> Maat model.1

- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.utils.R
- modules/emulator/R/minimize.GP.R
Two updates for the PDA code:
(i) changes in the emulator code (pda.emulator.R in the assim.batch package and mcmc.GP/get.y functions under minimize.GP script in the emulator package) to be able to use GPfit package
(ii) changes in the pda.init.run function under pda.utils.R script to be able to use new version of write.configs.xml.ED function
Colin is on vacation, so, sorry @jam2767 it's your turn again :)
> Updates in the PDA code

- modules/assim.batch/R/pda.bayesian.tools.R
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.mcmc.R
- modules/assim.batch/R/pda.mcmc.bs.R
- utils/R/read.output.R
there were couple of small fixes in my code and related with the issue #775  
@tonygardella is up for review
> small fixes before the VM

- models/gday/R/met2model.GDAY.R
- models/gday/R/model2netcdf.GDAY.R
- models/maespa/R/met2model.MAESPA.R
I've added the script to translate our outputs. This isn't necessarily finished, we currently output all the models state and fluxes (i.e. > 90+ vars), so in theory the PECAN interface could theoretically ingest any of these if it was desired.
I wasn't entirely clear on where some of the vars should go, e.g. leaf biomass. Following the protocol link to http://nacp.ornl.gov/MsTMIP_variables.shtml, it looks to me like the C biomass are perhaps in a single array? I couldn't see a clear example of this in the other model directories.
So for now the key C & water fluxes are there, as well as LAI and the wood & soil C.
> Added model2netcdf.GDAY.R

- modules/assim.batch/R/pda.utils.R
yesterday's last minute changes were not good enough, sorry about that. Now this is the proper fix.
> add full names and else

- models/maespa/R/met2model.MAESPA.R
- I've fixed the indentation logic as things didn't line up, which to me at least made it hard to follow which block matched.
- I've also moved some of the if else final brackets to their own line. I guess this is stylistic but otherwise it is hard to see where the else block closes
- I've also added that MAESPA will infer PAR from SW if PAR isn't in the met data. I think otherwise the model will attempt to simulate it from Tair. Certainly the use of SW would be preferential.
> Fixes to met2model.MAESPA.R. 

- modules/allometry/vignettes/.gitignore
- modules/photosynthesis/R/fitA.R
- modules/photosynthesis/vignettes/.gitignore
XV matrix was missing column names, which I think are needed further
down for setting the variable names in the JAGS code.
Also, captialization mismatch (BETAs vs. BETAS) was preventing the
priors from being defined in the JAGS code.
> Bugfixes in photosynthesis module

- web/03-inputs.php
This code is tied to ticket 353.
The following sites information fields were added to the map pin information window for 03-inputs.php only.
1) mat
2) map
3) greenhouse
4) local time
5) sand pct
6) clay pct
7) soil
8) notes
9) soil notes
> More site info on inputs 353

- scripts/dump.bety.sh
- web/PEcAn.Network.R
This will add the date of the dump to the versions.txt file, this should help to identify how old the dump is. The date is in ISO-8601 format and timezone it UTC.
> add the date to the versions.txt file

- models/ed/R/write.configs.ed.R
- models/ed/inst/template.job
- make sure scratch dir exists
- prepend run with workflow id, this will make sure all runs for a
workflow are in the same folder.
> fix scratch dir

- shiny/workflowPlot/DESCRIPTION
- shiny/workflowPlot/README.md
- shiny/workflowPlot/helper.R
- shiny/workflowPlot/server.R
- shiny/workflowPlot/ui.R
Queries database using dplyr, and sets up pull down menus based on data
from database. No graphs yet.
> shiny workflow plot

- db/R/query.format.vars.R
- db/man/query.format.vars.Rd
- modules/data.atmosphere/R/download.Ameriflux.R
- modules/data.atmosphere/R/download.AmerifluxLBL.R
- modules/data.atmosphere/R/download.FACE.R
- modules/data.atmosphere/R/download.Fluxnet2015.R
- modules/data.atmosphere/R/download.PalEON.R
- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/met2CF.ALMA.R
- modules/data.atmosphere/R/met2CF.FACE.R
- modules/data.atmosphere/R/met2CF.csv.R
- modules/data.atmosphere/R/met2cf.nc.R
- modules/data.atmosphere/R/metgapfill.R
- modules/data.atmosphere/man/download.Ameriflux.Rd
- modules/data.atmosphere/man/download.AmerifluxLBL.Rd
- modules/data.atmosphere/man/download.CRUNCEP.Rd
- modules/data.atmosphere/man/download.FACE.Rd
- modules/data.atmosphere/man/download.Fluxnet2015.Rd
- modules/data.atmosphere/man/download.PalEON.Rd
- modules/data.atmosphere/man/met2CF.FACE.Rd
- modules/data.atmosphere/man/met2CF.csv.Rd
- modules/data.atmosphere/man/metgapfill.Rd
- utils/R/convert.input.R
- utils/man/convert.input.Rd
Modifications (many!) to make automated CSV reading of data from the new Fluxnet2015, Ameriflux or any CSV file that has similarities to it. As far as I know, this doesn't break anything. Testing has been ongoing, but please look carefully at changes made in convert.inputs and met.process in particular.  Closes #882
> met.process, met2cf.csv and AmerifluxLBL/Fluxnet2015

- modules/data.atmosphere/R/download.GFDL.R
- modules/data.atmosphere/R/met.process.R
Cleaned up download.GFDL function and added default arguments for GFDL model/experiment/scenario (let me know if I need to rerun roxygen and such with the edits) and added GFDL hacks to met.process. Able to run jobs successfully in PEcAn with changes to met.process
> GFDL hacks added to Met Process

- modules/assim.batch/R/pda.utils.R
Few PDA updates before the Flux course.
I wanted to use BayesianTools' plotting function, I copied the script to pda.utils, but should I load the package instead?
@mdietze is up for the review
> PDA updates

- db/R/query.format.vars.R
- modules/data.atmosphere/R/download.AmerifluxLBL.R
- modules/data.atmosphere/R/download.Fluxnet2015.R
- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/met2CF.csv.R
- modules/data.atmosphere/R/metgapfill.R
- utils/R/convert.input.R
Was looping but kept using start_year instead of year. Easy fix.
> Fixed year loop bug for metgapfill

- models/ed/R/met2model.ED2.R
- modules/data.atmosphere/R/metgapfill.R
- modules/data.atmosphere/R/site.lst.R
Fixes @tonygardella error with lst
> Timezone lst fixes for met process

- modules/data.atmosphere/R/met.process.R
- web/03a-ameriflux.php
- web/04-runpecan.php
Sorry for the changes to whitespace. this should ask for a username and pass it into download function
> pass username from webform

- models/sipnet/R/write.configs.SIPNET.R
- modules/uncertainty/R/get.samples.R
Issue #927.
@araiho is up for code review
> Sipnet soil parameters

- models/sipnet/R/write.configs.SIPNET.R
- modules/uncertainty/R/get.samples.R
- utils/R/get.analysis.filenames.r
- utils/R/read.output.R
- web/workflow.R
As noted in previous PR, ignore write.configs.SIPNET and get.samples, that was accidentally done in the master branch and is in another PR
Attempts to address issues #916 and #792
> Sensitivity filename & units

- models/sipnet/R/write.configs.SIPNET.R
- modules/uncertainty/R/get.samples.R
- utils/R/run.write.configs.R
@istfer and @rykelly could you look at this to see if there's any obvious places this will break PDA? In particular I'm worried that either (1) PDA won't update the posteriorid variable or (2) the filenaming goes beyond the pattern I'm expecting and causes the system to accidentally run with the priors or (3) the posterior file format from PDA breaks get.parameter.samples.
Just noticed that this branch also includes the fixes that are in PR #946 so ignore write.configs.SIPNET
> Posteriorid fix

- web/workflow.R
> Fixed missing parenthesis in workflow.R

- models/linkages/R/write.restart.LINKAGES.R
- models/linkages/inst/setup_da.R
- models/sipnet/R/read.restart.SIPNET.R
- models/sipnet/R/write.restart.SIPNET.R
- modules/assim.sequential/R/sda.enkf.R
- scripts/workflow.treering.R
@mdietze This should have the fixes from the previous pull request. But, I'm still getting problems inverting matrices. I'm working on units now.
> fixing problems from previous pull request

- modules/assim.batch/R/pda.emulator.R
This `sapply` meant to be a `lapply`
> minor fix to PDA

- tests/pecan.testbnl.ed.xml
- tests/pecan.testbnl.sipnet.xml
Created: pecan.testbnl.ed.xml
Updated: pecan.testbnl.sipnet.xml
within pecan/tests/
> Updated BNL test xmls

- modules/assim.batch/R/pda.emulator.R
- utils/R/utils.R
corrected the conversion with the fixed units and a typo in pda
> conversion from umolC to kgC

- modules/data.atmosphere/R/met2CF.csv.R
To be consistent with change in db/query.format.vars
> met2CF.csv variable name fix

- documentation/tutorials/StateAssimilation/TreeRingSDA.Rmd
- models/sipnet/R/write.restart.SIPNET.R
- modules/assim.sequential/NAMESPACE
- modules/assim.sequential/R/sample.IC.SIPNET.R
- modules/assim.sequential/R/sda.enkf.R
- modules/assim.sequential/R/split.met.SIPNET.R
- scripts/workflow.treering.R
Added a few exports in roxygen and changed some parameters to make 2016 tree rings work with treering workflow.
> Small Changes for SDA with SIPNET and tree rings

- db/R/dbfiles.R
- modules/data.atmosphere/.Rbuildignore
- modules/data.atmosphere/R/download.NARR.R
- modules/data.atmosphere/R/met2CF.NARR.R
- settings/R/papply.R
- settings/R/read.settings.R
Pushing a handful of minor changes so they'll distract less when I get to sharing the more complicated updates to met.process. I think these are all straightforward but questions/comments welcome.
> Multisite workflow

- models/maat/R/met2model.MAAT.R
- models/maat/R/model2netcdf.MAAT.R
- models/maat/R/utils.R
More updates to code.  Enabled runs with met drivers.  Tested at Fort Dix and BCI, both with AF and custom met drivers from BCI tower
Working on a util to convert from ed2 to maat drivers, but may not follow through on that...
> Maat.model

- modules/allometry/R/allom.predict.R
Want the variance to remain fixed within an iteration when the dbh series passed to `allom.predict` is for a single tree (to ensure that biomass is monotonically increasing for each iteration).
Did this by adding a flag called `single.tree`. When `single.tree=TRUE`, then variance fixed within each iteration. Default value is `single.tree=FALSE`, in which case there is no modification to the previously implemented methods.
> Fix allom.predict to work for a single tree

- scripts/Rfcn.R
- scripts/dependencies.R
- scripts/install.dependencies.R
- scripts/pft.add.spp.R
- scripts/quickbuild.R
- scripts/workflow.bm.R
- scripts/workflow.pda.R
- scripts/workflow.treering.R
- settings/R/MultiSettings.R
- settings/R/Settings.R
- settings/R/clean.settings.R
- settings/R/papply.R
- settings/R/read.settings.R
Ran through formatR::tidy_dir with `arrow=TRUE`; standardized indents; made sure all if blocks have braces; cracked down on over-length lines; changed 1:length(x) to seq_along(x).
Non-syntax, both in `read.settings.R`:
* removed `if` check in line 35 (obviated by use of `seq_len`)
* changed from `null` to `NULL` in line 1005
> Style cleanup for `settings/R/*.R` scripts

- models/lpjguess/R/met2model.LPJGUESS.R
- models/lpjguess/R/model2netcdf.LPJGUESS.R
- models/lpjguess/R/write.config.LPJGUESS.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Moved ellipses to end of `met2model.LPJGUESS.R` declaration. Substituted `seq_len` and `seq_along`.
> Style cleanup for `models/lpjguess/R/*.R` scripts

- models/template/R/met2model.MODEL.R
- models/template/R/model2netcdf.MODEL.R
- models/template/R/write.config.MODEL.R
Just to be complete; not much to do here.
> Style cleanup for `models/template/R/*.R` scripts 

- models/jules/R/model2netcdf.JULES.R
- models/jules/R/write.config.JULES.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure
all `if` blocks have braces. Tried to make sure formatR didn’t make
things too jaggy.
@mdietze  note lines 194-206 in `write.config.JULES.R` - I have chained
these ifs together and given them a failure `stop()` - is this OK?
Also fixes #1051.
> Style cleanup for `models/jules/R/*.R` scripts

- models/preles/R/runPRELES.jobsh.R
- models/preles/R/write.config.PRELES.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Substituted `seq_len` and `seq_along`.
> Style cleanup for `models/preles/R/*.R` scripts 

- modules/allometry/R/AllomAve.R
- modules/allometry/R/allom.BayesFit.R
- modules/allometry/R/allom.predict.R
- modules/allometry/R/query.allom.data.R
- modules/allometry/R/read.allom.data.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Substituted `seq_len`, `seq_along`, and `paste0`, and `file.path`.
> Style cleanup for `modules/allometry/R/*.R` scripts 

- models/jules/R/write.config.JULES.R
Changed stop() to logger.severe()  - per @robkooper suggestion
> Style cleanup models jules (again)

- visualization/R/add_icon.R
- visualization/R/ciEnvelope.R
- visualization/R/map.output.R
- visualization/R/plot.netcdf.R
- visualization/R/points2county.R
- visualization/R/shiny.helpers.R
- visualization/R/visually.weighted.watercolor.plots.R
- visualization/R/worldmap.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Substituted `seq_len`, `seq_along`, and `paste0`, and `file.path` as necessary. Made sure all functions end with an explicit `return`.
> Style cleanup for `visualization/R/*.R` scripts 

- models/ed/DESCRIPTION
- models/ed/R/model2netcdf.ED2.R
- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/met2CF.ALMA.R
- scripts/build.sh
- scripts/install.dependencies.R
- utils/DESCRIPTION
- utils/R/read.output.R
Test: have `install.packages` handle a specific package dependency installation (abind)
 A test. Removed `abind` from package list in `scripts/install.dependencies`; made sure it was listed in package DESCRIPTION files; added `abind::` namespace to `abind` calls; modified
`build.sh`.
There shouldn't be any need for `install.dependencies` to do most of what it does.
> Test: have `install.packages` handle a specific package dependency installation (abind)

- db/DESCRIPTION
- db/R/get.trait.data.R
- modules/assim.sequential/DESCRIPTION
- modules/assim.sequential/R/sda.enkf.R
- modules/uncertainty/DESCRIPTION
- modules/uncertainty/R/variance.R
- scripts/install.dependencies.R
- settings/DESCRIPTION
- utils/DESCRIPTION
- utils/R/utils.R
- utils/tests/testthat/test.utils.R
- visualization/DESCRIPTION
- visualization/R/visually.weighted.watercolor.plots.R
Removed responsibility for handling `plyr` dependency  from `install.dependencies`.
Removed car from package list in scripts/install.dependencies; made sure it was listed in package DESCRIPTION files; removed `library` calls; added `car::` namespace to function calls. See #1088.
There shouldn't be any need for install.dependencies to do most of what it does.
> Move responsibility for handling `plyr` dependency

- models/biocro/R/model2netcdf.BIOCRO.R
- models/dalec/R/model2netcdf.DALEC.R
- models/ed/R/model2netcdf.ED2.R
- models/ed/tests/testthat/test.model2netcdf.ED2.R
- models/gday/R/model2netcdf.GDAY.R
- models/linkages/R/model2netcdf.LINKAGES.R
- models/lpjguess/R/model2netcdf.LPJGUESS.R
- models/maat/R/model2netcdf.MAAT.R
- models/maespa/R/model2netcdf.MAESPA.R
- models/sipnet/R/model2netcdf.SIPNET.R
same as previous pull request however only fixes lat/lon this time.
> try2 only fix lat/lon now

- models/lpjguess/R/readStateBinary.LPJGUESS.R
Really hacky function to read LPJ-GUESS's binary state files, reads the state file for the test case
> hacky function to read state files written by LPJ-GUESS

- db/R/dbfiles.R
- modules/data.atmosphere/R/download.raw.met.module.R
- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/met2CF.Ameriflux.R
- modules/data.atmosphere/R/metgapfill.R
- utils/R/convert.input.R
The call to dbfile.input.check in convert.input.R, was returning a ```NULL``` list and should have have been returning an empty data.frame instead. Also, I did some cleanup of scripts that I came across as I was testing things. This closes #1195.
> Convert.input bug fix, and some cleanup 

- utils/R/convert.input.R
The arguments to dbfile.insert at the end of convert.inputs were not assigned to objects creating error in #1220. This should close #1220 and allow files to be inserted under existing input records when another file record exists on another machine.
> Arguments to dbfile.insert were not named at end of convert.inputs

- Makefile
- modules/assim.batch/DESCRIPTION
- modules/assim.batch/R/pda.define.llik.R
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.get.model.output.R
- modules/assim.batch/R/pda.postprocess.R
- modules/assim.batch/R/plot.da.R
- modules/emulator/R/minimize.GP.R
Some more tweaks to the PDA code as @mdietze suggests
-Returning aligned data as well.
-PEcAn.MA namespace fix
-Attempt to write out a pda.log file for the emulator, not clean though
> Some final(!) PDA tweaks

- web/04-runpecan.php
> remove password from params

- db/R/dbfiles.R
- db/man/dbfile.check.Rd
- db/man/dbfile.input.check.Rd
- modules/data.atmosphere/R/met.process.R
- utils/R/convert.input.R
Reverts PecanProject/pecan#1230
> Revert "Met.bug - Making queries for existing inputs more explicit/exhaustive and cleaning up some logic"

- models/ed/data/pftmapping.csv
Initial ED2 mapping of tropical broadleaf evergreen tropical tree for testing
> serbinsh.ed2 - tropical PFT

- models/fates/R/model2netcdf.FATES.R
- models/fates/inst/template.job
> Updates to FATES

- db/R/dbfiles.R
Query for must have it's parenthesis closed
> Met.bug - Missed Parenthesis in query

- utils/R/convert.input.R
> Stray comma in convert.inputs

- modules/assim.batch/R/pda.bayesian.tools.R
- modules/assim.batch/R/pda.define.llik.R
- modules/assim.batch/R/pda.mcmc.R
- modules/assim.batch/R/pda.mcmc.bs.R
I wasn't really able to test things in the latest OS, sorry, but I think PDA algorithms should work fine with these fixes should
#
> minor fixes

- models/ed/DESCRIPTION
> changed PEcAn.ED maintainer to Mike Dietze

- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/download.AmerifluxLBL.R
- modules/data.atmosphere/R/download.NEONmet.R
- modules/data.atmosphere/man/download.AmerifluxLBL.Rd
- modules/data.atmosphere/man/download.NEONmet.Rd
Small bug found in each. One thanks to @mccabete on AmerifluxLBL (typo) and one debugging statement I forgot to remove in NEON.
- [ X] Bug fix (non-breaking change which fixes an issue) 
- [X ] I have read the **CONTRIBUTING** document.
> Minor bug fixes to AmerifluxLBL and NEONmet

- modules/data.atmosphere/R/download.CRUNCEP_Global.R
- modules/data.atmosphere/R/download.GLDAS.R
- modules/data.atmosphere/R/download.NARR.R
- modules/data.atmosphere/R/download.NLDAS.R
Add error message if outside CRUNCEP bounds (yes, ideally, it's better to put it earlier in the workflow, but can't have too many failsafes!).
> CRUNCEP minor revisions

- book_source/installation/Installing-PEcAn-Ubuntu.Rmd
Good to have the developer tools.
> Add `r-base-dev` to install list for Ubuntu

- web/03-inputs.php
> Disable Ameriflux

- CHANGELOG.md
- modules/assim.batch/DESCRIPTION
- modules/assim.batch/R/pda.bayesian.tools.R
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.utils.R
- modules/assim.batch/man/pda.neff.calc.Rd
- scripts/install.dependencies.R
Few cleanup to the PDA code.
Bayesian Tools functionality works again with the latest changes, but I need to work on it later to make it work with >1 chains and parallel.
> PDA cleanup

- modules/data.atmosphere/R/closest_xy.R
Did not close the nc file, this would break the conversion of NARR files on browndog.
> close nc file correctly

- utils/R/convert.input.R
error if settings was not set #18
logger.warning should be logger.warn
> fixes to convert-input.R

- .github/PULL_REQUEST_TEMPLATE.md
update to template so people remember to update CHANGELOG.md.
> add checkbox for CHANGELOG.md.

- models/biocro/R/run.biocro.R
> delete outdated comment

- CHANGELOG.md
- book_source/basic_users_guide/Getting-started.Rmd
- book_source/developers_guide/Using-Git.Rmd
Updating Git workflow. Also cleaning the page up. 
- Deleted "Quick and Easy" instructions because changes should be thoroughly documented and be on unique branches. 
- Established only one workflow to make changes rather than have a "basic" and "advanced" workflow.
I also moved the order of some topics around.
> Cleaning up and updating "Using Git" page

- CHANGELOG.md
- book_source/basic_users_guide/Getting-started.Rmd
- book_source/developers_guide/Using-Git.Rmd
Reverts PecanProject/pecan#1352
> Revert "Cleaning up and updating "Using Git" page"

- book_source/misc/user_appendix.Rmd
Updated documentation
Described the use of download.file() to use a custom FTP program
#994 
Addresses #994 
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
> Doc.update

- CHANGELOG.md
- scripts/load.bety.sh
Instead of using the hardcoded url this will allow to specify the url where to get the specific data from. This can be helpful if a site is down, or if you want to get a dump from somewhere else.
> allow to specify url with -w argument

- modules/data.atmosphere/R/download.Geostreams.R
Because [RFC 4627](https://tools.ietf.org/html/rfc4627) says so.
- [x ] I have read the **CONTRIBUTING** document.
> Use standard mimetype for JSON data

- Makefile
installation does not create a ./devtools, so prereq was never satisfied
Fixes #1410
> fix target paths for dependency packages (fixes #1410)

- db/R/dbfiles.R
- modules/data.atmosphere/R/download.CRUNCEP_Global.R
- modules/data.atmosphere/R/met.process.R
Few small bugfixes to met process for CRUNCEP use
> Met process fixes

- scripts/load.bety.sh
Bug fix
sync was not downloading
> Typo in load.bety.sh, missing $ in front of DUMPURL

- Makefile
> ensure existence of .install before writing to  it

- book_source/adv_user_guide_web/using_browndog.Rmd
- book_source/basic_users_guide/Getting-started.Rmd
- book_source/book_intro/how_to_use_book.Rmd
- book_source/models/variables.Rmd
- documentation/index_vm.html
Pushed last PR #1486 from a branch that was based off of `develop` instead of the `release/1.5.0` branch so I've fixed that here. Added more content to Documentation. Links to Demos, table of PEcAn tools, and a section explaining the purpose of the main sections.
@ashiklom You're partnered with me for review this week.
> Push Documentation Changes to Release branch

- documentation/tutorials/01_Demo_Basic_Run/Demo01.Rmd
- documentation/tutorials/ParameterAssimilation/PDA.Rmd
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.load.data.R
- modules/assim.batch/R/pda.neff.R
- modules/assim.batch/man/pda.emulator.Rd
- modules/assim.batch/man/pda.neff.calc.Rd
PDA tutorial update with latest code changes
> PDA tutorial update

- documentation/tutorials/AnalyzeOutput/modelVSdata.Rmd
- documentation/tutorials/sensitivity/PEcAn_sensitivity_tutorial_v1.0.Rmd
This includes small fixes in file paths, met referenced, and typos. The  versions tested from the VM.
> Tutorial update

- web/01-introduction.php
- web/02-modelsite.php
- web/03-inputs.php
- web/05-running.php
- web/06-edit.php
- web/07-analysis.php
- web/08-finished.php
Fix links to documentation from the web interface.
> Fix links in web interface

- models/sipnet/R/write.configs.SIPNET.R
Added functionality to write.configs.SIPNET to read in initial conditions from a netcdf file.
Instead of an IC input list, there will be a standard netcdf file containing any of the standard initial conditions pool variables. I modified the existing workflow to read in a netcdf from the filepath/id provided by the settings (settings$run$inputs$poolinitcond$path), check for each of the relevant IC variables, and convert them from PEcAn standard if necessary. The IC code was also moved after the other parameter code so that those values can be used in some on-the-fly conversions (not yet implemented).
This will eventually be part of a larger IC workflow for pool-based models. Currently the netcdf file must be created, registered and added to the pecan.xml by hand.
Note: unfortunately I …
> write.configs.SIPNET with IC input

- book_source/installation/thredds.Rmd
- scripts/setversion.sh
- scripts/updateVersion.sh
Small typo in the documentation on where to find the logo.
> Small fix to logo url

- modules/allometry/R/allom.predict.R
Generalizing allom.predict to accept a list where each list element contains a matrix of tree dbh time series for a single pft. The purpose of these changes is to maintain the correct error structure within a plot and for single tree.
> Generalizing allom.predict to accept a list

- web/03a-ameriflux.php
Link to register account with Ameriflux needed to be changed.
> Fix link to register account with ameriflux from web interface

- documentation/tutorials/01_Demo_Basic_Run/Demo01.Rmd
> Fix links in Demo1

- modules/assim.batch/R/gelman_diag.R
to fix issue where gelman diagnostic function crashes when using png(file = NULL) on some machines, like MacOSX (https://stackoverflow.com/questions/24759130/disable-plot-display-in-r)
For example:
```
2017-08-28 11:32:12 INFO   [message] : 
Running 100 more iterations ( 13401 to 13500 ). 
Running DEzs-MCMC, chain  1 iteration 102 of 102 . Current logp  8874.614 8882.72 8885.036 . Please wait! 
runMCMC terminated after 0.171999999999969seconds
Error in dev.off() : 
QuartzBitmap_Output - unable to open file '/dev/null'
2017-08-28 11:32:13 INFO   [PEcAn.logger::logger.info] : 
Unable to calculate Gelman diagnostic. Assuming no convergence. 
2017-08-28 11:32:13 INFO   [message] : 
PEcAn.assim.batch::autoburnin reports convergence has not been achieved. 
Resuming sampling. 
Error: object …
```
> minor update to modules/assim.batch/R/gelman_diag.R 

- CHANGELOG.md
- models/fates/inst/create_1x1_ref_case.sh
> Changes to Fates build script

- base/db/R/dbfiles.R
Type in get.id prevents met download from running.
> Bug fix on get.id call

- Makefile
Save tiny amounts of build time & disk space by not compiling `PEcAn.template`. This code exists to be modified by package developers adding new models to PEcAn, not to be actually called.
Tagging @serbinsh because we're paired for code review this week, @ashiklom because it's the Makefile.
> do not install model template package

- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.postprocess.R
- modules/assim.batch/R/pda.utils.R
- modules/data.land/R/ic_process.R
- modules/data.land/R/put.veg.module.R
> Small fixes

- modules/data.atmosphere/R/tdm_generate_subdaily_models.R
- modules/data.atmosphere/R/tdm_lm_ensemble_sims.R
- modules/data.atmosphere/R/tdm_predict_subdaily_met.R
- modules/data.atmosphere/man/gen.subdaily.models.Rd
- modules/data.atmosphere/man/lm_ensemble_sims.Rd
- modules/data.atmosphere/man/predict_subdaily_met.Rd
Slight tweak to file path to facilitate parallelization; cleanup old parallelization flags; fix consistent direction.filter naming
Previously, the way file paths were passed, trying to run things is
parallel (or at least the way I do it) got a little tricky.  It didn’t
seem much sense to have some redundant file paths, at least with my
file structure, so I think it’ll be okay.  *If this doesn't work with Pecan file structures, just reject the PR and I'll keep this branch for my personal use.*
Also, I did some clean-up along the way: 
1. Remove old flags for parallelization. These were a hold-over from my original paleon-specific workflow.  Further parallelization within the tdm family *could* be accomplished by parallelizing the computation of variables in lm_ensemble_sims, but I'm not …
> Slight tweak to file path to facilitate parallelization + cleanup

- README.md
Added BETYdb to list of publications
To be comprehensive. BETYdb is the core database used by PEcAn
> Added BETYdb to list of publications

- modules/data.atmosphere/R/metutils.R
> Fix for NA in temperature on stopifnot debug in rh2qair

- CHANGELOG.md
> CHANGELOG copy-edits

- book_source/data/meteorology.Rmd
> document Geostreams availability (#1658)

- CHANGELOG.md
- models/preles/DESCRIPTION
- models/preles/NAMESPACE
- models/preles/R/runPRELES.jobsh.R
Release Testing revealed two bugs when running PRELES. I've fixed them here and got rid of library() calls.
> PRELES Fixes

- CHANGELOG.md
- models/maespa/DESCRIPTION
- models/maespa/NAMESPACE
- models/maespa/R/model2netcdf.MAESPA.R
- models/maespa/R/write.config.MAESPA.R
- models/preles/R/runPRELES.jobsh.R
Made Rpreles and Maeswrap suggested packages in PEcAn model packages so that if they are not available package building will not fail
> Check for Rpreles and Maeswrap packages

- base/remote/R/check_qsub_status.R
- base/remote/R/start.model.runs.R
- base/remote/tests/testthat/test.check_qsub.R
- Revert to using `system` instead of `system2` for `qstat` command to allow it to use pipes.
- Fix progress bar typo
- Add a simple unit test for `qstat` code
This fixes some bugs in remote execution that @serbinsh discovered.
> Bugfixes in remote code

- base/remote/R/check_qsub_status.R
> Update to check_qsub function so that it waits properly

- CHANGELOG.md
- models/biocro/DESCRIPTION
- models/biocro/R/run.biocro.R
- models/biocro/tests/testthat/test-run.biocro.R
Fixes #1738.
Note that this adds a package import (`dplyr`), but `PEcAn.data.atmosphere` already imports `dplyr` and `PECan.BIOCRO` already imports `PEcAn.data.atmosphere`, so it doesn't add any new dependencies.
Also note that I've added a test to cover this, but it's skipped on Travis so that we can avoid adding BioCro to the everyday test environment.  It should still run when you do $(make test) on your local VM, though.
> Fix Biocro result summaries (#1738)

- Makefile
- models/biocro/DESCRIPTION
- models/biocro/tests/testthat/test-run.biocro.R
* Remove unneccessary `skip_on_travis()`
* install mockery package as needed
* minor code cleanup
I don't know how I missed it before, but my claims in #1739 about needing to install BioCro before stubbing out functions were 100% wrong: `mockery::stub` is perfectly happy to stub functions from namespaces that don't exist at all!
> Update #1739: Run mocked tests on Travis after all

- models/ed/R/write.configs.ed.R
- models/sipnet/R/write.configs.SIPNET.R
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.utils.R
- modules/emulator/R/minimize.GP.R
- modules/emulator/man/get_ss.Rd
Small fixes to the code that I used in production runs.
The handling of scaling factors was causing errors in the second round
> Fix for porposing and post-processing of scaling factor in emulator

- modules/data.atmosphere/R/met2CF.csv.R
Switches time zone from given Olsonname to "Etc/GMT+X" or "Etc/GMT-X". Tested and it works.
Closes #1748
> Force timezone to not switch between daylight and standard time

- models/ed/R/model2netcdf.ED2.R
> Fixing Typo in MsTMIP var name in model2netcdf.ED2

- CHANGELOG.md
- modules/rtm/R/bayestools.R
- modules/rtm/tests/testthat/test.invert_bayestools.R
- Remove effective sample size normalization trying to account for spectral autocorrelation. It was giving weird results that go away when it's removed.
- Enhance the BayesianTools inversion unit test.
> RTM: Minor revisions

- CHANGELOG.md
- models/ed/data/pftmapping.csv
- [ X] I have updated the CHANGELOG.md.
- [X ] I have updated the documentation accordingly.
- [ X] I have read the **CONTRIBUTING** document.
> Updated ed2 pfts

- base/utils/R/read_web_config.R
- Make sure to remove only leading $
- Make sure to remove everything after ;
Following line was a problem parsing:
$server_url="192.168.0.5";    // local test server
> tweaks to reading php config file

- book_source/developers_guide/debugging.Rmd
- book_source/installation/VM-Creation.Rmd
- scripts/install_pecan.sh
Added some documentation about how to debug shiny apps.
> add comments to book about debugging shiny apps

- CHANGELOG.md
- web/dataset.php
Fixed remote code execution discovered by NCSA security team
> escape arguments for dataset

- CHANGELOG.md
- book_source/_bookdown.yml
- book_source/adv_user_guide_web/curl-web-submit.Rmd
Documentation update to show how to submit a run from the command line using curl.
- [] My change requires a change to the documentation.
> document how to use curl to do a run

- web/common.php
> arpa-e funding

- base/visualization/R/create_status_page.R
Creating the status page could result in 2 errors. This only shows up if you run this multiple times.
> Fix some errors when creating status page

- tests/pecan64.biocro.xml
> update biocro integration test

- book_source/developers_guide/Directory-structure.Rmd
I went looking for a place to document the existence of the Workflow package and only found this, which hasn't been updated in a while. Here's my unsolicited stab at an update -- @tonygardella  please tear it apart as needed, or reject entirely it if this file is no longer the place to be documenting packages.
> update directory structure docs

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Adding a part to the PR template checklist asking about when a PR review is needed so priority of the PR can be understood by reviewers.
Added Three options:
Ankur is my code reviewer this week but unavailable so tagging @mdietze @dlebauer and @robkooper
> Add PR review time estimate to PR template

- .travis.yml
Saves ~1100 lines of log output by piping stdout to `/dev/null` during the initial database load. Have tested and confirmed that it doesn't eat warnings or errors.
> Travis: minimize console noise from loading Bety

- book_source/deploy.sh
- documentation/tutorials/deploy.sh
In #1843 I tried to use `git ls-remote` to check whether `github.com/$USER/pecan-documentation.git` exists before attempting to push to it, but this is [failing on Travis](https://travis-ci.org/PecanProject/pecan/builds/338648022#L6797); best I can tell, `git ls-remote` needs authentication and only appeared to work on my local machine because it was using my existing ssh keys.
This revision uses unauthed `curl` to check for the repository, and I've confirmed that Travis:
* Passes skipping book deployment when building non-{`master`, `release`, `develop`} branches in my fork
* Passes skipping book deployment when building `develop` in my fork and `infotroph/pecan-documentation` does not exist
* Fails at deployment step when building `develop` in my fork when …
> Deploy book if repo exists

- book_source/03_intermediate_users_guide/01_pecan_xml.Rmd
Small fix to link in documentation
> fix link to model-type in pecan.xml

- CHANGELOG.md
- scripts/load.bety.sh
This should fix issue with bu, use the -k
`load-bety.sh -k -r 1` will allow sync with BU again.
> fix to allow fetching with insecure servers.

- book_source/05_developer_guide/01_setup/01_install_PEcAn/04_install_models/install_LPJGUESS.Rmd
Link to download LPJ-GUESS has changed. Changing instructions in Documentation
> Change instructions to download lpj-guess

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Add comments statements about adding labels to issues and PR.
> Add message about labels in Issue and PR template

- web/hostmodelinfo.php
The loops failed due to an issue with php, see http://php.net/manual/en/control-structures.foreach.php (big red box).
> need to unset site

- book_source/05_developer_guide/01_setup/01_install_PEcAn/04_install_models/install_LPJGUESS.Rmd
this is the url LPJ-GUESS group prefers to be shared.
> change LPJ-GUESS download url

- modules/data.atmosphere/R/download.GFDL.R
- modules/data.atmosphere/R/metgapfill.R
- modules/data.atmosphere/man/download.GFDL.Rd
Closes #1902 to prevent overwrite. Also merges in metgapfill fix to develop. Let me know if you want me to rebase this to release branch (and remind me instructions again). Thanks.
> GFDL download fix

- models/biocro/inst/extdata/pecan.biocro.xml
- models/biocro/tests/testthat/data/pecan.biocro.xml
- tests/ebi-forecast.igb.illinois.edu.biocro.xml
- tests/pecan64.biocro.xml
* `settings$database$bety$dbfiles` was never a valid path; it gets ignored and PEcAn uses the default "~/.pecan/dbfiles" instead
* `settings$run$dbfiles` is accepted with a warning from `fix.deprecated.settings`, but fixing these while I'm looking at BioCro settings files.
> move dbfiles setting to correct location (#1918)

- modules/data.atmosphere/DESCRIPTION
> DESCRIPTION changes missed in #1904

- book_source/06_reference/04_docker/architecture.Rmd
- book_source/06_reference/04_docker/introduction.Rmd
- book_source/06_reference/04_docker/models.Rmd
Text above the header line gets shown in the previous chapter
> Documentation: Render disclaimer in Docker section, not met

- .zenodo.json
> fix .zenodo.json

- CHANGELOG.md
> add date to changelog

- modules/data.atmosphere/R/debias_met_regression.R
Quick bug fix in the precipitation redistribution step of the met bias correction routine -- changed two spots where days were sampled without replacement to WITH replacement.
When doing the bias-correction for PalEON sites, some midwestern sites ended up with a case where the precipitation couldn't be redistributed to the randomly generated number of rainless days unless we sampled with replacement.  This may cause the actual met to not hit the exact target number of rainless days (drawn from the distribution observed in the training dataset), but it should get us close.  Without this fix, the debiasing routine won't work for certain sites/times in the Midwest.
> Fix bug in met debiasing

- shiny/workflowPlot/server_files/sidebar_server.R
Once modal is executed we will be shown a results page from where we can navigate to shiny app. In shiny app, user needs to give workflow id in order to visualize results. We can make workflow_id and run_id preselected from URL parameters
* Link: http://pecan-gsoc-2.ncsa.illinois.edu/shiny/workflowPlot/?workflow_id=99000000002&run_id=99000000001
* Opens shiny app with preselected workflow_id as `99000000002` and run_id as `workflow 99000000002, run 99000000001`
* Link: http://pecan-gsoc-2.ncsa.illinois.edu/shiny/workflowPlot/?workflow_id=99000000002
* Opens shiny app with preselected workflow_id as `99000000002` 
* Link: http://pecan-gsoc-2.ncsa.illinois.edu/shiny/workflowPlot
* Opens shiny app with no preselected values
> Open shiny application with workflow_id and run_id from URL parametes

- modules/meta.analysis/DESCRIPTION
- modules/meta.analysis/R/meta.analysis.summary.R
- modules/meta.analysis/R/run.meta.analysis.R
- modules/meta.analysis/R/zzz.R
- modules/meta.analysis/man/pecan.ma.summary.Rd
- modules/meta.analysis/man/run.meta.analysis.Rd
- modules/meta.analysis/tests/testthat/test.run.meta.analysis.R
* Added a `.onLoad` function to load the `coda` namespace every time `PEcAn.MA` is loaded. This seems to be our best best to make sure coda's S3 methods are accessible when we call generics that use them. This fixes #1368.
* Added PEcAn.settings to Imports (was already used with ::, just needed to be declared)
* Partial cleanup of documentation to remove a few of the check warnings
> Fix PEcAn.MA tests

- Makefile
This is a fixup for #1966 -- I added PEcAn.settings to the Imports list for PEcAn.MA, but forgot to tell Make about the dependency.
(Someday we need a better system for this, but not today)
> install settings before MA

- modules/data.atmosphere/R/tdm_lm_ensemble_sims.R
- modules/data.atmosphere/R/tdm_predict_subdaily_met.R
Somewhere along the line, the way I propagated ensemble members changed
and now my attempt at speedup where I did half the number of ensembles
caused things to break with ensembles >3.  Simple fix, but it slows
things down when you’re generating a number of hourly ensemble members
Made a change that slows down the temporal downscaling (but not terribly), but is critical to generating hourly ensembles greater than 3.
(Also discovered a weird copy-paste error from who knows how long ago that I think has minimal impact on met downscaling.)
When doing temporal downscaling for Willow Creek (for the downscaling manuscript), discovered a bug when you tried to generate more than 3 hourly ensemble members.  I think this arises from a change in the routine structure in 2017, but regardless of the …
> TDM Bug Fixes

- .travis.yml
- Makefile
- base/logger/DESCRIPTION
- base/qaqc/DESCRIPTION
- base/qaqc/tests/testthat.R
- base/remote/DESCRIPTION
- modules/assim.sequential/DESCRIPTION
As proposed in #1949: Runs devtools::check on all packages during the Travis build, and marks the build as broken if any check returns an ERROR. WARNINGs and NOTEs do not break the build (for now), but I encourage all PEcAn authors to routinely run `devtools::check` locally and fix all WARNINGs and as many NOTEs as possible.
N.B. Currently skips checking of PEcAn.benchmark and PEcAn.data.land, until failures in their examples are resolved.
Note that this PR simply adds `make check` into the existing test script, and does *not* implement the "build stages" approach I demoed a few meetings ago -- that's in [this branch](https://github.com/infotroph/pecan/tree/travis-build-stages-grouped) and needs more work before merging.
> Run (most) package checks on Travis

- modules/data.atmosphere/DESCRIPTION
Forgot to remove from DESCRIPTION when fixing #1984
> Fixed RAtmosphere dependency

- CHANGELOG.md
- shiny/Data-Ingest/app.R
- shiny/Data-Ingest/modules/d1_download_module.R
- shiny/Data-Ingest/modules/formats_module.R
- shiny/Data-Ingest/modules/inputs_module.R
- shiny/Data-Ingest/modules/local_upload_module.R
- shiny/Data-Ingest/server_files/d1_download_svr.R
- shiny/Data-Ingest/server_files/ingest_workflow_svr.R
- shiny/Data-Ingest/server_files/local_upload_svr.R
- shiny/Data-Ingest/ui_files/d1_download_ui.R
- shiny/Data-Ingest/ui_files/ingest_workflow_ui.R
- shiny/Data-Ingest/ui_files/local_file_upload_ui.R
- shiny/Data-Ingest/ui_files/sidebar_ui.R
This PR completely redesigns the layout of the application. Instead of selecting a tab to then proceed to either a DataONE download or local upload workflow, there is only one Ingest-workflow tab. On this tab, the users can select their preferred input method and then the app will render this UI for them. Users can now select a column row, and have this name passed into the inputs step of the UI. Registering new formats records is now relegated to a drop down menu within the inputs box. 
These changes are by no means the end all be all for the UI of this app. Indeed there are a few important features that are not currently present. The objective of this PR is to get a minimum workflow ready so I can link the app to BETY. I intend to have this UI debugged and linked to BETY by the end of …
> New Data_Ingest app UI  features 

- CHANGELOG.md
- shiny/Data-Ingest/app.R
- shiny/Data-Ingest/server_files/d1_download_svr.R
- shiny/Data-Ingest/server_files/ingest_workflow_svr.R
- shiny/Data-Ingest/server_files/local_upload_svr.R
- shiny/Data-Ingest/ui_files/d1_download_ui.R
- shiny/Data-Ingest/ui_files/ingest_workflow_ui.R
- shiny/Data-Ingest/ui_files/local_file_upload_ui.R
- shiny/Data-Ingest/ui_files/sidebar_ui.R
Added new features to app while waiting for BETY docker issues earlier in the week. Users can now create new input records, db file records, and format records by entering all the inputs in the inputs tab and then selecting `Bety Test`. This should allow us to quickly progress to a final version of this app. It is still necessary for users to manually check that the input was inserted in the various tables. 
New Features: 
- Hide `Download` button until `doi` is entered. 
- New Radio Buttons ot toggle between download methods 
- Pass Filename from selected file from input method to `Name` field
- Pass new format name and mimetype from the formats box to the inputs box
- `Bety Test` Button to test `dbfiles.input.insert`
> Data-Ingest New Features and attempt at linking to BETY (Work in Progress) 

- modules/data.atmosphere/R/tdm_lm_ensemble_sims.R
Adjust number of intermediate ensemble members being calculated inside the TDM code.
In updating my branch, I discovered one of my slight fixes to the TDM code didn't make it into the mainline.  At one point I'd tried reducing the number of intermediate ensemble members inside the TDM code, but with larger ensembles, this wouldn't work.  This will slow down the TDM routine, but makes it more stable.
> Minor TDM bug fix

- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/metgapfill.R
- scripts/install.dependencies.R
REddyProc is now on CRAN and the old Rforge repo is deprecated, so removed the Remotes entry and deleted old references to Rforge version.
Note that if you have the GitHub version of REddyProc installed on your machine, devtools will keep using it and will always reinstall the newest version. If this annoys you like it does me, `install.packages("REddyProc")` to switch to the CRAN version.
> Use CRAN version of REddyProc

- CHANGELOG.md
- modules/data.atmosphere/R/download.NARR_site.R
- modules/data.atmosphere/man/download.NARR_site.Rd
- modules/data.atmosphere/man/get_NARR_thredds.Rd
to set parallel=TRUE in the function call to match the documentation and other sub-functions. Roxygenized the package and updated the docs
- [X ] My change requires a change to the documentation.
- [ X] I have updated the CHANGELOG.md.
- [ X] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
> Updated modules/data.atmosphere/R/download.NARR_site.R

- CHANGELOG.md
- base/utils/R/sensitivity.R
This is a fix for issue #2064. This makes sure that one met path is sent to write.sa.config.
- [ X] When possible
- [X ] Bug fix (non-breaking change which fixes an issue)
> Fix the met for SA

- book_source/Makefile
When running make in parallel, it needs to know  that it's not allowed to deploy the book until after it's done building. Closes #2069.
> Book build: declare build as prerequisite of deploy (#2069)

- modules/data.atmosphere/R/met2CF.AmerifluxLBL.R
- modules/data.atmosphere/man/met2CF.AmerifluxLBL.Rd
Per @serbinsh request, provide param info on format in met2CF.AmerifluxLBL
> Update documentation in met2CF.AmerifluxLBL

- models/biocro/DESCRIPTION
PEcAn.DB isn't ever used in the PEcAn.BIOCRO package code, but is referenced once in a vignette and once in a sample workflow in inst/. My understanding is that DESCRIPTION is supposed to include things needed by vignettes, so keeping it in Suggests.
> Trivial: BioCro move DB from imports to suggests

- Makefile
- modules/benchmark/DESCRIPTION
* List more imports that were missing from DESCRIPTION
* Declare other PEcAn dependencies in Makefile, so make can figure out that it needs to install DB before Benchmark.
This patch makes the dependency list more Correct, but in practice it only makes a difference when installing with a large number of parallel processes, or if trying to `make .install/modules/benchmark` on a system with no other PEcAn packages already installed. In most other cases these dependencies are installed by other packages before Benchmark misses them.
Tagging @bcow for review, as the benchmark expert.
> declare more benchmark dependencies

- base/utils/R/sensitivity.R
This PR would hopefully fixes all the issues with sending met paths to mode.write.config functions. This issue came up multiple times but it's mentioned in #2080. The only thing I did here is move up my previous code before the first write.config. I tested the code for `JULES` and I was able to write the configs and run the model.
- [ X] When possible
> Fixing the SA path problem.

- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/met2CF.Geostreams.R
* convert two prints to logger functions
* linebreaks for readability
> Logger formatting

- base/utils/DESCRIPTION
- base/utils/R/convert.input.R
Takes the result list of dataframes that contains the file names of downloaded/converted files from convert.input and checks for whether or not the files or empty or a file was downloaded or not. If there is a file of size 0 or it's empty, logger.severe is used to exit out of pecan.
There was a problem that files could be downloaded/converted that were actually empty, or within the list of files that were supposed to be downloaded/converted some were successfully done and others were not, but the since some worked things would continue on.
@bcow You're my code reviewer this week.
@serbinsh This should help with making runs fail at the correct step when met is empty
@ashiklom @infotroph  Want some advice on creating a better log statement. I have a data.frame of result files and when it …
> Add check for file size and exit if empty or NA in convert.input

- base/db/R/query.format.vars.R
- shiny/Data-Ingest/app.R
- shiny/ViewMet/server.R
A few packages were missing from SHINY apps.
Also, Ankur's fix in #2077 needs to be in this release.
ViewMet and dataingest shiny apps were loading by but then they would fail once using it. This gets rid of errors due to missing libraries.
Ankur's fix also needs to be in this release.
@dlebauer You're my code reviewer this week. Let me know if you don't have time to review.
> Packages for SHINY that were missed and Ankur's fix that needs to be in release.

- release.sh
automatically set up tags for docker
removed for loop that is not used.
> fix release script

- book_source/06_reference/04_docker/02_quickstart.Rmd
- book_source/06_reference/04_docker/03_architecture.Rmd
- docker-compose.yml
- docker/add-data.sh
- Add more status messages to `docker/add_data.sh` to make it easier to track progress
- Add a sentence of documentation describing how `pecan/data` uses `docker/add_data.sh`
- Add a bit more information about Minio, and fix the Minio comment in `docker-compose.yml`-
> Minor Docker-related documentation updates

- modules/data.atmosphere/R/download.CRUNCEP_Global.R
`outfolder` needs to exist for the mask to be downloaded into it.
This is a bug.
> MET/BUGFIX: Create CRUNCEP `outfolder` before downloading maskfile

- .travis.yml
- Makefile
- base/all/DESCRIPTION
This is a compacted version of #2163, PRed from a local branch so that Travis can build it with access to our authentication tokens. 
We still need to figure out a way of accepting PRs from outside forks, but hopefully this works for the meantime.
> Update build for new devtools behavior

- CHANGELOG.md
- book_source/06_reference/04_docker/03_architecture.Rmd
- docker-compose.yml
- docker/base/Dockerfile.thredds
- docker/thredds_catalog.xml
Added the THREDDS data server to the PEcAn Docker stack. It is accessible at `<hostname:port>/thredds/catalog.html` (by default, `localhost:8000`) through the web browser. Specific NetCDF files are accessible through OpenDAP as:
```r
ncdf4::nc_open("http://localhost:8000/thredds/dodsC/outputs/PEcAn_<workflow_id>/out/<run_id>/<year>.nc")
```
This makes it significantly easier to access PEcAn model results on remote servers.
> DOCKER: Add prototype of THREDDS data server

- docker/base/Dockerfile.base
- docker/base/Dockerfile.depends
- docker/models/Dockerfile.ed2
- docker/models/Dockerfile.sipnet
- scripts/install_deps.R
- install all dependencies
- fix sipnet/ed to start with right binaries
- copy makefile.depends
> docker fixes

- modules/data.atmosphere/DESCRIPTION
Specifies any version of geonames *greater than* the current CRAN version (0.998 at this writing, which is broken because the URL for the geonames web service has changed since it was released). 
Right now the only way to satisfy this requirement is by installing the geonames dev version (0.998.9000) from GitHub. Once a new CRAN version is released, We can drop the GitHub remote but keep the same version spec.
> require next Geonames

- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/download.CRUNCEP_Global.R
- modules/data.atmosphere/R/download.US_WCr.R
- modules/data.atmosphere/R/nc_merge.R
- modules/data.atmosphere/R/tdm_generate_subdaily_models.R
- modules/data.atmosphere/R/tdm_temporal_downscale_functions.R
Figured I'd sweep some dust bunnies out of the corners as long as I was looking at check results.
-  [x] cleanup
> data.atm: finish converting authors to authors@R, add a few namespaces

- docker/receiver.py
- poll for messages
- work done in separate thread
- worker thread can NOT talk on channel.
> fix heartbeat rabbitmq

- book_source/05_developer_guide/01_setup/01_install_PEcAn/04_install_models/install_JULES.Rmd
Link was broken to registration/download page. Fixes "PecanProject/PecanProject.github.io#5" as pointed out by @sw-rifai. Thank you for finding it.
> Fix link to Jules registration page

- web/08-finished.php
- web/historylist.php
make sure that hostname is passed from history and back option in interface.
> make sure to pass hostname

- CHANGELOG.md
- docker/add-data.sh
- docker/base/Dockerfile.data
small tweaks to data image:
- has all data already downloaded in image
- only registers ED and SIPNET since these are the only models supported right now.
> Pecan data download

- .travis.yml
This should fix travis build error
> fix travis missing libmagick++-dev

- tests/README.md
README incorrectly stated that workflow.R was in tests folder but it had moved to the web folder
> updated location of workflow.R file

- modules/data.atmosphere/tests/testthat/test.download.CRUNCEP.R
- modules/data.atmosphere/tests/testthat/test.download.GFDLR.R
The existing skip did eventually fire, but not until after waiting 75s for the connection to time out.
@ashiklom you added these lines in #2273 but I'm not sure I follow your intent -- does this change retain the behavior you wanted?
> wrap GFDL URL check in test, skip on travis

- docker.sh
copy and paste error when building on the develop branch
> fix docker.sh for develop branch

- docker.sh
- release.sh
Update release.sh to make sure all images are tagged correctly and pushed to dockerhub.
> same logic in release as docker.sh for IMAGE_VERSION

- CHANGELOG.md
- base/db/R/utils_db.R
- base/db/man/db.close.Rd
- base/db/man/db.exists.Rd
- base/db/man/db.open.Rd
- base/db/man/db.print.connections.Rd
- base/db/man/db.query.Rd
- base/db/man/db_merge_into.Rd
- base/db/man/insert_table.Rd
- base/db/man/match_colnames.Rd
- base/db/man/match_dbcols.Rd
A lot of this is code style and documentation cleanup and additional logging that shouldn't affect function. The most significant _functional_ change is that `db.open` should now also support the `RPostgres` package, which is a newer (and, I would argue, better) version of the old `RPostgreSQL` package.
`RPostgres` is better maintained, integrates more nicely with R, and, most importantly (IMHO) supports parameterized queries, which are both easier to write _and_ safer. Note that `pecanapi` already uses `RPostgres` under the hood.
> PEcAn.DB cleanup

- base/settings/R/site_pft_link_settings.R
> Quick bugfix in base/settings/R/site_pft_link_settings.R

- CHANGELOG.md
- docker.sh
- models/biocro/Dockerfile
- models/biocro/model_info.json
cleanup of #2320
This will dockerize biocro for PEcAn and make it discoverable.
> Dockerize biocro

- Makefile
- base/db/DESCRIPTION
- modules/benchmark/DESCRIPTION
- scripts/travis/script.sh
This installs version 1.3.0 of dbplyr. This should fix the build problems. There is an issue #2349 that tracks the progress of making PEcAn work with the latest version of dbplyr again.
> install specific version of dbplyr

- .travis.yml
- scripts/time.sh
- scripts/travis/script.sh
Quick fix for Travis failures -- the version of `sf` installed from cran2deb4ubuntu expects a different version of GDAL than is installed, but appears to do OK if built locally.
This will make uncached builds longer, but should get us going again until the prebuilt version updates.
> build sf locally to avoid gdal version conflict

- base/remote/R/remote.copy.from.R
- base/remote/R/remote.copy.to.R
- base/remote/man/remote.copy.from.Rd
- base/remote/man/remote.copy.to.Rd
Small enhancement to remote.copy.from to allow users specify their own flags and arguments for rsync.
Added a new argument as suggested by @robkooper 
I also grep for the current instances in the repository, this change doesn't seem to require any related changes
Closes #2355
> remote.copy.from enhancement

- models/ed/R/model2netcdf.ED2.R
> ED: Fix gsub pattern in model2netcdf.ED2

- docker-compose.yml
- docker/rstudio-nginx/nginx.conf
typo in default password
did not use proxy port
> fix rstudio docker

- base/workflow/R/create_execute_test_xml.R
- base/workflow/man/create_execute_test_xml.Rd
Old behavior led to possibly inconsistent database connections between what was used by `batch_run` configuration and what was used by the workflow itself (i.e. configured in the settings file). These changes should ensure that the database connection parameters are mutually consistent.
> Finer control over BETY con in integration tests

- CHANGELOG.md
Yay, it's time for the traditional* post-release changelog merge error party!
*(This is an indictment of Git usability, not a judgement on any member of the PEcAn team)
> Changelog: Move changes since 1.7.1 back into "unreleased" section

- book_source/04_appendix/04-package-dependencies.Rmd
Fixed two code chunks that Rmarkdown was evaluating instead of displaying
> [Docs] Fix chunk rendering in dependencies appendix

- modules/data.atmosphere/tests/Rcheck_reference.log
- scripts/check_with_errors.R
* Bugfix to PR #2442: needed to ignore "consider adding..." line as well as "undeclared global..." line
* Also: Made file executable. Not needed for this fix, I just got tired of typing "Rscript" all the time while testing it.
* Also also: Removes some messages fixed in #2403 from the stored `data.atmosphere` check file
> [Build] do not error when existing  importFrom suggestion fixed

- scripts/updateVersion.sh
Avoids undoing #2455 when running the script which increments package versions for release
> keep license names in release

- Makefile.depends
- modules/meta.analysis/DESCRIPTION
Cleaning up from #2470: I created a circular dependency by adding PEcAn.MA to the Imports of PEcAn.priors (it uses it exactly once, previously undeclared) without noticing that PEcAn.MA already listed PEcAn.priors in its Suggests (but was not in fact using it anywhere, so the resolution is easy).
(Detail for the nerds: Why wasn't this caught during build? Because dependency cycles in R are legal as long as one is in Suggests, and Make complains but builds anyway by dropping an arbitrary link out of the cycle)
> drop unused priors from MA suggests

- scripts/travis/install.sh
- scripts/travis/script.sh
And also move version-pinning from script.sh to install.sh
...And while we're at it, stop installing an old dbplyr, thus finishing #2392's work and closing #2349.
MCMCpack 1.4-5 now requires R 3.6 (after years of supporting everything back to R 2.1!) I can't find a changelog, but a requirement jump of this size likely means the new version is taking advantage of substantial efficiency gains from R's recent changes for compiled code.
We've been routintely testing and running PEcAn with MCMCpack 1.4-4 right up until this week, so I don't expect any issues with continuing to use it on older versions of R that can't use 1.4-5.
> install MCMCpack 1.4-4 on R < 3.6

- api/R/insert_new_workflow.R
- api/R/prepared_query.R
- base/db/inst/import-try/93.create.try.sites.R
- base/settings/R/check.all.settings.R
- base/utils/R/utils.R
- base/utils/man/retry.func.Rd
- base/visualization/R/visually.weighted.watercolor.plots.R
- models/biocro/R/call_biocro.R
- modules/allometry/R/allom.predict.R
- modules/assim.batch/R/autoburnin.R
- modules/assim.batch/R/gelman_diag.R
- modules/assim.sequential/inst/MultiSite-Exs/SDA/Multisite-4sites.R
- modules/assim.sequential/inst/RemoteLauncher/SDA_launcher.R
- modules/benchmark/R/metric_timeseries_plot.R
- modules/data.land/R/dataone_download.R
- modules/data.land/R/pool_ic_netcdf2list.R
- modules/priors/R/priors.R
- modules/rtm/R/bayestools.R
- modules/rtm/R/check.convergence.R
- modules/rtm/R/invert.custom.R
- modules/uncertainty/R/variance.R
- modules/uncertainty/tests/testthat/test.plot.sensitivity.R
- shiny/ViewMet/server.R
- [ x] When possible
- [x ] Bug fix (non-breaking change which fixes an issue)
> fixes issue #2479 by avoiding checking inheritance with ==

- base/utils/R/get.results.R
- base/utils/R/to_nc.R
- base/utils/R/utils.R
- base/utils/man/mstmipvar.Rd
- models/basgra/R/run_BASGRA.R
- [ x] When possible
- [ x] Bug fix (non-breaking change which fixes an issue)
> GH-#1154-changed var to nc_var

- CHANGELOG.md
- docker/depends/pecan.depends
- models/ed/R/other.helpers.ED2.R
- models/ed/man/list.files.nodir.Rd
- models/jules/DESCRIPTION
- models/jules/R/model2netcdf.JULES.R
- shiny/ViewMet/server.R
Combines #2511 and #2513 to make sure they combine to get a passing Travis build
> Travis build fix

- Makefile
- scripts/travis/install.sh
Fixes current Travis failure -- looks like `cran.us.r-project.org` doesn't exist anymore.
> [Travis] replace apparently-defunct CRAN mirror

- .travis.yml
- scripts/travis/func.sh
- scripts/travis/script.sh
Should allow faster feedback by failing build immediately as soon as the changes show up, instead of waiting until the very end of the build.
> [build] Check for uncommitted file changes after each step

- docker/monitor/index.html
> Fixing typo 

- CHANGELOG.md
- book_source/04_appendix/07_singularity.Rmd
Document how to run ED in singularity. This is based on discussion in #containers channel in slack.
> add documentation about ED and singularity

- book_source/04_appendix/07_singularity.Rmd
Add some text to show "click to expand"
> add click here

- .travis.yml
- scripts/travis/install.sh
Splits the Travis apt package list out into two sections: System libraries that we install for all builds, and prebuilt R packages from c2d4u that we only install for builds on R:release. 
Minor downside: Makes .travis.yml somewhat trickier to read, because I used [YAML aliases](https://yaml.org/spec/1.2/spec.html#alias//) to avoid repeating package names. Read `*name` as a macro that expands to some other object defined at the anchor `&name`, and read `foo: &name` as both defining foo *and* setting its contents to be copied into all `*name` aliases. In this case Travis never uses the `_apt` and `_c2d4u` objects by those names; they only exist to be referenced by alias because it seemed more readable to define them outside the build matrix.
My understanding is that c2d4u only targets the …
> [travis] Only use c2d4u on current R release

- modules/assim.batch/tests/testthat/test.bt_prior.R
Closes #2546 by implementing the "easiest fix" discussed there. If anyone wants to tackle a more "correct" refactoring later, I'd love to review it, but this should at least cut down on the spurious build failures in the meantime.
> set RNG seed for BayesianTools tests. Fixes #2546

- .github/ISSUE_TEMPLATE/Doc_changes.md
partial fix for [#2561](https://github.com/PecanProject/pecan/issues/2561)
[edited by @infotroph to avoid closing issue on merge]
> Fix broken link in doc_changes issue template

- base/db/R/dbfiles.R
- base/db/R/insert.format.vars.R
- base/db/R/query_pfts.R
- base/db/man/dbfile.input.insert.Rd
- base/db/man/insert.format.vars.Rd
- base/db/man/query_pfts.Rd
- base/db/tests/Rcheck_reference.log
> fix a couple R check complaints in DB documentation

- docker/monitor/monitor.py
Fixes broken monitor. This is needed for models to be registered.
Thanks to @istfer and @infotroph for pointing out the bug and this fix.
> fix monitor (fixes #2571)

- scripts/generate_dependencies.R
This fixes the sorting.
Can be tested with
```
LC_ALL=et_EE ./scripts/generate_dependencies.R && git diff docker
```
> set sorting to en_US.UTF-8 (fixes #2515)

- models/stics/tests/testthat.R
(`devtools::test` ignores this file, so I only noticed when I ran R CMD check without the `--no-tests` it usually gets during CI runs)
> tiny typo in STICS test file

- docker/check/check_postgresql
- docker/monitor/monitor.py
minor fixes to get PEcAn ready to run in kubernetes.
Also small fix to monitor, in python using a (x,) will create a tuple, while (1) will just create an int.
> Kubernetes fixes

- .github/workflows/depends.yml
will automatically build pecan/depends:develop image.
> autobuild pecan/depends:develop image

- CHANGELOG.md
Meant to add this to #2592 but apparently forgot.
> changelog for CI changes

- docker/depends/Dockerfile
`==` is a bashism. Not sure why it doesn't make the image build fail, though...
> typo in depends Dockerfile

- .github/workflows/ci.yml
As the issue #2578 is fixed. I think we can now remove this.
> removing-git-install

- CHANGELOG.md
- modules/data.remote/R/call_MODIS.R
- modules/data.remote/man/call_MODIS.Rd
I have changed the order of arguments in `call_MODIS()`, explained the behaviour of `outdir `argument and updated the changelog.
Fixes #2519
> Change order of arguments in call_MODIS()

- shiny/dbsync/Dockerfile
Need to run apt-get to refresh caches
> do apt-get before install

- base/utils/R/sensitivity.R
Fixed typos that cause DB query errors.
> Fixing small typos that casuses errors for SA runs

- CHANGELOG.md
- docker/depends/pecan.depends
- modules/assim.batch/DESCRIPTION
- modules/assim.batch/R/hier.mcmc.R
- modules/assim.batch/R/pda.utils.R
- modules/emulator/DESCRIPTION
- modules/emulator/R/minimize.GP.R
Replaced [tmvtnorm](https://CRAN.R-project.org/package=tmvtnorm) package functions in PDA with  [TruncatedNormal](https://CRAN.R-project.org/package=TruncatedNormal).  
Fixes #2621
> Replace tmvtnorm

- modules/data.atmosphere/R/met.process.R
- modules/data.atmosphere/R/met.process.stage.R
- modules/data.atmosphere/man/browndog.met.Rd
- modules/data.atmosphere/man/db.site.lat.lon.Rd
- modules/data.atmosphere/man/met.process.stage.Rd
- modules/data.atmosphere/tests/Rcheck_reference.log
One change missed in #2632, plus some Roxygen cleanup while I was in the file. Thanks to @kzarada for reporting.
> Pass correct object to query.format.vars

- .github/workflows/ci.yml
- .github/workflows/styler-actions.yml
- Makefile.depends
- docker/depends/pecan.depends
Motivated by seeing #2664 [pass on Actions](https://github.com/PecanProject/pecan/pull/2664/checks?check_run_id=937721036) but [fail on Travis](https://travis-ci.org/github/PecanProject/pecan/jobs/714223471), and therefore realizing this check wasn't being done on Actions.
> Implement dependency updates in Actions CI

- modules/data.atmosphere/tests/testthat/test.download.CRUNCEP.R
- modules/data.atmosphere/tests/testthat/test.download.GFDLR.R
- modules/data.atmosphere/tests/testthat/test.download.NARR.R
change suggested by @infotroph
> update skipped tests to skip on Github Actions too

- modules/data.land/R/soil_process.R
Updating format name for gSSURGO soil input
> Updating format name for dbfile insert for gSSURGO files

- README.md
> update link to documentation in README

- .github/workflows/ci.yml
- .github/workflows/depends.yml
- .github/workflows/docker.yml
- CHANGELOG.md
- docker.sh
Use github actions to build docker images
> GitHub actions docker

- docker/monitor/monitor.py
This fixes the missing , in the monitor.py
No need for a changelog since this fixes the bug introduced in this version
> fix missing , in execute

- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/tdm_lm_ensemble_sims.R
- modules/data.atmosphere/R/tdm_model_train.R
- modules/data.atmosphere/R/tdm_predict_subdaily_met.R
- modules/data.atmosphere/R/tdm_subdaily_pred.R
- modules/data.atmosphere/man/predict_subdaily_met.Rd
Major changes: 
1) Critical: Fix precipitation redistribution bug (tdm_lm_ensemble_sims.R line 572 most critical); 
2) Improve support for single-prediction downscaling by using the model coefficients and circumventing creating/pulling from a simulated posterior distribution of coefficients (necessary for generating an ensemble that characterizies and propagates uncertiainty)
For the precipitation redistribution issue: there was an issue where precipitation after temporal downscaling was consistent and sometimes dramatically less than at the outset.  Turns out this was due to a really stupid mistake that wasn't caught long ago.
For the single-prediction feature: the original motivator of the TDM code was to generate an met ensemble that could be used to calculate driver uncertainty and …
> Met Temporal Downscaling Fixes & Updates

- DEV-INTRO.md
* typo, file is .env (for consistency w/ later instructions) ./env --> .env
* added 'requirements' section
* other minor changes
> Minor updates to DEV-INTRO.md

- CHANGELOG.md
- base/remote/R/rabbitmq.R
- base/remote/R/start_rabbitmq.R
- base/remote/man/rabbitmq_create_queue.Rd
- base/remote/man/rabbitmq_get_message.Rd
- base/remote/man/rabbitmq_parse_uri.Rd
- base/remote/man/rabbitmq_post_message.Rd
- base/remote/man/rabbitmq_send_message.Rd
- base/remote/man/start_rabbitmq.Rd
- book_source/03_topical_pages/94_docker/05_building_images.Rmd
- book_source/03_topical_pages/94_docker/09_rabbitmq.Rmd
- docker-compose.yml
- docker/executor/Dockerfile
- docker/models/model.py
This will use the R functions to submit to R. This will allow the execution of workflows from Rstudio.
With this it should now be possible to run your workflow in rstudio and have the jobs be submitted to the queue for each model. There is no need for the sender.py script anymore.
> use rabbitmq in R

- modules/data.atmosphere/R/debias_met_regression.R
- modules/data.atmosphere/R/extract_local_NLDAS.R
Long overdue updates and fixes to the `debias.met.regression()` function.  Two relatively small, but important updates:
1. Provide better support for single-case downscaling where we don't care about propagating uncertainty (mirroring #2705)
2. Fix an apparent long-standing bug in uncertainty in temporal trends for temperature variables.  Through a logic error, we were _removing_ the temporal trend all together rather than adding in uncertainty in that trend.  The solution is to remove the mean trend and then add in the trend estimated in the anomaly/temporal trend sub-model.  Easy fix, but important one.
This isn't linked to any standing issues since it was previously masked int he ensemble approach.  The problem with the temporal trend was more evident when doing single-member work and …
> Updates to regression-based debias routines

- .github/workflows/styler-actions.yml
So cases like the current state of #2626 can be resolved by `/document`
> commit any changes to depend files when documenting from PR comment

- .github/workflows/styler-actions.yml
> commit namespace changes too

- modules/meta.analysis/R/single.MA.R
Previously working meta analysis **with random effects turned on** was breaking for me. I suspect it might be related to R version bump (due to stringsAsFactors = FALSE by default)
This minor fix solved it for me. But others might want to reproduce with
```
<meta.analysis>
<iter>10000</iter>
<random.effects>
<on>TRUE</on>
<use_ghs>FALSE</use_ghs>
</random.effects>
<threshold>1.2</threshold>
<update>TRUE</update>
</meta.analysis>
```
Perhaps `ghg` is also need to be made sure to be a factor. @dlebauer what do you think?
> minor MA fix

- CHANGELOG.md
- modules/photosynthesis/R/fitA.R
Addresses two issues in #2672 
* Checks if Tleaf provided in C; if so, convert to K
* If Tleaf not provided, set to 25C and send warning
> fix Tleaf assumptions in fitA

- docker/depends/pecan.depends.R
- modules/assim.sequential/DESCRIPTION
- modules/assim.sequential/R/sda_plotting.R
- modules/assim.sequential/tests/Rcheck_reference.log
A couple of minor review suggestions that I was too slow to get into #2735, plus a cleanup of the cached check results while I was at it.
> Cleanup from #2735

- modules/data.atmosphere/R/download.MERRA.R
- modules/data.atmosphere/tests/testthat/test.download.MERRA.R
Download the direct PAR, diffuse PAR, direct NIR, and diffuse NIR, and, in addition to storing these individual components, also aggregate them as diffuse SW = diffuse PAR + diffuse NIR and direct SW = direct PAR + direct NIR.
Also, shorten the MERRA test from 10 days to 4, so it finishes faster.
> Partition SW radiation in MERRA

- modules/data.atmosphere/R/debias_met_regression.R
- modules/data.atmosphere/R/tdm_lm_ensemble_sims.R
- modules/data.atmosphere/man/debias.met.regression.Rd
Make met sanity bounds in the downscaling routines in line with ED2 limits.  
ED2 is probably more rigid than most other models and the product of the downscaling routines would fail ED sanity checks for future simulations.  Down the road it might make sense to let the user pass in a matrix of sanity bounds, but I don't have the bandwidth to robustly code that at the moment.
- [?] Bug fix (non-breaking change which fixes an issue) 
(Not really a bug as it worked as intended, but just needed to be more rigid to work for ED2.)
> update met downscaling sanity bounds

- .github/workflows/ci.yml
Trying to resolve, `Error in get(genname, envir = envir) : object 'testthat_print' not found`.
See discussion here: https://github.com/r-lib/devtools/issues/2309#issuecomment-773572728
> Force update testthat in test and check GH actions

- CHANGELOG.md
- models/biocro/R/model2netcdf.BIOCRO.R
allow BioCro module to export AGB
> add aboveground biomass to BioCro output

- .github/workflows/ci.yml
> avoid failing builds from R using an unreliable time service

- .github/workflows/ci.yml
...and while I was at it I removed all the `_R_CHECK*_` variables from other jobs -- they have no effect when not running `R CMD CHECK`, so including them elsewhere is only confusing.
> hotfix for defect in #2792:  Needed to set flag in check job not build

- .github/workflows/ci.yml
Arguably this should be in the depends image instead of the CI, but this should unstick builds right away without waiting for Docker images to update
> install dev version of processx

- base/db/R/dbfiles.R
Bug Fix
The dbfile.input.check function was not able to find existing met data for NOAA sites. Traced the issue to the if/else statement that creates the input object, when you include the enddate argument the input object returns wit 0 observations. So I substituted in a new if/else statement that does not use the enddate argument to create the input object.
With this fix I can now successfully run NOAA and NEON sites through the workflow for the EFI Challenge.
> Edited the dbfile.input.check function if/else input statement

- .github/workflows/styler-actions.yml
> update file changes action to avoid error on file rename

- modules/assim.batch/R/pda.define.llik.R
Bug fix in calculation. 
Looks like I was undoing the inflation the old way and the calculation did not properly give the log-likelihood of h. laplace overall. 
I think we will change this logic some more (instead of inflating variance we will weigh the likelihood) but at least this is a bug that needs to be fixed. I thought I would make a PR already in case others are using these functions.
> heteroskedastic laplace likelihood fix

- modules/assim.batch/R/pda.define.llik.R
Remove extra comment lines per @infotroph's suggestion
> Accompanying comment fix to PR2810

- modules/data.atmosphere/R/metgapfill.R
Potentially this was a copy-paste remnant that escaped attention as we mostly have `soil_temperature` in CF files
> fix small typo in metgapfill

- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/depends.yml
- apps/api/R/auth.R
- apps/api/R/available-models.R
- apps/api/R/entrypoint.R
- apps/api/R/formats.R
- apps/api/R/general.R
- apps/api/R/get.file.R
- apps/api/R/inputs.R
- apps/api/R/models.R
- apps/api/R/pfts.R
- apps/api/R/runs.R
- apps/api/R/sites.R
- apps/api/R/submit.workflow.R
- apps/api/R/workflows.R
- use NA instad of NULL in functions, openapi does not know what to do with NULL.
- don't pass in global_db_pool into function, this does not exist in openapi
- fix plumber calls, remove deprecated calls
@moki1202 this will fix problem (hopefully) with api endpoints.
> cleanup/fixes of API

- modules/data.atmosphere/R/download.AmerifluxLBL.R
I was testing met_process Ameriflux functions and trying fresh pulls for some Ameriflux sites, and I've bumped into this issue that download.AmerifluxLBL cannot unzip files.
You can give this a try by
```
sitename <- "US-WCr"
my_tmp_outfolder <- "~/" # specify as you wish
start_date       <- "1998-01-01"
end_date         <- "2020-12-31"
PEcAn.data.atmosphere::download.AmerifluxLBL(sitename, my_tmp_outfolder, start_date, end_date)
SEVERE [PEcAn.data.atmosphere::download.AmerifluxLBL] : 
ZIP file 
...AMF_US-WCr_BASE-BADM_20-5.zip?=pecan 
did not contain CSV file AMF_US-WCr_BASE_HH_20-5.zip?=p.csv 
Error in PEcAn.logger::logger.severe("ZIP file ", output_zip_file, " did not contain CSV file ",  : 
ZIP file  .../AMF_US-WCr_BASE-BADM_20-5.zip?=pecan  did not contain CSV file …
```
> correct zip file name

- DEV-INTRO.md
> one-char typo in DEV-INTRO.md

- .github/workflows/styler-actions.yml
Allows installing packages from remotes when needed
> Set github PAT as env var for /document command

- docker/depends/Dockerfile
Bumps Docker from Roxygen 7.0.2 to 7.1.2 (current release).  As soon as this is merged I will submit part 2, which updates all packages to match.
**This will break all CI jobs!** Sorry for the inconvenience; they should start working again as soon as part 2 is merged.
> Roxygen update step 1: Install on Depends image

- .github/workflows/ci-weekly.yml
- .github/workflows/depends.yml
* Adds a scheduled weekly build of the `depends` image using the latest[1] development version of R
* Adds a weekly (three hours later) Github Actions run using the freshly-build `pecan/depends:Rdevel` image. 
* For the moment the checks performed are a copy-paste of the existing daily test and check jobs and are run only using R-devel. In the future we could add other R versions or further longer-running checks (data availability tests?) as desired.
* The checks are run against the `develop` branch; best I can tell there's no way to change this (scheduled jobs always use the commit at the tip of the default branch), but fortunately I think that's what we want.
[1] Technically we use the latest version of the `rocker/tidyverse:devel` image, which may sometimes be a day or two behind R's …
> [CI] Check against R-devel every Monday

- .github/workflows/ci-weekly.yml
- .github/workflows/ci.yml
- .github/workflows/depends.yml
- .github/workflows/docker.yml
- .github/workflows/styler-actions.yml
- .gitignore
- CHANGELOG.md
- book_source/03_topical_pages/05_models/biocro.Rmd
- book_source/03_topical_pages/93_installation/03_install_OS/06_install_models/install_BIOCRO.Rmd
- docker/depends/pecan.depends.R
- models/biocro/DESCRIPTION
- models/biocro/model_info.json
- scripts/install_pecan.sh
> update actions to work around Git safe directories issue (+BioCro updates from #2925)

- CHANGELOG.md
- DEV-INTRO.md
- base/remote/R/rabbitmq.R
- docker-compose.https.yml
- docker-compose.yml
- docker/env.example
Update traefik (proxy service) to 2.5 from 1.7
Fixes to make rstudio work.
Tested on Mac and Linux
Some changes have been made to the docker-compose file. Check your .env file to
see if you need to change any of these:
- TRAEFIK_HOST is now TRAEFIK_HOSTNAME without the Host: and ;, for example if you have
`TRAEFIK_HOST=Host:pecan.example.com;` you will need to change this to
`TRAEFIK_HOST=pecan.example.com`.
- TRAEFIK_IPFILTER is no longer used, and should be removed.
- TRAEFIK_HTTP_PORT now defaults to port 80
- TRAEFIK_HTTPS_PORT now defaults to port 443
- TRAEFIK_ACME_ENABLE is no longer used. If you want to use https you will need to add
`docker-compose.https.yml` to your command line. You can use the script `compose.sh`
to star PEcAn with https.
- TRAEFIK_HTTPS_OPTIONS is no longer …
> traefik 2.5, also fixes rstudio

- modules/data.mining/tests/testthat.R
Trivial fix for the data.mining tests failing on r-universe... which was suspicious because the data.mining package has no tests
> remove unused utils call in test file

- modules/assim.sequential/inst/MultiSite-Exs/SDA/Create_Multi_settings.R
Upload a script to create multi-site settings using site group ID
> Upload a script to create multi-site settings using site group ID

- docker-compose.yml
This pull request fixes issue #2978  by adding **PEcAn BioCro model runner** in the docker-compose.yml file.
> Fixes issue #2978: BIOCRO model doesn't show up on running PEcAn in docker

- book_source/02_demos_tutorials_workflows/01_install_pecan.Rmd
Adds a suggestion to add a project-level .Rprofile with 
```
options(repos = c(
pecanproject = 'https://pecanproject.r-universe.dev',
CRAN = 'https://cloud.r-project.org'))
```
This has made development of PEcAn with a local install work pretty well for me.  For example, `devtools::install_deps("models/ed")` just works.
Makes local PEcAn development possible if not even easier than developing on docker install
> Minor addition to r-universe install instructions

- docker.sh
I think this will automate updating of this docker image: https://hub.docker.com/r/pecan/model-ed2-git
It has the development version of PEcAn.ED2 and the development version of ED2.
Closes #3030 
Needed an updated container with bugfixes to run ED2 models on an HPC
> build docker image with git version of ED2 also

- CHANGELOG.md
- models/ed/R/modify_ed2in.R
- models/ed/R/read_ed2in.R
- models/ed/R/write.configs.ed.R
- models/ed/R/write_ed2in.R
- models/ed/tests/testthat/data/pecan_checked.xml
- models/ed/tests/testthat/test.write.configs.ed.R
Closes #3034.  Now prints informative error if there are tags not in the ED2IN template and it adds them to the end of the output ED2IN file.  
This change is consistent with what is expected from reading the [PEcAn documentation](https://pecanproject.github.io/pecan-documentation/develop/models-ed.html#models-ed)
> Fix bug in writing new tags to ED2IN

- models/sipnet/R/model2netcdf.SIPNET.R
- models/sipnet/man/model2netcdf.SIPNET.Rd
Test PR for the changes of model2netcdf function.
> Sda dongchen

- DEV-INTRO.md
- docker-compose.dev.yml
- docker/base/Dockerfile
- docker/docker-compose.example.yml
Minor improvements that I noticed as I was trying to get Docker builds running on a new machine. @robkooper please let me know if I'm off-base on any of these.
> Docker tweaks

- book_source/03_topical_pages/03_pecan_xml.Rmd
According to `check.settings()` the `<job.sh>` tag is deprecated in favor of `<prerun>`.  This PR updates the documentation accordingly
> change job.sh tag to prerun

- models/sipnet/R/write.configs.SIPNET.R
- modules/data.atmosphere/man/cos_solar_zenith_angle.Rd
- modules/data.land/R/cohort2pool.R
- modules/data.land/R/extract_NEON_veg.R
> Change from g to kg for SIPNET IC.process

- .github/workflows/docker.yml
- apps/api/Dockerfile
- docker.sh
- docker/base/Dockerfile
- docker/depends/Dockerfile
> [CI] Fix Docker action rate limits, hopefully

- .github/workflows/depends.yml
Missed this in #3083:  Need to enable BuildKit in the job for the depends image too. I keep forgetting those are separate actions.
> [ci] use buildit for depends image too

- .github/workflows/depends.yml
Per https://github.com/elgohr/Publish-Docker-Github-Action/issues/167, the deprecation warnings about `set-output` that @Aariq saw in #3072 weren't fully fixed in V4, so bumping the version once more.
> Bump Publish-Docker-Github-Action to v5

- README.md
PR fixes a broken link to the demo website in the README file ( fixes #3090 )
> Fix broken link (fixes #3090)

- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/docker.yml
Note that this doesn't itself turn on the merge queue option, it just tells Actions to run when a queue tells them to.
> [CI] run on merge queue event

- base/utils/R/utils.R
Closed, GoodFirstIssue
I removed the function that is already included in the base function and achieved resolved the issue as per the requirement.
This is required since already exists one function in the base so don't need to define it in our version.
It helped in preventing any kind of redundancy and any miss information production is prevented.
> The required change in the function is made. Kindly check it once.

- models/sipnet/R/model2netcdf.SIPNET.R
> Refactor `model2netcdf.SIPNET` variable lists

- modules/data.remote/R/NLCD.R
- modules/data.remote/inst/scripts/Download_OSU_AGB_data_v5.R
This PR fixes comments made in PR #3121
> Updated function calls to `utils::download.file()`

- modules/data.atmosphere/R/download.CRUNCEP_Global.R
- modules/data.atmosphere/R/download.NOAA_GEFS.R
- modules/data.atmosphere/man/download.CRUNCEP.Rd
- modules/data.atmosphere/man/download.NOAA_GEFS.Rd
> Fixed typos in `data.atmosphere`

- modules/assim.sequential/R/Analysis_sda_multiSite.R
- modules/assim.sequential/R/sda.enkf_MultiSite.R
- modules/assim.sequential/man/sda.enkf.multisite.Rd
> Added the feature of using existing Pf, aqq, and bqq from the previous enkf.params object for the SDA workflow.

- docker/depends/pecan.depends.R
- modules/assim.sequential/DESCRIPTION
- modules/assim.sequential/R/Nimble_codes.R
- modules/assim.sequential/R/SDA_OBS_Assembler.R
- modules/assim.sequential/R/sda.enkf_MultiSite.R
- modules/assim.sequential/R/sda_weights_site.R
> Fix indexing issue when there is only one observation with one state variable for the SDA workflow.

- base/visualization/.Rbuildignore
- base/visualization/R/map.output.R
- base/visualization/R/visually.weighted.watercolor.plots.R
- base/visualization/tests/Rcheck_reference.log
The PR is aimed at fixing the "no visible binding for global variable" notes for `base/visualization`
> Fixing Notes in `base/visualization`

- models/ed/R/model2netcdf.ED2.R
Apparently https://github.com/PecanProject/pecan/pull/3140 didn't fix this bug entirely.  If a PFT is missing from the ED2 output for a full year, then there were still problems with the dimensions.  Instead of using the ED2 output to figure out what PFTs need to have `NA`s for the output, this PR changes it to use the PFTs supplied by the user (e.g. in `settings`).
> `model2netcdf.ED2()`—Fix dimension issues when PFTs missing from ED2 output (Follow up on #3140)

- models/fates/R/model2netcdf.FATES.R
- models/fates/tests/Rcheck_reference.log
- models/gday/R/model2netcdf.GDAY.R
- models/gday/tests/Rcheck_reference.log
- models/jules/R/model2netcdf.JULES.R
- models/jules/R/write.config.JULES.R
- models/jules/tests/Rcheck_reference.log
This PR fixes notes : `no visible global function definition` for some `model` packages
> Fixed notes for some `model` packages

- modules/assim.sequential/R/SDA_OBS_Assembler.R
- modules/assim.sequential/R/sda.enkf_MultiSite.R
- modules/assim.sequential/inst/MultiSite-Exs/SDA/Create_Multi_settings.R
> Bug fixes for Obs_Assembler and SDA script.

- modules/assim.sequential/R/SDA_OBS_Assembler.R
- modules/assim.sequential/inst/MultiSite-Exs/SDA/Create_Multi_settings.R
> Bug fixes for Obs Assembler function.

- modules/data.land/R/DataONE_doi_download.R
- modules/data.land/tests/Rcheck_reference.log
Removing some unneeded superassignments to variables that are used only in local contexts.
Replaced my computer and am going through long-forgotten stashes in my development forks, including this one that I apparently committed *three years ago* but never pushed until now [:homer-disappear:]
> data.land: cleanup on data one

- modules/assim.sequential/R/SDA_OBS_Assembler.R
- modules/assim.sequential/R/sda.enkf_MultiSite.R
- modules/data.remote/R/Landtrendr_AGB_prep.R
- modules/data.remote/man/Landtrendr_AGB_prep.Rd
> Bug fixes for Obs prep functions and SDA script.

- modules/assim.batch/R/pda.utils.R
- modules/assim.batch/man/pda.adjust.jumps.bs.Rd
- modules/assim.sequential/R/Analysis_sda.R
- modules/assim.sequential/R/Analysis_sda_multiSite.R
- modules/assim.sequential/R/Helper.functions.R
- modules/assim.sequential/R/Localization.R
- modules/assim.sequential/R/Multi_Site_Constructors.R
- modules/assim.sequential/R/sda.enkf_MultiSite.R
- modules/assim.sequential/R/sda.enkf_refactored.R
- modules/assim.sequential/inst/sda_backup/bmorrison/Multi_Site_Constructors.R
- modules/assim.sequential/man/Analysis.sda.Rd
- modules/assim.sequential/man/Construc_H.Rd
- modules/assim.sequential/man/EnKF.MultiSite.Rd
- modules/assim.sequential/man/EnKF.Rd
- modules/assim.sequential/man/Local.support.Rd
- modules/assim.sequential/man/SDA_control.Rd
- modules/assim.sequential/man/block_matrix.Rd
- modules/assim.sequential/man/piecew.poly.local.Rd
- modules/assim.sequential/man/sda.enkf.Rd
- modules/assim.sequential/man/sda.enkf.multisite.Rd
- modules/assim.sequential/man/simple.local.Rd
This PR fixes some typos **mostly** in `assim.sequential` package that I came across while reading function descriptions.
> Fixed typos in `assim.sequential` package function descriptions

- modules/assim.sequential/R/Analysis_sda_multiSite.R
- modules/assim.sequential/R/Multi_Site_Constructors.R
- modules/assim.sequential/R/SDA_OBS_Assembler.R
- modules/assim.sequential/R/metSplit.R
- modules/assim.sequential/R/sda.enkf_MultiSite.R
- modules/assim.sequential/man/sda.enkf.multisite.Rd
> Refinements and bug fixes for the current SDA workflow.

- modules/assim.sequential/inst/SDA_runner.R
> Update SDA_runner script.

- modules/assim.batch/R/plot.da.R
- modules/priors/R/plots.R
- modules/priors/man/plot_trait.Rd
- modules/priors/man/priorfig.Rd
- modules/priors/vignettes/priors_demo.Rmd
This PR tries to address #729 and #1747
> Removing Dependency on `trait.lookup`

- modules/data.atmosphere/R/download.NARR_site.R
- modules/data.atmosphere/R/met2CF.csv.R
... And then fix some data-mask messages that it was inadvertently masking.
> data.atmosphere: Delete unused helper function

- README.md
The README documentation has been updated to correctly redirect the hyperlinks to landing page for [virtual machine](https://pecanproject.github.io/pecan-documentation/develop/install-vm.html#install-vm) and [docker](https://pecanproject.github.io/pecan-documentation/develop/install-docker.html#install-docker)
This PR fixed the issue #3178
> docs: Update README.md for correct hyperlink redirect

- DEV-INTRO.md
There were a few typos in the documentation
Fixed the typos :)
> docs: Fix Small Typo in DEV-INTRO.md

- base/qaqc/DESCRIPTION
- base/qaqc/R/find_formats_without_inputs.R
- base/qaqc/R/find_inputs_without_formats.R
- base/qaqc/R/get_table_column_names.R
- base/qaqc/R/taylor.plot.R
- base/qaqc/R/write_out_table.R
- base/qaqc/man/find_formats_without_inputs.Rd
- base/qaqc/man/find_inputs_without_formats.Rd
- base/qaqc/man/get_table_column_names.Rd
- base/qaqc/man/write_out_table.Rd
- base/qaqc/tests/testthat/test.cull_database_entries.R
- base/qaqc/tests/testthat/test.find_formats_without_inputs.R
- base/qaqc/tests/testthat/test.find_inputs_without_formats.R
- base/qaqc/tests/testthat/test.get_table_column_names.R
- base/qaqc/tests/testthat/test.write_out_table.R
PR aims at improving unit test coverage for `PEcAn.qaqc` package
> Improving test coverage for `PEcAn.qaqc` package

- apps/api/R/submit.workflow.R
The rpecanapi for POST request to submit a workflow was failing since a long time with an internal server error.
As discussed in the google meet, This PR fixes pecanproject/rpecanapi#20
cc: @robkooper
> fix: rabbitmq_post_message in Submit.Worflow Post API

- modules/data.atmosphere/inst/integrationTests/test.download.AmerifluxLBL.R
- modules/data.atmosphere/inst/integrationTests/test.download.ERA5.R
Fixing integration tests to bring `tmpdir` in scope of `test_that`.
> Fixing Integration Tests

- modules/data.atmosphere/inst/integrationTests/test.download.AmerifluxLBL.R
- modules/data.atmosphere/inst/integrationTests/test.download.CRUNCEP.R
- modules/data.atmosphere/inst/integrationTests/test.download.ERA5.R
This PR tries to change the way we access functions from a package in integration tests.
> Updated Integration Tests

- book_source/_bookdown.yml
Updates the URL at which a person can edit the documentation when a change is needed to a particular page.
> Updated edit URL for PEcAn Documentation

- README.md
Corrected typos in the README.md file for improved readability and accuracy.
- [ x] Immediately
- [x ] Bug fix (non-breaking change which fixes an issue) 
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.
> Fix typos in README.md for improved readability and accuracy

- Makefile
...instead of  devtools::install, which insists in checking for updates to all dependencies every call, even when `upgrade = FALSE`. 
Across all packages this adds up to a lot of repeated checks, and in combination with our separate dependency check it's enough to exceed GitHub APi request rate limits during CI builds.
remotes::install_local appears to not check dependencies at all when dependencies=FALSE, which is what we want for this case.
(Side note: The `force=TRUE` is needed to make sure Make reinstalls your changes during local development, because `install_local` defaults to not installing the package if its "SHA has not changed"... but for local packages it treats the package version string as the "SHA" and doesn't notice edits that don't change the version.)
> Makefile: install with remotes::install_local

- .github/workflows/book.yml
- base/db/DESCRIPTION
- base/qaqc/DESCRIPTION
- docker/depends/pecan_package_dependencies.csv
- docker/docs/Dockerfile
- modules/allometry/DESCRIPTION
- modules/assim.batch/DESCRIPTION
- modules/meta.analysis/DESCRIPTION
- modules/photosynthesis/DESCRIPTION
- modules/rtm/DESCRIPTION
Hopefully for real this time: Fixes `xfun::isFALSE` deprecation warnings by updating knitr and rmarkdown to versions that use base::isFALSE internally. 
Note that as wirtten, the check and renderbook jobs will fail one more time on this PR:
* The current build of the depends image is in an inconsistent state where {knitr} is still old but {xfun} has already been updated to a newer version that complains when you use an old {knitr}.
* Therefor the check job is going to fail because `pecan.depends.R` tries to install BioCro (and fails because the old knitr can't compile its vignettes) before it gets to the line that will update knitr. 😞 
* If the Docker CI job passes, it should be OK to merge this with the other checks failing. That will bring the depends image back into a …
> Require newer knitr and rmarkdown everywhere

- modules/assim.sequential/R/Analysis_sda_block.R
- modules/assim.sequential/R/Nimble_codes.R
> Solve convergence issue for the Tobit Gamma and Wishart Q; Allows for NA observations under block mode (scaled > 0)

- base/remote/R/qsub_parallel.R
- modules/assim.sequential/R/Analysis_sda_block.R
> Bug fixes for the progress bar in the qub_parallel function and Q type identification in the analysis_SDA_block function. 

- Makefile
feels cleaner, and allows skipping compilation on machines where a binary of the correct Roxygen version is available.
> [build] Makefile: Install fixed roxygen version from CRAN archive instead of github tag

- modules/assim.sequential/R/Analysis_sda_block.R
Rebuild logic between partial missing observations and complete missing observation (free run case), and fixed some edge cases for the wishart Q.
The free run is different than a normal run with partial missing observations for specific sets of sites. For the free run, we will estimate all state variables based on previous states and the potential Q from outside. For the normal run with partial missing observations, we will estimate state variables that match up with maximum types of observations across all sites. For the Wishart Q, some edge cases such as single site with single observation will be treated as Normal-Gamma conjugacy instead of MVN-Wishart conjugacy.
> Rebuild logic between partial missing observations and complete missing observation (free run case), and fixed some edge cases for the wishart Q.

- .github/labeler.yml
- .github/workflows/prlabeler.yml
Fix for a bug in #3204: Every PR was being labeled `tests`. 
This was caused by V4 of `actions/labeler` combining multiple rules for a label with OR rather than the AND its documentation implied, so `'!**/tests/Rcheck_reference.log'` was matching on _any_ file that wasn't Rcheck_reference.log, whether or not it was in a test directory.
Fixed by updating to `actions/labeler@V5`, which uses a more verbose but clearer rule notation.
> Labeler fix

- CHANGELOG.md
- base/db/NEWS.md
- models/ed/NEWS.md
- modules/data.atmosphere/NEWS.md
- modules/data.land/NEWS.md
- modules/emulator/NEWS.md
Tried to organize existing entries a bit and added a couple I noticed missing. Feel free to edit more!
> polishing NEWS files for release

- modules/assim.sequential/inst/covariates.R
This PR aims to fix a potential discrepancy in one of the arguments in resampling soil grids.
In the previous resampling caused discrepancy in extent of soil grids because it matched NA_WorldClim to NA_SoilGrids, whilst the intended operation was to match NA_SoilGrids to NA_WorldClim.
> Fixed possible arg discrepancy

- CHANGELOG.md
- shiny/Elicitation/LICENSE
- shiny/dbsync/LICENSE
Updating license file upon noticing that we have agreement from all authors:
* dbsync: @infotroph, @robkooper, @istfer
* Elicitation: @infotroph, @mdietze, @robkooper, @tonygardella.
> Relicense shiny/dbsync and shiny/Elicitation to BSD3
