PecanProject/pecan

- modules/meta.analysis/R/run.meta.analysis.R
set defaults for new arguments to run.meta.analysis for backward compatibility 
* GRMVPRF diagnostic threshold = 1.2;  
* random (use effects in model) = TRUE
> Added defaults to run.meta.analysis

- models/biocro/R/write.configs.BIOCRO.R
- models/dalec/R/write.configs.dalec.R
- models/ed/R/write.configs.ed.R
- models/linkages/R/write.config.LINKAGES.R
- models/sipnet/R/write.configs.SIPNET.R
- models/template/R/write.config.MODEL.R
- modules/data.atmosphere/R/met.process.R
- settings/R/read.settings.R
- tests/workflow.R
- web/04-runpecan.php
- web/config.example.php
- web/workflow.R
All inputs now have a id and path fields that contains the information
needed for write configs.
Also added code to copy over url/username/password for browndog from
~/.pecan.xml, only if a browndog entry exists in pecan.xml
> use path/id fields in inputs #356

- models/ed/R/met2model.ED2.R
no rounding of lat/lon, but use site info as center of polygon. The rounding would result in the site sometimes to fall outside of the polygon when running ED.
An [example](http://pecan.ncsa.illinois.edu/pecan/08-finished.php?workflowid=99000000020) of an ED run at Willow Creek (US-WCr) using Ameriflux.
> use real lat/lon for DRIVER file

- modules/data.atmosphere/R/metutils.R
- modules/data.atmosphere/vignettes/ameriflux_demo.Rmd
@bcow @jam2767 
regarding the documentation suggested in #404, this vignette provides an example of how to use `download.Ameriflux` and `met2cf.Ameriflux`. Would be great to have similar examples for other functions. It's really just an annotated script of a use of these functions (e.g. I created this because I found it useful for a separate analysis).
> added ameriflux vignette refs #404

- modules/data.atmosphere/R/met2CF.csv.R
A function called datetime was being called from earlier in the code and it was breaking. I created a datetime function after many trials and errors to handle iso8601 dates that do not include seconds from csv files.
> Added a datetime function to better handle dates

- db/R/dbfiles.R
Per Rob's direction at gh-494, dbfile.insert now checks first to
see if a file already exists at the requested machine/path/file
location. If so, then the function returns that record's ID or NA,
depending on whether a new 'reuse' argument is T or F, repsectively.
If no file already exists, then a new record is inserted, and its ID is
returned (as before).
I noticed the function header said it returns a data frame of several
relevant values, but actually only the ID was being returned. Updated
this documentation as well.
> Make sure dbfile is unique (gh-494)

- modules/data.atmosphere/R/metutils.R
Still need to change units to be same for both functions and met2CF Ameriflux/CSV/ALMA and temporal downscaling need to pass pressure; two of these functions don’t read in pressure currently. qair2rh is called in met2model for BIOCRO/SIPNET and temporal downscaling, so if units change, these will need to change too.
> Rewrote rh2qair to account for air pressure. Now true inverse of qair2rh

- scripts/load.bety.sh
@RobKooper  Let me know if you think this looks OK?  I tested this link with curl -L -o and it worked out for me; i.e. pulled the bety.tar.gz off the dropbox.
This is the temp link.  I will be updating once our sever is open to the world.  It will then be:
modex.test.bnl.gov/sync/dump/bety.tar.gz
> Update to load.bety.sh to include temp BNL sync location

- modules/uncertainty/R/run.ensemble.analysis.R
- utils/R/get.analysis.filenames.r
Got a little bit kludgey, but should work. 
Once workflows (and maybe other functions?) are updated to avoid `sensitivity.analysis$ensemble.id = NULL` or `ensemble$ensemble.id = NULL`, the kludge won't be needed anyway. 
Actually, as far as I can tell, simply adding `settings <-` in front of `run.write.configs(...)` in all workflows would ensure that files are always saved with actual ensemble IDs, rather than the dummy "NOENSEMBLEID". That's because I modified `run.write.configs()` awhile back to add the SA and EA ensemble ids to `settings`, and invisibly return the updated list. But we can worry about that later.
> bugfix filenames

- modules/assim.batch/R/pda.mcmc.recover.R
- modules/assim.batch/R/pda.utils.R
- modules/uncertainty/R/get.samples.R
- utils/R/run.write.configs.R
Fixed conflict with some of @dlebauer 's changes since v1.4.3, that had disabled a feature I added to allow `run.write.configs()` to be called on a specific prior. or post.distns file.
> Pda.block+emulator

- scripts/load.bety.sh
- web/PEcAn.Network.R
- web/status.php
The idea is to have a dashboard that shows which machines are up and of those which are up-to-date vs running an older schema -- this part is bare-bones but largely working at this point (Shawn's files on Dropbox are confusing the code a tad). I also plant to extend this to also plot the edges of the network to show when syncs are up-to-date, out-of-date, and failing -- this will require some small changes to the db dump and load functions.
Initial prototype is visible at https://pecan2.bu.edu/pecan/status.php
Green = good
Yellow = old schema
Red = down
Purple = Shawn's Dropbox (which evidently is on a server in CA)
> Initial code for webpage that displays PEcAn network status

- web/03-inputs.php
This fix is for enhancement 453.  I am using the inputs.name field for the met names instead of "weather + year".
I also added the bety database link to this field label.
Now the met input.names field will need to be populated with values or the default logic of "weather+year" will show.
All modification were done in file 03-inputs.php
> Informative met names 453

- scripts/dump.bety.sh
- scripts/load.bety.sh
- web/PEcAn.Network.R
now writes a triple to versions.txt
- number of migrations
- hash of all migrations combined
- latest migration applied
This will use the hash to check for version, even if an older migration
is applied this will make it so the version check still fails (step
closer for #160).
> better version check

- scripts/build.sh
In order to prevent failed builds due to lock files, I added 
```sh
if [ "$FORCE" == "yes" ]; then
rm -rf ${R_LIBS_USER}/00LOCK-*
fi
```
Alternative would be to _always_ remove these files.
Not sure if this would have unintended consequences or if there is a more suitable approach.
> build: remove lock files if $FORCE = 'yes'

- modules/data.atmosphere/R/met2CF.NARR.R
During met.process, the function convert.input runs ```met2CF.NARR``` effectively opening an instance in R. The ```lubridate``` package needs to be loaded again in order for the function to be able to use the function ```year```. This should close #723.
@ashiklom
> Function 'year' is called without loading lubridate in met2CF.NARR

- models/ed/R/met2model.ED2.R
- scripts/install.dependencies.R
This should close #725. The CRUNCEP met product is missing an observation, making a mismatch of time dimensions and observations when the met is formatted for the model. In this case, the required changes were already made to SIPNET's met2model script so it was a simple matter of doing the same thing and testing it.
@ashiklom @araiho not sure if we've rotated code reviewers yet so I mentioned you both.
> met2model.ED: fix to building time dimension so it works with cruncep

- models/ed/R/met2model.ED2.R
I made a mistake when I copy and pasted my changes from the script that I tested in the release candidate. I now tested these changes on the BU server, where I made the changes, and it does not throw errors at this step any more. 
Closes #737 @serbinsh. This should fix that error.
> Entering skip<- FALSE and mo<-day2mo() lines in met2model.ED2

- models/sipnet/R/met2model.SIPNET.R
* can now take wind_speed as scalar OR vector (i.e. does not fail if eastward_wind does not exist)
* removed query of variable air_pressure (which was not used)
> minor revisions to met2model.SIPNET

- models/maespa/R/write.config.MAESPA.R
- models/maespa/inst/template.job
Change to allow write.configs to read met from db. Also, fix to file path to job.sh so it could be chmoded correctly. 
Change to template.job because symbolic link did not have correct permissions so I just made it copy example input files directly.
> MAESPA: change to write.configs and template.job

- utils/R/ensemble.R
Currently two methods are implemented in the get.ensemble.samples function: halton and uniform.
Regarding #491, I just added additional methods to generate ensemble samples: sobol and torus from randtoolbox (we were already using the halton function from this package), and @mdietze's lhc function from emulator package.
@ashiklom is up for review
> additional ensemble samplers

- models/ed/inst/template.job
This solves the issue for #761 where ED failures are not detected. Most
of the job scripts assume the model exits with 0 if everything was ok,
and anything else if there was an error code. ED always exits with 0.
> detect error in ED

- modules/assim.batch/R/pda.utils.R
I just found out that I need to add some checks for a few of the BayesianTools specific settings, otherwise if they're NULL (it's fine for them to be NULL but) as.numeric converts them to `numeric(0)` which causes an error.
@mdietze it would be great if it can make it to the VM
> add few checks in the pda.settings.bt function

- models/maespa/R/met2model.MAESPA.R
@mdekauwe thank you for all the fixes. I definitely need to improve on making my code cleaner and more readable. 
For ```SW``` I had read it in with the MAESPA variable name ```RAD```.  To get PAR from ```RAD``` we had a function in our data.atmosphere package that I've implemented here.
> Fix for met2model.MAESPA

- models/gday/R/met2model.GDAY.R
Various bug fixes to met2model.GDAY.R 
Key change:
- no longer writing the GDAY met header information. All units are declared in the translation script and seeing as the met file is transferred internal there probably isn't much need for it.
To do:
- when we split GDAY into day & sub-daily versions, then we can split the if and else blocks into two scripts.
Still potential gotchas:
- Some of the gap-filled met files seem to be missing afternoon PAR values entirely. This would lead to GDAY crashing and most likely other models.
- This should probably be fixed at the met creation stage. We could add a check during the translation but I'd argue this is a data issue rather than a model issue.
> Bug fixes to gday met2model

- modules/rtm/DESCRIPTION
- modules/rtm/NAMESPACE
- modules/rtm/R/check.convergence.R
- modules/rtm/R/defparam.R
- modules/rtm/R/edr.wrapper.R
- modules/rtm/R/invert.auto.R
- modules/rtm/R/invert.custom.R
- modules/rtm/R/invert.fast.R
- modules/rtm/R/invert.fast.re.R
- modules/rtm/R/invert.lsq.R
- modules/rtm/R/process-output.R
- modules/rtm/man/generate.rsr.all.Rd
- modules/rtm/man/invert.auto.Rd
- modules/rtm/tests/testthat/test.invert.R
- modules/rtm/tests/testthat/test.prospect.R
- modules/rtm/tests/testthat/test.sail.R
Run multiple MCMC chains in parallel using the `parallel` package. This significantly reduces computational time.
@istfer is up for review.
> Add parallel functionality to PEcAnRTM::invert.auto

- models/sipnet/R/model2netcdf.SIPNET.R
- models/sipnet/R/write.configs.SIPNET.R
- models/sipnet/inst/template.job
I first changed the header and the variables that are being written in /fs/data5/pecan.models/SIPNET/trunk/sipnet.c so they match (header being written in L784, acsii outputs are written in L817, csv in L838)
Now the header agrees with both the ascii and csv outputs ( I don't know whether sipnet maintainers would be happy with the change).
To be able to make model2netcdf.SIPNET compatible with different SIPNET revisions I modified it, now revision info is being passed from template.job. I only changed things for evapotranspiration but r136 version of SIPNET gives outputs such as fPAR, rh ra too. Unfortunately I have to leave now to finish packing for the field!
> changes to use SIPNET r136 outputs with corrected header

- modules/data.atmosphere/R/download.GLDAS.R
- modules/data.atmosphere/R/download.NLDAS.R
Two functions to pull from the Land Data Assimilation Service (LDAS):
1. NLDAS = North American LDAS; hourly, 0.125-degree resolution. Data available from 1979-present.  see: [documentation](
http://disc.sci.gsfc.nasa.gov/uui/datasets/NLDAS_FORA0125_H_V002/summary)
2. GLDAS = Global LDAS; I’ve pulled the one with higher spatial &
temporal resolution (0.25-degree, 3-hr), but the new version that goes
back to 1949 isn’t on threads yet.  Current data availability for the dataset referenced in the code (NOAH) is only 2000-present.  Code could easily be changed to select a different model or pull the 1-degree resolution data that goes back to 1979. see:
[documentation](http://disc.sci.gsfc.nasa.gov/uui/datasets/GES_DISC_GLDAS_NOAH025SUBP_3H …
> New download functions!

- modules/data.atmosphere/R/download.Ameriflux.R
- modules/data.atmosphere/man/download.Ameriflux.Rd
US-UMB has both hourly and half-hourly files, a use case not considered by download.Ameriflux. As far as I know, this is the only site that acts this way. So added a small hack if site=US-UMB. If for some reason other sites have separate hourly and half-hourly, then we could generalize it later.
> Small fix to download.Ameriflux

- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.load.data.R
- modules/assim.batch/man/pda.emulator.Rd
- modules/assim.batch/vignettes/AssimBatchVignette.Rmd
- modules/emulator/R/minimize.GP.R
- modules/emulator/R/update.jump.R
Rainy afternoon in Bartlett :)
I made changes for the emulator code to propose values with mvrnorm. It was a little quick and dirty fix (it now uses `pda.adjust.jumps.bs` of block sampling code as well) but it should do the job for the flux course.
I also made some changes to the pda.load code as I missed to pass input.id/variable.id info along with `inputs` list in the latest changes (because it was `bety$write=FALSE` in my pecan.xml while I was testing it) which is necessary to associate the likelihoods with inputs in BETY.
@jam2767 is up for review (although I may not be prompt with my replies)
> adding mv for emulator

- modules/data.atmosphere/R/met2CF.Ameriflux.R
Raw Ameriflux VPD is in kPa. The conversion that already was there just multiplied by 1000, effectively converting kPa to Pa. The unit was  mol/m2/s1 however, so this just needed a change to the unit name, not a conversion. This should close #692
> Corrected units of VPD in met2CF.Ameriflux from mol/m2/s1 to Pa

- modules/data.atmosphere/R/download.GFDL.R
Added this so different experiments/scenarios across the same GFDL model could be tagged properly. Also, discovered that lat/lons were off by 1 because OPeNDAP indexes start at 0, not 1. Same was true for CRUNCEP, told Christy about the error for her pull request.
> download.GFDL output file descriptors

- modules/data.atmosphere/R/metgapfill.R
Small typo that was making Fluxnet2015 fail.
> missingair to missingarr typo in metgapfill

- modules/data.atmosphere/R/download.AmerifluxLBL.R
- modules/data.atmosphere/R/download.Fluxnet2015.R
- modules/data.atmosphere/R/met.process.R
username defaults to pecan, passed to download functions as username=username from met.process. next step is to fix workflow to read username from settings and pass to met.process.
> Username passing for download fluxnet/ameriflux

- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.utils.R
Here are the changes I've made so far. I'm still updating the chunks that are there for extension runs (see my previous PR) but still wanted to push this without waiting any longer so that I can include other suggestions asap.
There were too many little details and I changed design more than once on the way, so there can easily be  redundancies or bugs. But it runs a first round of emulator for more than one PFTs/parameters/chains without any errors, at least without me noticing.
@araiho is up for review, although @mdietze definitely needs to chime in
here is the `assim.batch` formatting I'm using to make it work
```
<assim.batch>
<method>emulator</method>
<n.knot>10</n.knot>
<iter>200</iter>
<chain>3</chain>
<param.names>
<soil>
<param>som_respiration_rate</param>
</soil> …
```
> Generalize emulator code for >1 PFTs

- scripts/Rfcn.R
- scripts/dependencies.R
- scripts/install.dependencies.R
- scripts/pft.add.spp.R
- scripts/quickbuild.R
- scripts/workflow.bm.R
- scripts/workflow.pda.R
- scripts/workflow.treering.R
Ran through `formatR::tidy_dir`; added `@param` roxygen fields;
standardized indents; made sure all `if` blocks have braces; changed to
`paste0` where applicable; cracked down on over-length lines.
> Style cleanup for `scripts/*.R` scripts

- db/R/query.site.R
- db/R/query.trait.data.R
Proposed fixes for issues #1040 and #1041. Re 1041, I’m assuming that`arrhenius.scaling.traits` and `filter.sunleaf.traits` should return NULL if there are no covariates.
> Fix end-of-function problems (#1040 and #1041)

- models/fates/R/met2model.FATES.R
- models/fates/R/model2netcdf.FATES.R
- models/fates/R/recurse.create.R
- models/fates/R/write.configs.FATES.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all `if` blocks have braces; took advantage of paste0 and file.path; changed require calls to library. Tried to make sure formatR didn’t make things too jaggy. Moved ellipses to end of met2model definition.
> Style cleanup for `models/fates/R/*.R` scripts 

- models/dalec/R/met2model.DALEC.R
- models/dalec/R/model2netcdf.DALEC.R
- models/dalec/R/write.configs.dalec.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces; took advantage of paste0 and file.path; changed require calls to library.
Note - got rid of extra params (…) in `met2model.DALEC`. They weren’t last, which was odd, and weren’t used.
> Style cleanup for `models/dalec/R/*.R` scripts

- models/ed/R/get.model.output.ed.R
- models/ed/R/met2model.ED2.R
- models/ed/R/model2netcdf.ED2.R
- models/ed/R/parse.history.R
- models/ed/R/write.configs.ed.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces; took advantage of paste0 and file.path; changed require calls to library. Tried to make sure `formatR` didn’t make things too jaggy. Moved ellipses to end of met2model definition.
> Style cleanup for `models/ed/R/*.R` scripts

- models/gday/R/met2model.GDAY.R
- models/gday/R/model2netcdf.GDAY.R
- models/gday/R/write.config.GDAY.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces; took advantage of paste0 and file.path; changed require calls to library. Tried to make sure formatR didn’t make things too jaggy. Moved ellipses to end of met2model definition.
Fixes issue #1049.
> Style cleanup for `models/gday/R/*.R` scripts 

- models/sipnet/R/get.model.output.SIPNET.R
- models/sipnet/R/met2model.SIPNET.R
- models/sipnet/R/model2netcdf.SIPNET.R
- models/sipnet/R/read.restart.SIPNET.R
- models/sipnet/R/sample.IC.SIPNET.R
- models/sipnet/R/split.inputs.SIPNET.R
- models/sipnet/R/write.configs.SIPNET.R
- models/sipnet/R/write.restart.SIPNET.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Moved ellipses to end of `met2model.MAESPA.R` declaration. Substituted `seq_len`, `seq_along`, and `paste0`.
> Style cleanup for `models/sipnet/R/*.R` scripts

- models/maespa/R/met2model.MAESPA.R
- models/maespa/R/model2netcdf.MAESPA.R
- models/maespa/R/write.config.MAESPA.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Moved ellipses to end of `met2model.MAESPA.R` declaration. Substituted `seq_len` and `seq_along`.
> Style cleanup for `models/maespa/R/*.R` scripts 

- models/ed/R/write.configs.ed.R
`write.configs.ed` checks that the paths for the ED css, pss, and site files match, and throws an error if they don't.
To make it easier to diagnose errors related to this, I added `print` statements so that the paths are visible on exit.
> ED verbose path matching

- models/ed/R/write.configs.ed.R
Latitude and longitude should be in every prefix, and therefore *not* optional. Also, `lat` is not followed by a literal period. New regular expression should correctly match `.lat<coord>lon<coord>.css/pss/site`.
> Fix buggy regular expression in write.configs.ed

- web/04-runpecan.php
make sure there are no spaces around the params which can trigger an error in insert workflow.
https://gitter.im/PecanProject/pecan?at=57fce8724fde72031429acfa
> make sure there are no spaces at beginning/end of params

- utils/R/SafeList.R
- utils/R/clear.scratch.R
- utils/R/convert.input.R
- utils/R/distn.stats.R
- utils/R/do.conversions.R
- utils/R/download.url.R
- utils/R/ensemble.R
- utils/R/fqdn.R
- utils/R/full.path.R
- utils/R/get.analysis.filenames.r
- utils/R/get.model.output.R
- utils/R/get.results.R
- utils/R/help.R
- utils/R/kill.tunnel.R
- utils/R/logger.R
- utils/R/mail.R
- utils/R/n_leap_day.R
- utils/R/plots.R
- utils/R/r2bugs.distributions.R
- utils/R/read.output.R
- utils/R/regrid.R
- utils/R/remote.R
- utils/R/remove.config.R
- utils/R/run.write.configs.R
- utils/R/sensitivity.R
- utils/R/start.model.runs.R
- utils/R/status.R
- utils/R/transformstats.R
- utils/R/utils.R
- utils/R/write.config.utils.R
Ran through formatR::tidy_dir with arrow=TRUE and indent=2; made sure all if blocks have braces. Tried to make sure formatR didn’t make things too jaggy. Substituted `seq_len`, `seq_along`, and `paste0`, and `file.path` as necessary. Made sure all functions end with an explicit `return`.
**Non-style notes:**
* `convert.input`: changed GMT to UTC; added if-block failure case
* `sendmail`: note new line 32 (`sendmail <- Sys.which("sendmail")`) -
OK?
* `bugs.rdist`: added if-block failure
* added if-block failure to `misc.convert`
> Style cleanup for `utils/R/*.R` scripts 

- scripts/install.dependencies.R
Removed responsibility for handling `car` dependency  from `install.dependencies`.
Removed car from package list in scripts/install.dependencies; made
sure it was listed in package DESCRIPTION files; removed `library`
calls; added `car::` namespace to function calls. See #1088.
[In this case, `car` is only used by `modules/data.remote/inst/`
scripts, so didn't need to do anything.]
There shouldn't be any need for install.dependencies to do most of what it does.
> Move responsibility for handling `car` dependency 

- scripts/install.dependencies.R
Removed responsibility for handling `car` dependency  from `install.dependencies`.
Removed responsibility for handling `car` dependency  from `install.dependencies`. [In this case, `car` is only used by `modules/data.remote/inst/` scripts, so didn't need to do anything.]
There shouldn't be any need for install.dependencies to do most of what it does.
> Move responsibility for handling `chron` dependency

- Makefile
- db/man/get.trait.data.Rd
- db/man/get.trait.data.pft.Rd
- settings/DESCRIPTION
- utils/man/do.conversions.Rd
* Fix Makefile dependencies so that required installs happen before documentation.
* Fix Makefile bug where package root directory (DESCRIPTION, NAMESPACE, etc.) was ignored in rules
* Fix trailing comma in `settings/DESCRIPTION` file `Depends` field.
* Update documentation for a few packages where it was out of date (just running `roxygenize`).
Suppose `pkg2` depends on `pkg1`. `devtools::document('pkg2')` will fail if `pkg1` is not installed. However, we want to do `devtools::document('pkg1')` before installing `pkg1` to update the `NAMESPACE` and documentation. This package implements this logic into the Makefile. See discussion in issue #1148 .
> Bugfixes to make

- modules/assim.batch/DESCRIPTION
- modules/assim.batch/R/pda.bayesian.tools.R
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.get.model.output.R
- modules/assim.batch/R/pda.load.data.R
- modules/assim.batch/R/pda.mcmc.R
- modules/assim.batch/R/pda.mcmc.bs.R
- modules/assim.batch/R/pda.utils.R
- modules/assim.batch/man/load.pda.data.Rd
- modules/assim.batch/man/pda.get.model.output.Rd
- modules/benchmark/R/align.data.R
- modules/benchmark/R/match.timestep.R
Minor bugfixes in the PDA code after recent benchmark changes
Changed` query.format.vars` calls to use `dplyr` connection.
Also addressed some of the changes in align.data and fixed one minor bug.
> Fix query.format.vars calls in PDA

- db/R/query.format.vars.R
One line change in code `query.format.vars.R`
I had an if statement with condition length > 1.
> Fixing error where query.format.vars fails for more than one variable

- modules/assim.batch/DESCRIPTION
- modules/assim.batch/R/pda.emulator.R
- modules/emulator/DESCRIPTION
- Forgot the case for parallelization where detect cores can return 1.
- Also added `GPfit` package to the `Depends`, package was not installed to the VM. Do I need to put the package dependency somewhere else so that it will be installed while VM is created?
- And[ this file ](https://psql-pecan.bu.edu/bety/inputs/1000002080) needs to be in the VM I think, if we want to use it in the PDA @robkooper @mdietze?
> minor fixes after VM tests

- models/fates/inst/template.job
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/inst/FATES_BCI_PDA_demo.Rmd
Save the internal state of pda.emulator periodically, along with a flag indicating how far we got. Doesn't allow an automated restart from web interface, but does allow you to dive into the console and rerun/debug from that specific step.
> pda.emulator: history restart

- modules/assim.batch/R/pda.define.llik.R
- modules/assim.batch/R/pda.emulator.R
- modules/assim.batch/R/pda.utils.R
- modules/assim.batch/man/pda.load.priors.Rd
- modules/assim.batch/man/pda.settings.Rd
Fixed the bug and cleaned the prior handling some more. I tried to test it as much as I can (this can get a little complicated, because if you want to run emulator "longer" you need to load the priors used for the previous PDA whereas if you want to refine the emulator by proposing new "round" of knots you need both the priors used for the previous PDA and the posteriors came out of the previous PDA, and these extensions can come after one another, and be run more than twice etc.)
For now I tested these cases:
- normal run
- normal run followed by a "longer" extension run
- normal run followed by a "longer" extension run twice
- normal run followed by a "round" extension run
- normal run followed by a "round" extension run and then a "longer" extension
I also added back ability to handle …
> Revised PDA prior handling

- web/02-modelsite.php
Site add right click feature
Changed adding a site from a map double click to a map right click so we don't interfere with the double click zoom and center functionality.
Fixes issue detailed in ticket #1221 
- [ x ] Bug fix (non-breaking change which fixes an issue) #1221
> Adding a site now need a right click instead of double click on the map.

- db/R/dbfiles.R
- db/man/dbfile.check.Rd
- db/man/dbfile.input.check.Rd
- modules/data.atmosphere/R/met.process.R
- utils/R/convert.input.R
Machine check needed to be better implemented and added to. It also needed to happen all the time and upon failure grab the last updated record as a tiebreaker if there are multiple valid inputs and only then return empty.
Also if a input record is being updated with new dates. We needed to return the existing input/file record pair after the download.
> Met.bug - Making queries for existing inputs more explicit/exhaustive and cleaning up some logic

- modules/data.atmosphere/R/site.lst.R
When querying  for time zone from a site in BETY it returns a list containing non numeric values (ex. America/Chicago) so when it checked if the query returned an "NA" value it would always return FALSE and force us to rely on geonames to get time zones.
The other dependence on geonames is in met2CF.Ameriflux but it's slightly different. There is not original query to see if a time zone exists for the site in BETY. Need to check that next.
> Change as.numeric to as.character in function to find timezone

- modules/data.atmosphere/R/extract.nc.module.R
- modules/data.atmosphere/R/met2cf.module.R
- modules/data.atmosphere/R/met2model.module.R
- modules/data.atmosphere/R/metgapfill.module.R
The arguments to calls of convert.inputs in the met.process stage modules were not named and so they were read in order so sometimes the exact.dates chunks of convert.inputs  was run. This would sometimes create false positives in runs as it would succeed if there were exact matching dates in BETY and fail when the right input record was found but had different dates.
In some of the modules , the arguments were out of order, so I named them and to be extra sure I named exact.dates as FALSE in all of them except met2model where it is possible for it to be true.
> Name all the arguments in the modules called in met.process

- shiny/global-sensitivity/load_ensemble.R
- shiny/global-sensitivity/plotEnsemble.R
- shiny/global-sensitivity/server.R
Replaced `read.ensemble.output` with manual loop to avoid the 'expressions' pitfall. Might be a good idea to add expression back in eventually for even more powerful plotting, but this is just to get this working for now.
Added a lot of `message` statements throughout to assist in debugging. Anything that gets passed to `stderr` will be printed in the Shiny log, which allows for debugging Shiny runs in the web interface.
> Bugfixes to Shiny global sensitivity

- scripts/dump.bety.sh
- scripts/load.bety.sh
dump missing tables from migrations up to BETY 4.15
> dump new tables PecanProject/bety#403 PecanProject/bety#491

- book_source/deploy.sh
Deprecated the old gitbook repository, and changed "pecan_bookdown" to "pecan-documentation". So I made requisite changes to the name of repository where html files are pushed to in the deploy.sh script.
> Change repository to push html  bookdown files to.

- modules/data.atmosphere/R/metgapfill.R
Bug fix 
ifelse statements do not return more than one element if the conditional is only one element. 
Makes metgapfill crash. Now it works
- [X ] Bug fix (non-breaking change which fixes an issue)
> Replace ifelse with if because of multi-element return value

- models/biocro/R/run.biocro.R
- models/biocro/inst/biocro.Rscript
- models/biocro/inst/pointbiocro.Rscript
- modules/data.atmosphere/R/load.cfmet.R
- tests/pecan64.biocro.xml
* Fixed a bunch of typos and copy/paste errors
* Added missing meta-analysis block to settings file
* Preserve time units when computing whether to downscale
* Added `lubridate::` where missing to make existing `data.atmosphere` tests pass
Goal: make `$(web/workflow.R tests --settings pecan64.biocro.xml)` run without errors, as a first step toward making BioCro work with the PEcAn met conversion workflow (#1266).
> Fix biocro test run

- models/biocro/R/write.configs.BIOCRO.R
First pass at a fix for #1307. Ensures that users can see errors, but does not format them very nicely or check for recoverability. 
For discussion: 
* This patch makes `job.sh` bail immediately on error, without copying `README.txt` back to `outdir`. Is this correct, or should the copy happen unconditionally?
* Note that a nonzero script exit status <del>isn't sufficient to make the PEcAn workflow notice the failure</del> <ins>produces a warning but does not stop execution of the PEcAn workflow</ins>: `PEcAn.utils::start.model.runs` reports success unless `job.sh` output contains the exact phrase "ERROR IN MODEL RUN". Should this be changed?
> BioCro: complain on failure in job.sh

- book_source/_bookdown.yml
- book_source/adv_user_guide_web/PEcAn-Configuration.Rmd
Right now PEcAn XML config page, one of the most important and frequently referenced pages in the docs, is hidden in the Brown Dog section because of heading issues. Attempting to resolve and also fix links to pda and sda doc pages.
> Docs: minor clean up to PEcAn XML config page

- modules/data.atmosphere/R/load.cfmet.R
- modules/data.atmosphere/tests/testthat/test.load.cfmet.R
Fixes #1344: If load.cfmet detects more than 2.5° lat/lon mismatch between site and met file, it now exits with logger.severe (previously logged an error and kept going).
> load.cfmet stop on lat/lon mismatch

- modules/rtm/R/invert.auto.R
Otherwise, chains start with same seed and can end up identical if their initial conditions are the same.
This uses `parallel::setClusterRNGSeed` to set a different seed on each chain.
This hasn't been a problem for PROSPECT inversions because initial conditions are almost always generated randomly.
It has become a problem for EDR because it is often convenient to set static initial conditions.
> PEcAnRTM: Initialisze RNG on parallel cluster

- book_source/deploy.sh
This is a continuation from https://github.com/PecanProject/pecan/pull/1363
In response to #1351 I'm trying to have deploy.sh handle different versions of documentation.
The documentation locations will be:
master = https://pecanproject.github.io/pecan-documentation/master/
develop = https://pecanproject.github.io/pecan-documentation/develop/
release/1.4.10.1 = https://pecanproject.github.io/pecan-documentation/1.4.10.1
etc
Types of changes
Checklist:
> 1351 deploy branches

- modules/data.atmosphere/tests/testthat/test.download.CRUNCEP.R
Skips `test.download.CRUNCEP` when built on Travis, but should still test it when run locally. Note that skip_on_travis() only works without producing a Travis error if it's inside a `test_that`, so I also rearranged all expectations to go inside one test group.
Should help mitigate the recent rash of failed Travis builds -- many of them have been timing out waiting for the CRUNCEP server.
> skip cruncep tests on travis to reduce timeouts

- documentation/README.md
I updated a deprecated link, but perhaps would also be useful to have additional information about how to edit and compile documentation? I would add it but am not sure what to write.
Should we move the book_source folder under the /documentation/ directory?
> update documentation README

- modules/rtm/tests/testthat/test.invert_simple.R
Some of the PEcAnRTM unit tests generate temporary files that are fairly large, and are prone to being accidentally stored in with the package library. This commit adds a `file.remove` call at the end of the offending tests.
> Remove temporary files generated by testthat tests

- modules/benchmark/R/load_data.R
load_data() now will not pass any variables that haven't be converted into pecan names and units, or already match pecan names and units. 
This resolves part of [issue #1415.](https://github.com/PecanProject/pecan/issues/1415)
> load_data() unconvertible units catch

- modules/rtm/R/generate.noise.R
`filter` is a function in `dplyr`, which causes this function to fail.
Adding `stats::filter` protects against the namespace clash.
> Protect generate.noise against namespace clash

- book_source/models/variables.Rmd
Pasted a typo in last PR that should have introduced a failure to render that table. Odd though that the table was still there in documentation when it should have not been rendered at all. Need to check if things are actually being run properly.
> Typo bug I made in last PR

- CHANGELOG.md
- scripts/dump.bety.sh
- scripts/load.bety.sh
need to dump new many-to-many table sites_cultivars
This is a new table that has not been added to the dump/load scripts so it is missing
> add sites_cultivars to dump / load bety scripts

- modules/data.atmosphere/R/met.process.R
Met.process needs to specific met source when met already converted. But logger.error statement was stopping execution.
> Replace logger.error with logger.warn on met source missing fix

- book_source/deploy.sh
Need to keep track of who made/owns the Github authentication token used as environment variable `GITHUB_PAT` in TRAVIS to build and push documentation. 
Added a line to print a comment about who owns it.
> Print who made GITHUB_PAT variable 

- modules/data.atmosphere/inst/registration/register.CFmet.xml
Forgot to add the needed XML file to the last fix #1438 . Sorry.
register.CFmet.xml needs to exist in inst for met.process to actually accept CFmet as valid.
> Registration file needed to match met.process CFmet generic

- Makefile
- modules/assim.batch/DESCRIPTION
- modules/benchmark/DESCRIPTION
- modules/data.atmosphere/DESCRIPTION
- modules/data.land/DESCRIPTION
- visualization/DESCRIPTION
`make` was not creating the files used to check if devtools, roxygen,
and testthat had been performed. This was causing `make` to run in full
_every_ time for pecan intsalls that didn't already have the
.install/devtools, etc. files existing, which of course defeats that
point.
> Bugfix in Makefile

- db/R/query.format.vars.R
- modules/data.atmosphere/R/download.Fluxnet2015.R
- modules/data.atmosphere/R/met2CF.csv.R
- modules/data.atmosphere/man/met2CF.csv.Rd
Changes to met2CF.csv.R and related functions to work with time formatting convention used in storage_type instead of variable units. 
Function now uses same method as load.data.R in benchmark for time converseion. query.format.vars also return site time zone to use as default time zone for CSV files.
Deals with #1459  
- [X ] Bug fix (non-breaking change which fixes an issue)
> Update met2CF.csv to be consistent with load.data

- shiny/workflowPlot/helper.R
- shiny/workflowPlot/server.R
- shiny/workflowPlot/ui.R
1. pecan/shiny/workflowPlot/server.R
Switch to allow both type of plots.
Commenting helper.R
observeEvent while loading variable names
2. pecan/shiny/workflowPlot/helper.R
Commenting helper.R
3. pecan/shiny/workflowPlot/ui.R
Commenting helper.R
Allow radio buttons for selecting the choice. Default scatter plot
Feature required to show line charts as well scatter plots.
> Allow toggle (line and scatter plots) for visualization

- utils/R/convert.input.R
Within convert.inputs, if a conversion of data (i.e. download of raw met data) failed there was not a check for whether or not the `result` object was actually valid and it would continue on to update input records. Lines 411-415 should fix that.
I also added more explicit logger info at lines 51 and 146 to help debugging.
This closes #1500
> Stop convert.inputs after failed data conversion 

- models/sipnet/R/write.configs.SIPNET.R
Sipnet's initial condition for plantWood includes both above ground woody C and roots, but our IC workflow/standard variables are equipped to pass in AbvGrndWood. This change estimates total wood by incorporating the fineRootFrac and coarseRootFrac parameters. Also added a check on the IC netcdf file opening.
> Update plantWood IC in write.configs.SIPNET

- modules/data.atmosphere/R/download.Geostreams.R
- web/03-inputs.php
Was saving Geostreams downloads as "Clowder.<dates>.json", but workflow expects the met name to match what's declared in register.<metname>.xml. This resulted in a confusing web workflow error (`XML content does not seem to be XML: ''`), which turns out to really mean "I'm looking for a `register.Clowder.xml` and not finding one."
Fixed by always naming the files "Geostreams".
> Always name files as "Geostreams" not "Clowder"

- db/R/dbfiles.R
- modules/data.atmosphere/R/download.raw.met.module.R
- utils/R/convert.input.R
Within the checks for met, GFDL was being confused for CRUNCEP because they have the same formats. To alleviate this a special check was added to look for the string "GFDL" in the valid inputs that are found and return only rows with "GFDL" in them.
> Fix to differentiate GFDL 

- db/R/dbfiles.R
- modules/data.atmosphere/R/download.raw.met.module.R
- utils/R/convert.input.R
- utils/man/convert.input.Rd
Without setting the met as Null, it was messing up run that did not require that argument so it needed a default setting.
> Default for met source setting in convert.inputs

- Makefile
Prevent build errors by ensuring that all PEcAn packages are installed before `devtools::install_deps` is invoked
Make was failing after clean R installations, but succeeding when older versions of all dependency packages were available. There appear to be two simultaneous issues here: 
* the Makefile's dependency lists for Biocro and uncertainty were out of date*
* `devtools::install_deps` tries to resolve dependencies by installing them from one specified repository, so it doesn't know what to do with a package that Depends on, say, both `PEcAn.db` (local) and `ncdf4` (CRAN).
Switching the `all` recipe from `document install` to `install document` seems to make everything happen in the correct order on my system, but please check my assumptions.
*P.S. While I'm looking at Make …
> install PEcAn packages before resolving dependencies

- models/dalec/R/model2netcdf.DALEC.R
When I updated model2netcdf.DALEC to use the new standard variables and a new to_ncvar function, I put the dimensions in the wrong order, causing an error in nc_create. Now the model output should successfully write to netcdf.
> fix order of dims to prevent nc_create error

- utils/R/convert.input.R
This was causing #1522. Based on preliminary tests, this is no longer hitting that particular bug. Can't speak to other bugs yet.
> Bugfix: Passing host list, when should be hostname

- modules/meta.analysis/R/jagify.R
The jagify function in meta-analysis had an error message for unreasonable standard errors which had an uninitialized variable (probably from an old copy and paste from a for loop) which prevented the error message from showing. Replaced the broken part.
> Fix broken error message in jagify

- modules/meta.analysis/R/jagify.R
Add jagify check to change stat=0 to stat=NA. Uncertainty stats can't be 0. Before, the illogical case of stat being nonNA (set as 0 in some raw field data) when n = 1 led to n being set to 2. See pr #1574 for discussion.
> Add jagify stat=0 check 

- CHANGELOG.md
- web/dataset.php
Fix remote code execution in dataset.php, this is only executable by providing a malicious url, and not from the web interface.
> fix for #1545

- utils/R/read.output.R
Currently read.output has start.year and end.year arguments that default to NA. However, this results in no output and several warning messages. @ashiklom suggested it would make more sense to have the function return all years if no limits are passed in. Added a simple check for NA start or end years. Could be more complex, e.g. accepting a start or end year without the other, but this will at least allow the no years provided case to work.
> Improve read.output

- CHANGELOG.md
Retroactive notes in CHANGELOG.md for my past pull requests. I'm assuming it's still useful to add notes to the past release as well as the current pre-release?
> update CHANGELOG for past PRs

- CHANGELOG.md
- Makefile
Installation of each package depends on its documentation being compiled. This means that it's now much harder to install a package with outdated documentation, _and_ that complete package installation now proceeds one package at a time (i.e. `document package1, install package1, document package2, install package2`) rather than doing all the `document` and `install` steps at once, as before (i.e. `document package1, document package2, install package1, install package2`). This should make installation on new machines much more robust.
This PR addresses #1558.
> Improve makefile logic

- Makefile
- modules/rtm/R/bayestools.R
- modules/rtm/man/invert_bt.Rd
- modules/rtm/man/rtm_loglike.Rd
- modules/rtm/tests/testthat/test.invert_bayestools.R
- Fix wrong default `lag.max` in `rtm_loglike`
- Add more informative messages to `rtm_loglike`
- Change default `min_samp` to 5000, becuase the results are a lot more robust and don't take that long. It can always be lowered by the user if desired.
> RTM: Minor bugfixes to `invert_bt`

- CHANGELOG.md
- modules/data.remote/R/call_MODIS.R
- modules/data.remote/inst/modisWSDL.py
- modules/data.remote/man/call_MODIS.Rd
The call_MODIS function in the remote module, which extracts MODIS data for a given location and date range, previously relied on an R package, MODISTools, which was pulled from CRAN (issue #1606 ). There was also an option in the function to call a python script, which was out of date. This PR reverts the function to an updated python script which accesses the MODIS web service API described [here](https://modis.ornl.gov/data/modis_webservice.html). 
The bugs fixed include:
- numpy.zeros being called with the number of rows and columns of the output data as floats; needs ints.
- A netcdf variable created with "i7" instead of "i8" (64-bit integer)
- Out of date netcdf format; updated to NETCDF4
- Typo causing an input variable not to be assigned in QA downloads
Most of the commits are …
> Debug modis download

- modules/rtm/R/bayestools.R
- modules/rtm/man/invert_bt.Rd
- modules/rtm/man/rtm_loglike.Rd
- modules/rtm/tests/testthat/test.invert_bayestools.R
Was using true sample size (`n_obs`), when I should have been using the effective sample size (`n_eff`), in likelihood calculation.
Also:
- Allow option to disable diagnostic messages
- Add predictive interval plot when doing interactive tests of invert_bt.
> RTM: Fix likelihood calculation in `invert_bt`

- models/biocro/R/met2model.BIOCRO.R
This is a continuation of #1620 -- @dlebauer made some good suggestions in review that seemed worth following up on even though that PR has been merged.
Also of note: Removed an unnecessary conversion from ratio to percentage and back to ratio when computing relative humidity inside `met2model.BIOCRO`.
In [https://github.com/PecanProject/pecan/pull/1620#pullrequestreview-60151116](https://github.com/PecanProject/pecan/pull/1620#pullrequestreview-60151116), @dlebauer said:
> FWIW I think 'data.table' way was faster, as would the dplyr mutate function, though this is definitely more standard and readable. 
I got interested in this speed comparison and [may have gone a *tad* overboard](https://gist.github.com/infotroph/fd76379d8a0e2aa3d7a8ed4ac76dbd2c). Bottom line: data.table is indeed a …
> Further Biocro data.table style cleanup

- modules/data.atmosphere/R/download.Geostreams.R
- modules/data.atmosphere/man/download.Geostreams.Rd
> Document how to authenticate to Geostreams

- CHANGELOG.md
- documentation/index_vm.html
- web/05-running.php
Now uses GET to switch to 08-finish.php which will put the workflowid in the url.
> Put workflowid in url

- base/remote/DESCRIPTION
- base/remote/R/is.localhost.R
- base/remote/R/remote.execute.R.R
- base/remote/R/remote.execute.cmd.R
There was a circular dependecy where PEcAn.remote depended on PEcAn.utils and vice versa. If you did a make clean followed by make it would fail in building PEcAn.remote since it did not exist yet.
> fix circular dependency

- models/sipnet/R/write.configs.SIPNET.R
- modules/data.land/R/prepare_pools.R
prepare_pools was assigning a variable without prefixing the right list stuff. write.configs.SIPNET had a udunits2 namespace with only one colon.
> Fix typos in prepare_pools and write.configs.SIPNET

- Makefile
- models/sipnet/R/read_restart.SIPNET.R
- models/sipnet/man/read_restart.SIPNET.Rd
Re-adds the PEcAn package template to the Makefile, but in a slightly cleaner fashion.
Additionally: 
* cleaner Make syntax for PEcAn.logger dependancy
* fix typo that was preventing `read_restart.SIPNET` docs from compiling
In #1634 I removed the template package `PEcAn.ModelName` from the build, thinking that no other part of PEcAn used it. I was wrong: `read_restart.ED2`, `write_restart.ED2`, and  `read_restart.SIPNET` (but not `write_restart.SIPNET`!) take their parameter documentation from there using the Roxygen `@InheritParams` tag.
> Install template package after all

- models/maespa/R/met2model.MAESPA.R
Missed calling `sw2par` as `PEcAn.data.atmosphere::sw2par`
> Maespa missed external function call

- models/sipnet/R/met2model.SIPNET.R
SoilT variable was converted from Kelvin to Celsius by hand (-273.15) then subsequently converted into Celsius again using ud.convert, making soilT values unreasonable.
> Fix soilt calculation in met2model.Sipnet

- base/db/inst/bety_mstmip_lookup.csv
- modules/data.atmosphere/R/met2CF.csv.R
Fixes warnings in query.format.vars on unit conversion and handles met conversions when units are kg m-2 (30 minute)-1 or kg m-2 hr-1, when file can be hourly -or- half-hourly.
Closes #1702 
> Remove warnings on met conversions

- base/logger/R/logger.R
- base/logger/tests/testthat/test.logger.R
Log messages were always reporting "INFO [PEcAn.logger::logger.info]" where they were supposed to report the function that the logger was called from, e.g. "INFO [do_conversions]". 
Fixed by allowing for an optional "PEcAn.logger::" when matching strings to remove logger calls from the frame dump.
> logger: allow for namespaces when filtering calls

- .zenodo.json
Zenodo automagically publishes our latest release with a doi and makes it easy to cite.
If folks use their real name and affiliation on GitHub, it will be carried through to Zenodo. That would be ideal. But at present we still have a number of folk who don't use their real names on GitHub (and many valid reasons exist for doing so). However in the context of academic credit for software as a scientific product, I think this can be a useful tool.
Notably, it also appears to only include contributors with >= 4 commits by default; we could change that here. 
Format follows the Zenodo rest API documented here http://developers.zenodo.org/#depositions
creators:  The creators/authors of the deposition. Each array element is an object with the attributes:
attributes: 
* name: Name of creator in …
> Add contributor names / affiliations via .zenodo.json 

- models/ed/R/write.configs.ed.R
Missing the t in met for settings$run$inputs$met$path
> Fixing typo in write.configs.ed

- models/sipnet/R/met2model.SIPNET.R
Fixes subsetting bug in met2model.sipnet closes #1769 . Tested in web workflow, seems to work. For those who have tested previously, be sure to delete your "bad" sipnet .clim files both physically on disk and also in dbfiles table.
> Fix for improper subsetting of end date in met2model for sipnet

- modules/data.land/R/soil2netcdf.R
- modules/data.land/R/soil_utils.R
soil2netcdf relies on soil_params (in soil_utils) to estimate parameters. This fix allows 1) passing soil type instead of texture to soil2netcdf to be consistent with recent change @mdietze made to soil_params, 2) passing empty texture variables to soil_params results in them being NULL not missing, and this needs to be tested in estimating texture, and 3) some soil types (like "peat") output NULL or NA values for some variables and soil2netcdf was incorrectly writing those out to the NetCDF file. These changes fixes those, so we can make wetlands great again.
- [X ] Bug fix (non-breaking change which fixes an issue)
> Small fixes for missing values in soil2netcdf and soil_params (soil_utils) in data.land

- modules/rtm/R/edr.wrapper.R
This automatically renames the wood and soil reflectance files so they
match the name expected by EDR.
> RTM: Rename wood and soil reflectance files

- models/dalec/R/write.configs.dalec.R
There's one line in write.configs.dalec where a udunits conversion has two small errors: missing a -1 and the order is switched; it should be convering to PECAN standard rather than from it because the variable is an input for prepare.pools.
> write.configs.dalec udunits fix

- modules/data.atmosphere/R/metgapfill.R
metgapfill now adds more cheks for RH < 0 or > 100, Shum < 0 or VPD < 0 or VPD > saturation vapor pressure.
> More consistency for water vapor variables in metgapfill

- base/db/R/query.dplyr.R
- base/db/man/get_users.Rd
- base/db/man/get_workflow_ids.Rd
- shiny/workflowPlot/server.R
Externalize Shiny calls in `get_workflow_ids`. Remove unused `session` argument from `get_users`.
Ain't nobody got time to load all those Shiny dependencies.
> Remove Shiny dependencies from PEcAn.DB

- base/db/R/query.dplyr.R
- base/db/man/get_users.Rd
- book_source/developers_guide/Testing.Rmd
- shiny/workflowPlot/server.R
Several potential issues:
- `PEcAn.DB::load_data_single_run`:
- Currently can't handle matrix output (e.g. multiple layers of soil for moisture and temperature). This has a hack to only grab the top layer.
- If variable is not found, returns a 0-length data frame, which then crashes on the `cbind`. This skips the variable with a warning if it has 0-length output.
- `shiny::server.R`
- Shiny crashes if no inputs are available for a given site and format. This hotfix returns `NULL` if no inputs are found, which allows Shiny to draw the output, even if it can't find data to plot with.
> Temporary hotfix for Shiny

- models/ed/DESCRIPTION
See issue #1806. Temporarily switching to a specific GitHub user's `rhdf5` forks. `Rhdf5lib` dependency added to `Imports` because it's required by `rhdf5`.
> Temporary patch to fix `rhdf5` installation

- .travis.yml
Set the error option (`set -e`) for the documentation-building part of Travis, so that if `make` throws an error, the build will fail.
> Make documentation builds fail Travis

- book_source/deploy.sh
- documentation/tutorials/deploy.sh
Skips documentation deployment for builds in forks where the user hasn't set up a `pecan-documentation` repository.
The current build script attempts to deploy to `${USER}/pecan-documentation.git` on every push to a branch named "master", "release*" or "develop", even in forks owned by users who don't have such a repo. Before #1833, this was masked by *all* documentation failures going unreported, which is obviously even less desirable.
This patch queries for the existence of a documentation repository and only attempts the deployment if one is found. Then for anyone who *does* want a local documentation repo, the procedure should be as simple as "Fork `PecAnProject/pecan-documentation` to the same account as your PEcAn fork, and the next CI build will start it updating."
> skip documentation build if user has not forked repo

- .travis.yml
This will remove all the setvalue from psql loading of the database.
`psql -q` will make postgresql quiet, but all output from any select type statements is still printed. When doing a setval this is considered output that should be printed. Using the `-o` flag the output is now redirected to /dev/null. Errors will still be printed to the console.
> silence psql

- modules/rtm/R/bayestools.R
These values no longer exist. Asking for them in an error message would
cause an error.
> RTM: Remove references to `n_eff` and `sigma2eff`

- .travis.yml
Adds an encrypted token for Travis<>Slack integration. 
I've already set up the Slack end -- notifications currently go to the `#travis` channel, but this can be changed at will and (I think) without needing to update this token.
> send CI status notifications to Slack

- modules/data.land/R/load_veg.R
`load_veg` has a query to find an input veg file, but there is the possibility that the file can be on multiple machines. Added to the query to make sure it finds the file on the  for that within the function as it has the necessary params to make that query.
Tagging @istfer for review because you wrote this function and you happen to be my code reviewer this week.
> Add machine check to query in load_veg

- base/utils/R/seconds_in_year.R
- base/utils/man/seconds_in_year.Rd
`PEcAn.utils::seconds_in_year` also needs to be aware of the `leap_year` argument. This adds the `leap_year` argument in.
Without it, running `met2model.*` would throw an error, because `leap_year` is expected by `days_in_year`, but is not properly passed through when called by `seconds_in_year`.
> utils: Residual leap year-related bug

- models/ed/R/model2netcdf.ED2.R
- models/ed/inst/ED2IN.rgit_istfer
I forgot to return the modified out-lists that have the unit conversions. Currently ED runs don't break but the outputs are not in pecan units. This PR fixes it.
> model2netcdf.ED fix

- models/ed/R/modify_ed2in.R
- models/ed/R/write.configs.ed.R
- models/ed/man/modify_ed2in.Rd
check_paths in modify_ed2in is breaking remote runs, defaulting it to false
> change check_paths default to false

- CHANGELOG.md
- web/setups/core.php
NCSA security discovered a XSS issue, this is fixed in this pull request.
php code in setup folder can be run without being logged in. Now requires user to be logged in. This does not completely address issue yet, however it makes it harder to abuse the setup system. Will need a more thorough review of the code.
> need login before calling anything in setup folder

- base/utils/DESCRIPTION
This is a minor fixup for #1893 -- I added tests that use testthat::teardown (new in testthat 2.0.0) but neglected to update the version spec.
> testthat::teardown requires testthat 2.0.0

- CHANGELOG.md
- web/curl.php
- web/history.php
This will allow you to see the curl command needed to re-execute an existing workflow.
This will look at the parameters stored when the workflow was last executed through the web interface and create the curl command to re-execute the same workflow. Only caveat is that all spaces had been removed from the parameters, this is visible in site-names, however this should not impact the actual run.
For testing I needed to quickly be able to re-execute a workflow.
> show curl command to re-execute workflow

- modules/data.atmosphere/R/download.GFDL.R
I take the input arg `outfolder` and add on the newly named outfolder:
This:
`GFDL_site_0-772/`
Becomes:
`GFDL_site_0-772/GFDL_CM3_rcp45_r1i1p1_site_0-772`
This closes #1911.
I need to finish testing this, but works on one run I've done.
> Fix for Issue #1911

- CHANGELOG.md
- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/download.GFDL.R
- modules/data.atmosphere/man/download.GFDL.Rd
- modules/data.atmosphere/tests/testthat/helper.R
- modules/data.atmosphere/tests/testthat/test-download.GFDLR.R
- modules/data.atmosphere/tests/testthat/test.download.CRUNCEP.R
* Record time units as seconds since current_year-01-01, not "secs" (#1347). (cc @dlebauer this fixes GFDL->BioCro conversion errors)
* Adds basic tests for GFDL download, skipped on Travis for speed
* Download only the observations from the year of current interest (was downloading whole 5-year block and then subsetting)
Please review commits 13e8956 and d544380 extra-critically -- My changes pass all of my tests, but I feel like that `if(year %%5...` chain is a great example of "don't let me delete it until I understand why it was there in the first place"
> download.GFDL: CF-compliant time units, download only requested dates

- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/met_temporal_downscale.Gaussian_ensemble.R
Removes a single call to `aspace::cos_d` by calculating degrees-to-radians for ourselves.
aspace depends on Hmisc, which we don't use anywhere else in data.atmosphere and which depends on approximately everything. Removing it should shorten the dependency chain considerably.
> remove aspace package dependency

- CHANGELOG.md
- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/met2CF.Ameriflux.R
- modules/data.atmosphere/R/site.lst.R
* Installs dependency package `geonames` from Github
* Uses `::` instead of `library`
* Does not overwrite `options(geonamesUsername)` in the (unlikely?) case it's already set
By default, the current CRAN version of geonames queries `ws.geonames.org`, which is now defunct. This *could* be fixed by setting options(geonamesHostname = "api.geonames.org"), but the github version of geonames has done this for us and has the nice additional benefit of better `.onLoad` behavior, so we can now use GNtimezone without attaching whole package.
When https://github.com/ropensci/geonames/issues/17 is closed, we can bump the geonames version spec and switch back to installing the CRAN version.
> use newer geonames

- base/visualization/DESCRIPTION
- modules/benchmark/R/load_netcdf.R
- shiny/ViewMet/server.R
- shiny/ViewMet/ui.R
I made a quick shiny app for finding and visualizing all met data that is in CF format.  The app has two main features:
Finding files:
- The app searches for all inputs in BETY that are in CF format and pulls their site id's. 
- A menu with a list of sites is shown. 
- After selecting a site, the app then searches to see if there any met files for the site on your local server.
- Checkboxes with the met types and which dates available is shown. 
- After clicking on a met type and year, a table with the corresponding file paths will render in the "Files to be loaded" tab. 
Plotting met:
- After selecting met type(s) and year(s) and clicking on the "Load Met Data" button the app runs `load_data` and attempts to read all files in. 
- Once the files are loaded, a menu with available variables …
> Shiny app for viewing CF met

- modules/data.atmosphere/R/debias_met_regression.R
Min to max may seem more logical but for datasets where a year is
missing for whatever reason, this will cause the precipitation
redistribution to fail.  Using unique() might be a hair slower, but has
no noticeable impacts on performance.
Change from indexing from the minimum year to the max year in the training dataset to using unique years.
If using non-consecutive years in the training dataset, an error will occur when trying to determine the precipitation distribution.
> Met debias: fix year indexing to accommodate missing years

- modules/data.atmosphere/R/debias_met_regression.R
Bound the number of rainless days to at least 1 and no more than 364.
At sites with a high standard deviation, you can get random values for
n.now that cause the quantile to be negative or greater than 1 (which
is impossible.)
In sites or datasets with high inter annual variability in the number of rainless days and when processing thousands of years (via ensemble generation), an impossible number of rainless days can be generated.  This causes the quantile function too ind the precip cutoff to fail because it's trying to find a number outside of the 0-1 bound.  
I've added a bound where the minimum number of days is as much as 1 sd less than the minimum observed in the training dataset, allowing for the dataset to drift into novel conditions.  If that produces a negative number, then try …
> Bug Fix, Debias routine: Bound rainless day distribution

- CHANGELOG.md
- modules/data.atmosphere/R/met2CF.csv.R
Minor update to modules/data.atmosphere/R/met2CF.csv.R to include recursive=TRUE for outfolder.  Seemed to work better
@ankurdesai are you OK with this?  very minor but seemed to work better on my cluster...perhaps a problem for other machines?
> Minor update to modules/data.atmosphere/R/met2CF.csv.R

- base/utils/R/convert.input.R
Was getting an error:
```
Error in basename(in.prefix) : a character vector argument expected
```
And found that in convert.inputs, when trying to insert the result into the database, it wasn't handling the result object correctly to define `in.prefix`. The id `existing.input` arg wasn't being defined properly as well
This comes from testing the VM
> Fix the defining of args for db.file.insert in convert.inputs

- CHANGELOG.md
- base/settings/DESCRIPTION
- base/settings/tests/testthat/helper-get.test.settings.R
- base/settings/tests/testthat/test.deprecated.settings.R
- base/settings/tests/testthat/test.read.settings.R
Settings package tests were writing to the test directory and not cleaning up properly, which was (1) annoying, and (2) caused Make to always see the modules/settings folder as having been updated, so the settings tests would rerun every time `make test` was called. 
Fixed by setting up a tempdir, consistently passing that as the outdir for all settings, and making sure to unlink the directory at the end of the test.
Tagging @robkooper because you're paired with me for review this week and probably know the settings code best as well.
> use tempdir for settings tests, clean up afterward

- base/utils/R/convert.input.R
The object `existing.input` is turned into list and so one instance of it being called did not take into account that structure. 
Made for a weird bug that was hard to track down because it would make met not work  and then work at different stages because the correct records were actually being created but the result object sometimes did not contain an input.id to pass on. I'd run it again and it would work, but since the conversion actually worked and the records in BETY were there it would pass through the step. Took a bit to test and make sure this worked  because I had to keep cleaning the DB before testing. It's a small thing but it messed up every step when there was an existing input on other machine and a new file needed to be inserted after the initial stage of met.process. …
> Missing index in convert.inputs

- CHANGELOG.md
- modules/data.atmosphere/R/download.CRUNCEP_Global.R
- modules/data.atmosphere/R/download.raw.met.module.R
- modules/data.atmosphere/man/download.CRUNCEP.Rd
New argument `method` defaults to "opendap" (current). However, specifying `method = "ncss"` (a.k.a. `<method>ncss</method>` in XML) uses the slower but much more reliable NetCDF subset method, which involves subsetting the file on the server first, then downloading the subsetted file (to `tempfile()`), and then reading it locally.
OpenDAP is a notoriously unreliable download method. In my experience, NetCDF subset, although somewhat slower and not quite as elegant (because files have to be downloaded locally), fails _much_ more rarely. In my tests, it has never once failed, whereas OpenDAP fails at least 50% of the time.
> Add download method argument to `download.CRUNCEP`

- CHANGELOG.md
- book_source/06_reference/09_rabbitmq.Rmd
- docker/receiver.py
- web/04-runpecan.php
- web/07-continue.php
- web/common.php
Also, refactor RabbitMQ functionality in web interface into its own functions.
Also, allow `docker/receiver.py` to receive custom applications via `custom_application` message.
This PR fixes #2151.
> DOCKER: Make web post RabbitMQ messages even after edit

- CHANGELOG.md
- modules/data.atmosphere/R/download.CRUNCEP_Global.R
Downloads the CRUNCEP 0.5 degree land-water mask (small file, ~250 KB) and checks if the specified site coordinate falls on land. If yes, proceed as usual. If not, look for land 1 degree in every direction, and if any pixels are land, use data for those coordinates instead. If no land within 1 degree of coordinates, throw an informative error.
Addresses issue #1265 for CRUNCEP specifically. The same issue may appear for other met products, in which case this should be generalized, but this fix should work for now.
> Check against CRUNCEP land-sea mask during `download.CRUNCEP`

- scripts/check_with_errors.R
Fixes #2173
`devtools::check` now defaults to exiting with an error on any warning or error from `R CMD check`, so we need to specify `error="never"` so that the check_with_errors script can finish (<del>Otherwise it </del><ins>Also, an [unrelated issue](https://github.com/r-lib/devtools/issues/1914)</ins> will falsely report success with 0 warnings and 0 notes).
Note that this means `check_with_errors.R` is now redundant for its *original* purpose (which was basically to provide the behavior we could now get from `devtools::check(..., error_on="error")`), but I propose we keep it around and use it to start *promoting* specific warnings to errors as a path toward finishing #1949.
> update check_with_errors for new devtools

- book_source/06_reference/04_docker/05_building_images.Rmd
- docker/receiver.py
- scripts/docker_rebuild.sh
Enable (and describe) a development workflow where the user mounts her local PEcAn source code as a volume onto the `executor` container, and then triggers workflow rebuilds using a special `rebuild` RabbitMQ message. This leverages the `docker-compose.override.yml` functionality, described [here](https://docs.docker.com/compose/extends/), to avoid having to edit any version-controlled files.
This should make it easier to develop and test with Docker.
> DOCKER: New development workflow using RabbitMQ

- CHANGELOG.md
- book_source/06_reference/02_models/ed.Rmd
- models/ed/R/write.configs.ed.R
- models/ed/inst/template.job
- models/ed/man/write.config.jobsh.ED2.Rd
Add ability to pass ED2 executable arguments via PEcAn settings list (`pecan.xml`). This is primarily useful by adding ability to pass `-s` flag, which delays MPI initialization, and prevents Dockerized ED2 runs from crashing immediately after startup.
NOTE: All of the Docker/RabbitMQ-related changes are from #2182. This PR is a superset of those changes.
Closes #2146.
> ED2: Pass arbitrary binary arguments

- contrib/modellauncher/Makefile
- contrib/modellauncher/modellauncher.c
Moved modellauncher from base/utils to contrib
During the migration from /utils to /base/utils (v1.5.0 to v.1.5.1) modellauncher.c was removed.
> Modellauncher was removed when migrating from utils to base/utils

- docker/base/Dockerfile.monitor
`Dockerfile.monitor` doesn't read the `EXPOSE` argument (for the port) correctly because of a backslash on the preceding line (interpreted as a command continuation).
`docker build monitor` doesn't work.
> DOCKER: Fix trailing backslash in Dockerfile.monitor

- .travis.yml
- CHANGELOG.md
- Makefile
- modules/data.mining/DESCRIPTION
Removes data.mining from the Make build, and therefore also from testing on Travis, to save build time and signal its not-yet-maintained status.
Proximal issue: installing the `magick` R package and its required ImageMagick libraries is eating a *lot* of build time, contributing significantly to our Travis timeout problem.
Medial issue: ImageMagick is needed because `data.mining` imports `dplR`, which imports `animation`, which imports `magick`. Only one dplR functions actually uses animation, and `data.mining` doesn't call it. I emailed the maintainer of dplR to suggest they move `animation` to their Suggests so that we can skip installing it, and they agreed that this is a good idea but they don't yet have a timeline for their next CRAN release.
Ultimate issue: `data.mining` isn't yet …
> Exclude PEcAn.data.mining from build

- .travis.yml
- CHANGELOG.md
- Makefile
- scripts/check_with_errors.R
* Run Travis tests against three versions of R in parallel
* Fold up successful log sections so it's easier to find what failed
* Report time used by each make step (deps/install/document/check) within every package. Especially useful for debugging timed-out builds
* `make check` now skips rebuilding documentation if env var `$REBUILD_DOCS` is false  
* General cleanup: Remove unused packages, delete some build hacks that have outlived their purpose, etc.
The major change here is a transition from testing against one R version (hopefully the one most users have) to defining a *build matrix* so that we can test in multiple environments at once. The build matrix concept could be extended in the future to include different OSes, Postgres versions, environment variables, etc, but for this PR …
> Travis: Build against multiple R versions

- scripts/backup.bety.sh
- Added check for HOURLY environment variable to enable an hourly-labeled database dump
- If making an hourly dump, set the filename with 'h' and the hour (in 24 hour time format). For example, `bety-h-14.sql.gz`
- If **not** making an hourly dump, assume making a daily dump
- If making an hourly dump, copy hourly dump to daily dump at hour 00
- Changed other dump commands to copy the original dump (hour or daily) to correct name
- Added `-p` command line option for additional psql command line parameters
- Added `-h` command line option to display help
- Added '-o' command line option to specify output location override
- Can now make an hourly dump of the database
- Can run in non-standard environments, such as a machine hosting Pecan in docker containers
- Using **cp** saves time
- …
> Added features requested in #2291

- CHANGELOG.md
- base/db/R/utils_db.R
- base/db/man/db.query.Rd
(NOTE: This PR is a superset of #2316. Merge/review that one first).
Support prepared statements in `db.query` (if using the `RPostgres` backend).
Prepared statements provide a way to efficiently pass data into SQL queries without the risk of SQL injection attacks. Instead of doing this:
```
db.query(paste0(
"SELECT * FROM table WHERE mycol = ", somevalue,
" AND othercol = ", othervalue
), con = con)
```
...we can now do this:
```
db.query(
"SELECT * FROM table WHERE mycol = $1 AND othercol = $2",
values = list(somevalue, othervalue),
con = con
)
```
Besides preventing SQL injections, prepared statements also ensure that the input and target types are compatible.
Prepared statements provide an efficient way to operate on multiple values at once. For example, the following will return all …
> Support prepared statements in `PEcAn.DB::db.query`

- base/settings/R/site_pft_link_settings.R
The conversion about this function started here :https://github.com/PecanProject/pecan/pull/2309#discussion_r263871328, which resulted a bunch of bugs. Here is a small fix for the cases that the `prepare.settings`  crashed. The error comes from the point where `purrr::discard` changes the length of `pft.l` but in the last line this was not taken that into account.
> Small fix for prepare setting function

- docker-compose.yml
- docker.sh
- docker/rstudio-nginx/Dockerfile
- docker/rstudio-nginx/nginx.conf
put rstudio behind nginx to make /rstudio work. See https://docs.rstudio.com/ide/server-pro/access-and-security.html#running-with-a-proxy
> rstudio behind nginx-proxy

- base/utils/R/read_web_config.R
- base/utils/man/read_web_config.Rd
- base/utils/tests/testthat/test.read_web_config.R
Make `PEcAn.utils::read_web_config` more robust and safe by using regular expressions and setting names directly, rather than using the highly unsafe and unreliable `eval(parse(...))` structure. Also, give it a unit test.
Previous code was failing to parse the default Docker config file. More generally, since we use this function in our Shiny apps, @tonygardella's batch test script, and possibly other places, I figured it was worth cleaning up.
> UTILS: Refactor `read_web_config` and add unit test

- CHANGELOG.md
- models/ed/R/met2model.ED2.R
Unless `overwrite = TRUE`, don't extract met for years for which every required target file is present. This should make `met2model.ED2` run much faster when extending an existing met record.
Tagging @istfer, @mdietze, @serbinsh, and @femeunier as major ED users.
When updating existing ED met, `met2model` would extract variables, etc. for all years, including those for which files are already present. This can add up to a lot of wasted time.
> ED: Make met2model entirely skip complete years

- .travis.yml
* Specify Ubuntu 16 (Xenial) for Travis build container (was 14 AKA Trusty)
* Install openGL headers (previously provided by default), 
* Drop hdf5-backports PPA (was only needed because Trusty)
After long delay, Travis CI now supports using Ubuntu 16 instead of the now-EOL Ubuntu 14. This is a good thing and we should take advantage of it, to keep our testing platform at least vaguely in the same generation as the OSes on which PEcAn is actually used.
> Use Xenial for Travis build

- models/ed/R/write.configs.ed.R
Allows `<ed2in_tags>` that are negative vectors to work. This is particularly relevant to soil depth (`SLZ`). For example:
```xml
<model>
<ed2in_tags>
<SLZ>-3.0, -2.7, -2, -1.5, -1, -0.5, -0.2, -0.1, -0.05</SLZ>
</ed2in_tags>
</model>
```
Tagging @istfer and @serbinsh because you both work with ED.
> ED2: Allow negative numbers in custom ED2IN tag vectors

- base/db/R/get.trait.data.R
- base/db/R/query.prior.R
- base/remote/R/stamp.R
- modules/uncertainty/R/ensemble.R
Fixes a bug reported by @istfer. Without `scientific = FALSE`, `format(<long integer>)` uses scientific notation, which fails in the SQL query.
> DB: Correctly format PFT ID in query.priors

- scripts/travis/install.sh
- scripts/travis/rebuild_pkg_binaries.R
Avoids Travis failures on R-oldrel by checking the build information on all binary-installed R packages before attempting to load them, and rebuilding from source any that were built for a later R version than is currently running.
All our Travis builds on R-oldrel (currently R 3.5) are failing with this cryptic error: 
```
Error in rbind(info, getNamespaceInfo(env, "S3methods")) : 
number of columns of matrices must match (see arg 2)
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
```
The exact cause is kind of tedious...
<details>
The process of loading an installed R package involves reading namespace its namespace info and adding all declared S3 methods to an internal table... and that table is apparently a 3-column matrix in R 3.5 and a four-column matrix in R …
> Travis: Rebuild packages as needed on R 3.5

- base/db/R/get.trait.data.R
When pulling trait data from the database, we ran into the following error: 
```[PEcAn.DB::get.trait.data] : 
`trait.names` is NULL, so retrieving all traits that have at least one 
prior for these PFTs. 
Error in .subset2(x, i) : subscript out of bounds
```
This occurred because we were using a new PFT that had no data associated with it, so the meta-analysis didn't produce any posteriors. 
Changed `get.trait.data.pft` so that, if the posterior table has no rows, it returns a message ("No previous posterior found. Forcing update") instead of an error due to an empty table. 
Though it probably won't be common for people to run new PFTs with no data, it's possible for it to happen like it did in our case and there's no reason for it to disrupt the workflow. 
I need help with making sure …
> Return error message if no meta-analysis posterior exists

- Makefile
This is a workaround for a [bug in `devtools::install_deps`](https://github.com/r-lib/devtools/issues/2109) that doesn't understand that `Ncpus` is a valid argument (in cases where there is nothing to install or update). This bug has been immediately [killing](https://travis-ci.org/ashiklom/pecan/jobs/586040358#L2501) a bunch of my builds.
Also, use chained `Rscript -e "..." -e "..."` instead of single strings with complex escaping. This feels cleaner.
> BUILD: Use `options` instead of arguments

- base/workflow/DESCRIPTION
- base/workflow/R/run.write.configs.R
- base/workflow/R/runModule.run.write.configs.R
- book_source/03_topical_pages/03_pecan_xml.Rmd
- modules/uncertainty/R/ensemble.R
We just pulled the PR #2288 , which allows us to write config files for the cases where we don't have access to bety. However what I noticed was missing was when we need to specify `posterior.id` under PFT. I'm adding a new tag under `pft` for directly specifying `posterior.files`. I have tested this and this does not affect original functionality but if you define a tag like below, it will bypass the processing of using `posterior.id` for finding `posterior.files` and it will use the file directly.
The file could be any of `post.distns.*Rdata` or `prior.distns.Rdata`.
```
<pft>
<name>boreal.coniferous</name>
<constants>
<num>1</num>
</constants>
<outdir>/fs/data3/hamzed/Projects/HPDA/Outputs/Conifer/pft/boreal.coniferous</outdir> …
```
> Adding the posterior files tag

- Makefile
Workaround for devtools#2129: In version 2.2.1 of devtools, `test()` hard-codes the `stop_on_failure` argument to FALSE and throws an error if we try to override it. We need `stop_on_failure` to be TRUE to make the Travis builds stop reliably when tests fail, so this patch switches to directly calling `testthat::test_dir` (which devtools::test is a wrapper around).
> [Build] switch from devtools::test to testthat::test_dir

- modules/uncertainty/R/get.parameter.samples.R
I think, @femeunier and I found a change in behavior of base R between 3.4.X and 3.5.X which may result in a bug in near future for pecan running under R 3.5.X .  At line where I'm changing `trait.mcmc[[prior]]` is a list with 4 elements (4 chains for each parameter used in MA or HPDA) which when it's evaluated in R 3.4.X, it combines all lists into one vector. But in R 3.5.X code breaks at this point and it requires a more specific pointer to what elements within this list needs to be taken. I tested this fix for both versions of the R and 2 models and it passed successfully at all of them.
> Fix for get.parameter.samples 

- scripts/check_with_errors.R
Fixes an overeager (and, it turns out, redundant) string comparison in `check_with_errors.R` that was killing the build with a spurious "undefined functions or variables" note when the PR is in fact *fixing* undefined globals.
> [Build] avoid complaint when fixing one of several existing undefined globals

- scripts/check_with_errors.R
* When checking a package that has no `tests/Rcheck_reference.log`, default to failing on any new ERROR, WARNING, or NOTE (previous behavior was to fail if file not present)
* When checking a package that does have a reference log, continue to default to allowing old WARNINGs and NOTEs but failing on new ones and on any ERROR
* In either case, can override default behavior by setting environment variables `LOGLEVEL` and `DIELEVEL`
* Minor change from previous behavior: When check fails, output is printed by `devtools::check` not by us and `LOGLEVEL` is ignored. So e.g. if a check fails on a WARNING, it will print the WARNING *and* any NOTEs, even if `LOGLEVEL`=warn.
An apology to reviewers: This PR contains several commits, some with substantive changes and a couple that are strictly code …
> [Build] default to strict checking when no stored check results present

- models/ed/R/write.configs.ed.R
Values for the config.xml are read in from history files:
`vals <- as.list(edhistory[edhistory$num == pft.number, ])`
But depending on the history file, `include_pft` may be set to 0. However, I'm assuming that if you included the PFT in your `pecan.xml` then you definitely do want `include_pft = 1`. Thus it seems safe to set it to 1 at the end of conversions.
> Make sure `include_pft` is correct in write.config.xml.ED2

- CHANGELOG.md
- web/04-runpecan.php
This is a redo of the change in #2466 and will not automatically add a num to the pecan.xml, this was breaking the ED code that uses "smarts" to pick the right pft number. 
This needs testing with multi pft runs.
> don't write pft->constants->num see #2466

- base/settings/R/check.all.settings.R
- modules/data.atmosphere/R/read.register.R
It's been quite a while since 20141009160121 was the migration to use. This patch removes the hardcoded version and should stay at least somewhat informative without manual updating, at least as long as future migrations keep being parseable as dates and as long as "this schema version didn't exist yet when we tested this version of PEcAn" is the right cutoff for warning about possible incompatibilities.
> More informative warning on migration date mismatch

- modules/data.atmosphere/R/met.process.R
Avoids some cryptic errors when looping over empty vectors in met.process, e.g.
```
Error in standardize_result[[i]] <- .metgapfill.module(cf.id = list(input.id = cf.id$input.id[i],  : 
attempt to select less than one element in integerOneIndex
```
Whether the vectors ought to be empty in the first place is a different question, but this should at least make them easier to diagnose...
Saw this error on first attempt to use AmerifluxLBL data in a sorta-cleanish 1.7.1 VM updated to develop @ 601a92611. Have not tried too hard to reproduce in other contexts.
> met.process: use seq_along not 1:length

- scripts/travis/script.sh
Pins Travis version of Roxygen2 to 6.1.1 for now, to avoid breaking build on changes in output format from newer versions.
The CRAN version of Roxygen2 is now 7.0.0, with a bunch of shiny new features we don't yet use and also a change in how it formats function usage lines: previously on as few lines as possible, now with each parameter on its own line. We *could* upgrade right now and commit the resulting changes (I count 273 files affected), but we'll also want to make all PEcAn committers upgrade Roxygen on their dev machines at the same time. By pinning the Travis version to 6.1, we can defer the change until we're ready to do that.
> [build] pin Roxygen version until we are ready to upgrade

- CHANGELOG.md
- models/biocro/R/close_nc_if_open.R
- models/biocro/R/met2model.BIOCRO.R
Fixes #2485 
The lack of  `@export` on `close_nc_if_open` is intentional -- I think there's a chance but not a certainty that it could be useful to other packages, and it's much easier to export it (probably from a different package) if we need it later than it is to remove an exported function if we change our mind about it.
> met2model.BIOCRO: Close all years of input

- book_source/02_demos_tutorials_workflows/05_developer_workflows/01_update_pecan_code.Rmd
When building packages with compiled code, R calls Make internally, and those processes don't coordinate with the Make process running the whole PEcAn build. This only causes trouble when our build is called in parallel (`-j` > 1).
I've run into this both for RTM (#1976) and for BASGRA in my experimental GitHub Actions build. It's *possible* that we could make the Makefile be completely parallel-safe for packages with compiled code, but as far as I can tell it'd be an uphill battle and for the moment I advise avoiding the issue by building those two packages with `-j1`.
> document that compiled packages need make -j1

- CHANGELOG.md
- docker/depends/pecan.depends
- models/jules/DESCRIPTION
- models/jules/R/model2netcdf.JULES.R
- shiny/ViewMet/server.R
- [x ] When possible
- [ x] Bug fix (non-breaking change which fixes an issue)
> fixes-#2509-Removed-ncdf4.helpers-dependency

- models/ed/R/other.helpers.ED2.R
- models/ed/man/list.files.nodir.Rd
The documentation for base::list.files changed in R 3.6.2, making Roxygen output differ between R versions and therefore causing Travis headaches. This patch resolves this by no providing our own parameter descriptions instead of inheriting them, and adds some usage advice while I was at it.
> Remove @inheritParams from list.files.nodir

- scripts/travis/script.sh
Just for convenience when debugging Travis builds, should be especially useful for catching cache gremlins:
Prints all package versions (in a Travis-folded block, to avoid cluttering output)
just before starting the PEcAn make process. Packages may be added or updated after this,
but those will usually show clearly in the log. This at least gives a clear picture of our starting point.
> [BUILD] list package versions in log

- docker/depends/pecan.depends
- modules/data.atmosphere/DESCRIPTION
- modules/data.atmosphere/R/extract_local_CMIP5.R
- modules/data.atmosphere/tests/Rcheck_reference.log
For compatibility with R 3.5 and for general paring-down of the number of packages to install: package `car` imports `pbkrtest`, which now requires R >= 3.6.0. Since we only use it for `car::recode` in one function of data.atmosphere, this patch rewrites to use base::levels instead.
Also: While I'm at it, add undeclared `raster` dependency to DESCRIPTION.
> remove `car` dependency

- scripts/travis/rebuild_pkg_binaries.R
Problem: `devtools::install_deps` turns every `warning: package <package> was built under R version <version>` into a build-killing error, and we get a lot of those because c2d4u is serving a mix of packages built with R 3.6.2 and R 3.6.3.
Solution: For now, rebuild every package not built on exactly the same R version as is currently running, and hope we get it back from the Travis cache next time.
At this point I'm not at all sure that c2d4u is actually saving us any time, but am not ready to tear into the scripts enough to try removing it yet.
> [Travis] rebuild any package not built with this EXACT R version

- .github/workflows/stale.yml
> fixes-GH-#2556-Dealing with stale issues

- CHANGELOG.md
- base/db/R/dbfiles.R
- base/db/R/get.trait.data.pft.R
- base/db/R/utils_db.R
- base/db/inst/import-try/93.create.try.sites.R
- base/db/inst/import-try/README.md
- base/db/man/get.id.Rd
- base/db/tests/Rcheck_reference.log
- base/settings/R/check.all.settings.R
- base/utils/R/sensitivity.R
- docker/data/add.util.sh
- docker/monitor/monitor.py
- modules/assim.sequential/R/sda.enkf.R
- modules/data.land/inst/LoadFLUXNETsites.R
- scripts/add.util.sh
- web/04-runpecan.php
- web/setups/serversyncscript.php
Closes #1083 by removing all `created_at` and `updated_at`s from INSERT statements, because the database will handle these for us automatically . 
I have tested locally and confirmed the PEcAn.DB unit tests pass and the add.*.sh scripts still work as expected; I have not test-run the PHP or SDA changes.
As discussed in #1038 and elsewhere, this doesn't change the goal to move away from having hand-built SQL in our R code at all. But it does make the SQL we have a bit cleaner and eliminate a source of errors from non-UTC timestamps.
> Let database generate created_at and updated_at

- scripts/check_with_errors.R
Should cut down on failures caused by sort order within lines
Example: reference check result contains `imports not declared from: 'dplyr' 'PEcAn.DB'`,
but on OS X with my default locale the new result becomes `imports not declared from: 'PEcAn.DB' 'dplyr'` and is reported as a failure.
Yes, we have to call both `Sys.setlocale` and `Set.setenv`, because we need to set locale both
inside the current session and for rcmdcheck::rcmdcheck (which runs in its own process).
> set locale when comparing check output

- book_source/03_topical_pages/01_advanced_vm.Rmd
- documentation/tutorials/01_Demo_Basic_Run/Demo01.Rmd
just not necessary!
also simplified port forwarding examples
Also - is it possible to deprecate https://pecanproject.github.io/pecan-documentation/index.html ? It is the unversioned documentation and indexed by google, but hasn't been updated since 2017
> Remove Xubuntu desktop installation instructions

- modules/data.remote/R/call_MODIS.R
Even when `good` is an empty vector it does not display "all values bad" message. I have removed `!(is.null(good)))` to fix this.
Fixes #2520
> Fixed not triggering of "All values bad" in call_MODIS

- CHANGELOG.md
- modules/meta.analysis/R/meta.analysis.R
Current behavior: if random effects = TRUE in pecan.xml but none of the trait data have statistics then random effects is set to FALSE. A message is written to the log but this is mostly a hidden assumption that should be up to the user - because it may indicate an incorrect assumption about the data or missing data, or an overspecified model etc.
This was done because models will not converge if there are insufficient data to estimate all of the random effects parameters. 
I think setting random.effects = FALSE should be a decision made by the end uer.
Even when implemented in 2011, it was not clear that this was necessary. See my comment here https://github.com/PecanProject/pecan/commit/f6bcb78ea144e564bae781e32bcc307e9ec793b3#r8861144
Two other options:
1. come up with a more …
> don't override random.effects = TRUE

- book_source/Makefile
the PEcAn documentation is not currently building because Travis has updated to bookdown 0.20, which [interacts poorly](https://stackoverflow.com/a/62583304) with our multiple-subdirectory file organization. I predict this will be fixed in the next release of bookdown, but here's a workaround in the meantime.
Thanks to @MukulMaheshwari and @tezansahu for reporting.
> Fix for failing documentation build

- modules/data.remote/inst/gee2pecan_smap.py
This PR adds the `gee2pecan_smap()` function which can be used for getting soil moisture data from Earth Engine.
To be used in the remote data module.
As the module is not yet integrated with the PEcAn workflow, these steps will have to be performed manually.
This script requires Python3 and the python package manager pip
1. Sign up for the Google Earth Engine https://earthengine.google.com/new_signup/
2. Install the earth engine python api.
`pip install earthengine-api` on Linux use `pip3` instead of `pip`
Detailed steps including instructions for the alternative conda version are available [here](https://developers.google.com/earth-engine/python_installl)
3. Install the dependencies: download this [requirements.txt](https://raw.githubusercontent.com/ayushprd/PEcAn-GEE/master/requirements …
> GEE - SMAP script

- CHANGELOG.md
- modules/data.atmosphere/R/download.NOAA_GEFS_downscale.R
- modules/data.atmosphere/man/download.NOAA_GEFS_downscale.Rd
> Updating precipitation downscale for NOAA GEFS downscale 

- .github/workflows/styler-actions.yml
Adds a new command for pull request comments: To update the Roxygen docs for all files touched in a PR, leave a comment that starts with `/document` and the robots will do the rest. You don't even need Roxygen on your local machine!
Technically it was already possible to Roxygenize a PR as part of the `/style` command, but this wasn't documented and sometimes we want to document without touching code formatting. 
I've also streamlined the checking code a bit for hopefully faster results, including removing a few dependencies that I *think* aren't needed -- @rahul799 can you confirm I got this right?
> Roxygenize from PR comments with /document

- apps/api/R/entrypoint.R
- apps/api/R/submit.workflow.R
I came across these issues while trying to use the API to submit workflows. These are a prerequisite to getting the test suite working.
- Rather than inserting workflows and then querying the last one, insert workflows with a `INSERT ... RETURNING id`, which reduces the number of queries and is more robust.
- Replace `paste`-style queries with prepared statements, which are more robust.
- Standardize the target `bety_params`. Rather than sometimes relying on `config.php` and sometimes relying on `get_postgres_envvvars`, always rely on the later, with sensible defaults (set in the file, in the global variable `.bety_params`)
- Replace `plumber::plumber` with `plumber::Plumber` (to reflect v1.0 update -- this silences a warning and protects us from upcoming deprecation)
> API workflow submission bugfixes

- apps/api/Dockerfile
- apps/api/R/auth.R
- apps/api/R/available-models.R
- apps/api/R/entrypoint.R
- apps/api/R/formats.R
- apps/api/R/general.R
- apps/api/R/get.file.R
- apps/api/R/inputs.R
- apps/api/R/models.R
- apps/api/R/pfts.R
- apps/api/R/runs.R
- apps/api/R/sites.R
- apps/api/R/submit.workflow.R
- apps/api/R/workflows.R
- base/utils/R/convert.input.R
Resolving some issues I discovered while trying to get the test suite up and running.
- Use the [`pool` package](https://github.com/rstudio/pool) to manage database connections in the API. This prevents "too many connections" errors, which can arise from heavy API use (e.g., when submitting dozens of test runs). Create this connection pool once, when the API is launched, and use it everywhere (rather than re-opening new connections everywhere).
- Add the `availableModels` API entrypoint for querying the models available on a given machine.
- Use explicit string formatting of `workflow_id`, to avoid implicit coercion issues with `bit64`
- Minor bugfix in `base/utils`: If `dbfile.input.check` returned a blank `data.frame` (as it does if files aren't found), then the subsequent `filter` …
> PEcAn API bugfixes and enhancements

- apps/api/R/submit.workflow.R
Currently, the API incorrectly sets the `model$type` as the `models.model_name`, though these actually have different meanings in PEcAn (though, for many models, they are coincidentally the same value). This would result in a bug when trying to run `ED2.2`, whose name is `ED2.2` but whose _type_ is `ED2`. The resulting error would be something like `No PFT "temperate.Late_Hardwood" for model type "ED2.2"`.
This PR makes it so that only the model ID is passed to PEcAn, which is already unambiguous and, moreover, is how the `rpecanapi::submit.workflow` function already works anyway (i.e., no user-facing changes). It should be the user's responsibility (for now) to manually figure out exactly which model + revision they want to run and the associated ID.
However, given the model ID, we _do_ …
> API: Only pass model ID to PEcAn

- apps/api/R/general.R
In all the other places in the API, there is a `dbcon = global_db_pool` function argument. But I forgot to add it to the `status` entrypoint.
> API: Fix missing `dbcon --> global_db_pool`

- apps/api/R/models.R
They are opened externally to the function, so it's no longer the function's job to close them.
> API: Don't close connections in model funs

- CHANGELOG.md
- book_source/03_topical_pages/03_pecan_xml.Rmd
- web/workflow.R
New XML tag `run / stop_on_error` controls whether the workflow will terminate if _any_ of the model runs fail. If unset, the _new behavior_ is that the workflow _will_ terminate (`stop_on_error = TRUE`) if you are doing only a single model run, but _will not_ terminate (`stop_on_error = FALSE`) if you are doing an ensemble simulation.
> Allow setting stop_on_error via settings

- web/workflow.R
When `stop.on.error` is not set, trying to retrieve it returns `NULL. As it turns out, `as.logical(NULL)` produces a length-0 logical vector, not `NULL` (so `is.null(as.logical(NULL))` is `FALSE`), and so my entire automatic setting of this was being skipped! This would lead to downstream errors when the resulting `stop.on.error = logical(0)` interacts with, e.g. ,`if (stop.on.error)`.
> WORKFLOW: Bugfix empty stop.on.error

- web/workflow.R
If no ensemble, `stop.on.error` should be `TRUE`! If ensemble, should be `FALSE`! I accidentally got this backwards...
> WORKFLOW: Fix swapped stop.on.error TRUE/FALSE

- models/ed/inst/template.job
Otherwise, workflows would claim to still finish successfully even if this step failed.
> ED2: Catch model2netcdf errors in template.job

- modules/data.atmosphere/R/download.CRUNCEP_Global.R
When using the NetCDF subset method (`ncss`), we would previously download raw yearly CRUNCEP NetCDF files as temporary files, which would just be deleted at some point. Taking inspiration from `download.MERRA`, I figured it might make more sense to actually store these raw files in a meaningful way, so that future workflows could reuse them. Since these files were already complete years (regardless of what the input time step was), this seems like a useful speed gain with the only minor downside being somewhat increased disk usage. These files are silently overwritten if `overwrite = TRUE`.
> MET: Cache raw CRUNCEP files

- base/db/R/get.trait.data.pft.R
Old meta-analysis PFT membership files sometimes stored NA's as literal "NA" strings, which were not being read in as NA's. This caused the difference checking code to (incorrectly) pick up a difference between in PFT membership and caused the trait meta analysis to always run.
For example, this is from one of my recent workflows (before this change):
```
2020-11-11 18:42:04 DEBUG  [FUN] : 
Checking if PFT membership has changed. 
2020-11-11 18:42:04 ERROR  [FUN] : 
PFT membership has changed. 
Difference is:
source   id     genus species scientificname
1  existing 1390     Tilia      NA          Tilia
2  existing   17      Acer      NA           Acer
3  existing   46  Aesculus      NA       Aesculus
4  existing  634   Halesia      NA        Halesia
5  existing  450 Diospyros      NA …
```
> Fix meta-analysis update-auto when some columns are NA

- CHANGELOG.md
- base/utils/R/utils.R
- base/utils/tests/testthat/test.utils.R
Prior to this change, the `summarize.result` function did not summarize SE due to an ordering issue. n and mean were moved to below statname and stat.
previously, the `summarize.result` function included this:
```r
dplyr::summarize(
n = length(n),	
mean = mean(mean),	
stat = stats::sd(mean) / sqrt(length(n))
```
Apparently, the author had expected `sd(mean)` and `length(n)` to use the values in the original data frame, but the summarize function first computed new summary values of mean and n, and since these were reduced to 1 value per group, didn't compute a statistic. 
We also created additional tests were created to ensure the new function works correctly.
As a result, random effects were not being included in some meta-analysis models where these within group statistics were not …
> Fix summarize.result so it generates statistics

- base/db/R/get.trait.data.pft.R
Should be able to set `forceupdate` in meta-analysis to `TRUE` to update trait data, but this wasn't working because it was read in as a string and changed in `get.trait.data.pft` to `FALSE`. This should fix that, and came from @bcow [original suggestions](https://github.com/PecanProject/pecan/issues/2422) about how to fix this.
> Fix get.trait.data.pft so forceupdate set to true stays true

- .github/workflows/book.yml
- .github/workflows/ci.yml
- .github/workflows/depends.yml
- CHANGELOG.md
Our 4.0.3 builds and checks are already passing, and now that R 4.0.4 is released, 4.0.3 packages are frozen to Feb 17, 2021. Meanwhile, our 4.0.2 builds are failing for no fault of our own (looks like an error with the R Package Manager).
NOTE: I think this will fail the 4.0.4 checks (not required) until it's merged because we haven't build the containers yet. I already changed the branch protection rules to use the 4.0.3 builds and checks instead of 4.0.2.
> Bump default R version to 4.0.3

- base/db/R/dbfiles.R
I added an else block under for the if (exact.dates). I kept the end_date logic added in 692b65aa588d2352bb3dfb2f88a235e32295bc1e but brought back the missing code from the earlier version d93f1b395279119cd0849c0bc34c121f7bf2edda.
When trying to get CF met data processed I found the workflow to crash in dbfile.input.check, because no query is run whenever the exact.dates argument is false. It seems that the code to handle this case had gone missing in a recent commit. Assuming that this was accidental, I restored the missing code from an earlier version.
> Handle exact.dates = FALSE in dbfile.input.check

- web/common.php
When a different port is used for bety the web UI could not connect to DB, passing the port explicitly solves it I think.
On our server we use a different port for Bety and I can't use web UI because pages don't respond after open_database() fails. This change seems to fix it for me.
> Pass port explicitly to open_database()

- scripts/check_with_errors.R
Apparently devtools 2.4.0 changed the needed input for its `document` argument without saying so in the release notes 😒
> Support devtools >= 2.4.0 in check_with_errors.R

- base/logger/DESCRIPTION
Found by checking PEcAn.logger against the R-hub check service: `Rscript -e 'rhub::check_for_cran("PEcAn.logger_1.8.0.tar.gz", email = "chris@ckblack.org")'`
(use your own email address; rhub will give you instructions on how to verify it before you submit the package) 
r-hub results: Before this patch ([R-devel Fedora](https://builder.r-hub.io/status/PEcAn.logger_1.8.0.tar.gz-5448fb4274fa440596dc4faee348eb5b), [R-release Fedora](https://builder.r-hub.io/status/PEcAn.logger_1.8.0.tar.gz-f261c02966024604b3fb69cc82161289), [R-devel Windows](https://builder.r-hub.io/status/PEcAn.logger_1.8.0.tar.gz-d58a4cf8451740799bb4bfd6cf6018e7)); After this patch ([R-devel Fedora](https://builder.r-hub.io/status/PEcAn.logger_1.8.0.tar.gz-c4bd584c907248d4b78bc04daff699ee), [R-release …
> Logger spelling fix

- base/utils/R/mcmc.list2init.R
- modules/assim.sequential/R/get_ensemble_weights.R
- modules/data.land/R/InventoryGrowthFusion.R
- scripts/EFI_workflow.R
The logger functions in PEcAn.utils have been deprecated for several years and will be removed entirely in #2830. 
These are the only remaining uses of them I could find in the codebase, but if you're reading this please check all your local scripts and update them now!
> convert last uses of deprecated PEcAn.utils::logger* to PEcAn.logger::loger*

- CHANGELOG.md
- docker-compose.yml
force docker to use rabbitmq 3.8, rabbitmq 3.9 and above require a rabbitmq.conf file. This will fix the issue where new installation can not run rabbitmq, and thus pecan does not work.
> rabbitmq 3.9 and up require a config file, using 3.8 for now

- Makefile
Not needed because when on CI all known dependencies are listed in `docker/depends/pecan.depends.R` and we install them in bulk before invoking make
Question for @robkooper:  On checking, it looks like install-dependencies steps of the `test`, `check`, and `sipnet` jobs is 
```
Rscript scripts/generate_dependencies.R && Rscript docker/depends/pecan.depends.R
``` 
But in the `build` job it's just
```
Rscript scripts/generate_dependencies.R
```
Should that change, or does build not need depends?
> skip dependency check when on CI

- modules/assim.sequential/R/Helper.functions.R
- modules/assim.sequential/tests/testthat/test_rescaling.R
A few unit tests for the helper function that rescales state variables. 
As is traditional, writing the tests also leads to bug fixes: 
* When the input had more than one attribute set, none of the attributes were being copied to the output. Fixed by looping over all of them.
* Inputs that were dataframes lead to corrupted output, because their `class` and `names` attributes got copied over onto the matrix output. Fixed by only coercing the result to matrix if the input was also a matrix, and otherwise returning dataframe. Note that the function is only documented to accept and return matrices, but quiet dataframe support seemed better than data corruption.
"Once again, Chris, why are you spending your time writing tests for the simplest function in the package?" 
Well, because my real …
> Add tests for rescaling_stateVars

- .github/workflows/ci.yml
This should install any dependencies added since last Docker build. Only editing the build step because test and check were doing it already.
Should be a no-op for runs where no new packages are added (i.e. the vast majority of them)
> rerun pecan.depends.R before build step 

- .github/workflows/styler-actions.yml
Fix missed in #2864: You'd think we'd need to either install at the beginning /or/ during Make, but 🤷‍♂️
> Install new packages at start of /document

- Makefile
When invoking `make document`, check that Roxygen version is exactly 7.0.2 and stop immediatelywith a clear error message, rather than let Roxygen update every package in a way that's hard to roll back as it does currently.
The fact that we make everyone use the same version of Roxygen is buried somewhere in the documentation, but hasn't been a clear part of the onboarding routine (sorry, @helge22a and @DongchenZ!). It's definitely worsened by the fact that we've let the supported version of Roxygen get so old, but I submit that we'll still need this check even after updating to use the version of Roxygen that's current as I write this.
> throw Make error if wrong Roxygen2 used

- docker.sh
- docker/depends/Dockerfile
Noticed that we still use docker 4.0.2 to build, now using 4.1
> fix docker.sh to use R 4.1

- Makefile
- docker/base/Dockerfile
- scripts/confirm_deps.R
Replaces the Makefile check for package dependencies, previously provided by a call to `devtools::install_deps` that always checked for updates, with a new check that checks locally first and exits if all dependencies are already satisfied, _even if newer versions of them are available_. This is a change in behavior, but I argue it's what we want: If your installed version of (say) `stringi` still works, running `make document` shouldn't waste your time looking for a new version of it.
Note that if any dependencies *are* missing for a given package, we still resolve them by calling `install_deps` with `upgrade = FALSE`, which will still _send queries_ to learn about updates to all dependencies (not just the ones that are missing) but will only  _install_ the missing ones. 
The primary …
> Less eager dependency check

- apps/api/README.md
Updated a not working link in the README.md for the API docs.
Previous link doesn't work, this one does.
> Update README: Fixed link to API docs in swagger

- docker/depends/pecan.depends.R
- modules/data.remote/DESCRIPTION
- modules/data.remote/NEWS.md
- modules/data.remote/R/call_MODIS.R
The `binaryLogic` package has been removed from CRAN and appears abandoned on GitHub, so depending on it seems risky. Fortunately we were only using it for one call inside `PEcAn.data.remote::call_MODIS` and that call was relatively easy to replace with base functions.
> remove dependency on  binaryLogic (+ add NEWS)

- docker/depends/Dockerfile
Needed when installing `nloptr` from source, as happens on the Rdevel image. The images for other R versions install binary packages from Rstudio Package Manager and therefore don't strictly need this, but I vote we install cmake everywhere rather than fuss around installing different apt packages on different tags.
> add cmake to depends image

- scripts/confirm_deps.R
Makes `scripts/confirm.deps.R` work as expected with R 3.6.3. 
Note that R 4.0 is the oldest version we still include in the PEcAn CI tests, so it is *very likely* that we have other components that no longer support R 3.6 -- I only fixed this one because it was simpler than adding an interpretable error message.
> avoid string->factor when running `confirm_deps` in R < 4.0

- book_source/03_topical_pages/03_pecan_xml.Rmd
I recently encountered a problem setting up PEcAn to use ED2 that involved editing an un-documented xml tag in pecan.xml.  This adds it to the documentation and fixes some other mistakes I noticed along the way.
> document `mpirun` xml tag

- scripts/generate_dependencies.R
Updates `generate_dependencies.R` to avoid adding a(nonexistant) "R" package to the list of needed packages when a package contains an R version support declaration of the form "Depends: R (>= x.y)"
> do not count "R" as a package that needs installing. Fixes #2993

- base/utils/R/datasets.R
- base/utils/man/standard_vars.Rd
R checks for utils now complain if run on a system that doesn't have `udunits2` installed. Fixed by rewording to point to new wrapper instead.
> remove leftover link to udunits2 package

- modules/uncertainty/R/ensemble.R
Removing code implemented in PR https://github.com/PecanProject/pecan/pull/2126. The queried the DB and used the information to return some information. 
It was implemented as a quick workaround for a specific project to link pfts with specific sites. But at this point it has no effect other than to send a message via logger, or create an error if nothing is returned (perhaps because R has changed how it handles missing data). In [todays meeting](https://docs.google.com/document/d/1DUQyKEwGYTumr6ttFJA8vcwZXqgUTTxn4rjeVdomQtU/edit#bookmark=id.ucevo0tnkm6b) we decided to remove the code and punt the implementation of pft-site relationships to the next time it is needed
> Remove orphaned and troublesome query and logger message from ensemble.R

- base/db/R/insert.format.vars.R
- modules/data.atmosphere/R/met2CF.csv.R
Replacing udunits2::ud.is.parseable with PEcAn.utils::unit_is_parseable
> removed udunits2::ud.is.parseable usages from PEcAn

- scripts/generate_dependencies.R
Updates the matching rule for treating a dependency as a PEcAn package, from "starts with `PEcAn` followed by at least one other character" to simply "starts with `PEcAn`"
`generate_dependencies.R` identifies dependencies between PEcAn packages by parsing DESCRIPTION files and looking for dependencies matching `"^PEcAn."`. The dot is treated as a wildcard, so this works as intended, but is confusing to read since it will be matching a literal dot in most but not all packages. Removing the dot makes it clearer that we don't care that characters come after the prefix.
> assume nothing about characters after "PEcAn" in package name

- CHANGELOG.md
- base/remote/R/fqdn.R
Add `as.character(Sys.info()["nodename"])`  if no env variable FQDN and `hostname -f`  return empty strings.
hostname doesn't work on Windows. Fixes #3044
**Perhaps a simpler option** 
replace function with `fqdn <- function() as.character(Sys.info()["nodename"])`
> find fqdn across platforms

- CHANGELOG.md
- models/ed/DESCRIPTION
- models/ed/NEWS.md
- models/ed/R/model2netcdf.ED2.R
- models/ed/R/veg2model.ED2.R
- models/ed/R/write.configs.ed.R
- models/ed/man/model2netcdf.ED2.Rd
- modules/data.atmosphere/man/cos_solar_zenith_angle.Rd
Adds an argument `process_partial` (default FALSE) to `model2netcdf.ED2()` that allows it to work even on partial runs that have been interrupted and not produced as many .h5 files as expected based on the dates in settings.
Although ensembles of different lengths might screw up downstream analysis, sometimes you want to extract data from failed runs to inspect it.
> Allow `model2netcdf.ED2()` to process partial output from failed runs

- docker-compose.yml
The changes to the docker-compose file made the bety interface not reachable. This fixes that issue.
> add missing port reference to docker-compose (fixes #3062)

- base/utils/tests/testthat/test.utils.R
- models/maat/R/write.config.MAAT.R
- modules/priors/R/plots.R
- modules/priors/vignettes/priors_demo.Rmd
The aim of this PR is to replace the use of `transform()`
This PR fixes #2961
> Replaced `transform` function

- base/qaqc/DESCRIPTION
- docker/depends/pecan.depends.R
Background: We install pinned versions of `testthat` and `vdiffr` from GitHub rather than CRAN, because on our R 4.0 images, "CRAN" is an RSPM snapshot from 2020 and contains testthat 3.0.2 (we need at least 3.0.4 for vdiffr support).
Problem: Our weekly tests on R-devel are [failing](https://github.com/PecanProject/pecan/actions/runs/4040621324/jobs/6946430240) because of some incompatibility between testthat 3.0.4 and devtools 2.4.5.
Solution: Bump the pinned version of testthat to 3.1.6, the current latest CRAN release.
> Bump testthat and vdiffr versions

- base/db/DESCRIPTION
- docker/depends/pecan.depends.R
Version bump is needed to avoid "xfun::isFALSE is deprecated" warnings; installing from Github is just the easiest way to bump it on Docker images that use fixed-date RSPM snapsnots as their CRAN.
Note also that this only specifies the rmarkdown version for PEcAn.DB (where the `xfun::isFALSE` warnings were appearing during vignette build), but it has the effect of bumping the rmarkdown version for all PEcAn packages that use it.
(I'm not sure I like this pattern as a long-term solution, but at the moment it feels like the cleanest balance of keeping most dependency versions stable while incrementing the ones we need to.)
> install rmarkdown from github

- modules/data.atmosphere/R/download.Fluxnet2015.R
This adds an additional condition when checking for `dataURLsList` in `link` object. 
Made this improvement as it does not check conditions when the `link` is `NULL` or when the return value is `atomic`.
Work done : 
I ran the API code separately and ended up in the result as below in the `link` variable :
[1] "This endpoint is no longer available. Please contact ameriflux-support@lbl.gov for assistance."
which is `atomic` and thus the condition seemed necessary.
`sitename` set to : `Niwot Ridge Forest/LTER NWT1`
> Added condition for link response in `download.Fluxnet2015`

- models/ed/NEWS.md
- models/ed/R/model2netcdf.ED2.R
Fixes a bug in `model2netcdf.ED2()` where `put_E_values()` would fail because the dimensions were wrong when a PFT was missing from ED2 output .h5 files. 
I was previously making the assumption that all PFTs would show up in all outputs, but apparently they can "disappear" for a few months and then come back.  This may be an ED2 bug, but for now, I figured it would be best to write `NA`s for temporarily missing PFTs so that the dimensions get figured out correctly and .nc files get created.
> Bugfix for `model2netcdf.ED2()`—missing PFTs cause incorrect dimensions

- Makefile.depends
- models/ed/DESCRIPTION
- models/ed/R/write.configs.ed.R
> Updated `write.configs.ed` to throw an error if `revision` not specified

- CHANGELOG.md
- modules/uncertainty/DESCRIPTION
- modules/uncertainty/NEWS.md
- modules/uncertainty/R/run.sensitivity.analysis.R
- modules/uncertainty/man/run.sensitivity.analysis.Rd
Adds a `pfts` argument to `run.sensitivity.analysis()` to allow the user to specify a subset of PFTs in the `settings` object to run sensitivity analysis on. 
Also prevents this function from dumping objects into the global environment (and possibly overwriting things without any warning) by specifying the environment for `load()`
Doing sensitivity analysis with a large number of PFTs generates a large number of runs and to save on compute time, I "manually" removed SA runs for PFTs I'm not interested in.  `run.sensitivity.analysis()` interprets this as an there having been an error in model runs and doesn't generate all the files it is supposed to (in particular, no sensitivity.results.Rdata) (#3154).
> Add optional `pfts` argument to `run.sensitivity.analysis()` (fix/workaround for #3154)

- CHANGELOG.md
- base/utils/NEWS.md
- base/utils/R/ud_convert.R
- base/utils/man/ud_convert.Rd
- base/utils/tests/testthat/test-ud_convert.R
Fixes #3012 .  Checks if argument `x` is difftime, and if it is converts it to a `units` object with `as_units()`.  Units are inferred from the class, so argument `u1` isn't actually used in the conversion in this case.  UI is a little weird here, but seems like this is mostly an internal function so probably better than adding argument defaults and allowing `u1` to be `NULL` or something like that.
> Allow `ud_convert()` to work with class "difftime" (fix for #3012)

- base/remote/DESCRIPTION
- base/remote/tests/testthat/test.check_model_run.R
- base/remote/tests/testthat/test.kill.tunnel.R
- base/remote/tests/testthat/test.rabbitmq.R
- base/remote/tests/testthat/test.remote.copy.from.R
- base/remote/tests/testthat/test.start_qsub.R
- base/remote/tests/testthat/test.start_rabbitmq.R
- base/remote/tests/testthat/test.start_serial.R
PR aims at improving unit test coverage for `PEcAn.remote` package
> Improving test coverage for `PEcAn.remote` package

- base/utils/DESCRIPTION
- base/utils/R/mail.R
- base/utils/R/utils.R
- base/utils/man/retry.func.Rd
- base/utils/tests/testthat/test.cf2date.R
- base/utils/tests/testthat/test.clear.scratch.R
- base/utils/tests/testthat/test.days_in_year.R
- base/utils/tests/testthat/test.download.url.R
- base/utils/tests/testthat/test.get.ensemble.inputs.R
- base/utils/tests/testthat/test.listToArgString.R
- base/utils/tests/testthat/test.load_local.R
- base/utils/tests/testthat/test.n_leap_day.R
- base/utils/tests/testthat/test.need_packages.R
- base/utils/tests/testthat/test.r2bugs.distributions.R
- base/utils/tests/testthat/test.seconds_in_year.R
- base/utils/tests/testthat/test.sendmail.R
- base/utils/tests/testthat/test.timezone_hour.R
- base/utils/tests/testthat/test.units_are_equivalent.R
- base/utils/tests/testthat/test.utils.R
PR aims at improving unit test coverage for `PEcAn.utils` package
> Improving test coverage for `PEcAn.utils` package

- scripts/check_with_errors.R
Adds a new usage variant: To update the cached check results in `[package_dir]/tests/Rcheck_reference.log`, run the check script with env var `RESAVE_CHECKS` set, e.g.:
```
RESAVE_CHECKS=true Rscript scripts/check_with_errors.R base/db
```
After running, review the changes to `Rcheck_reference.log` and commit them if they look good.
Thanks to the whole team in general and @moki1202 in particular, lots of our cached check results are stale in the sense that they contain messages about errors/warnings we have since fixed. We've mostly been updating these by manually editing the saved files, but this is tedious and error-prone. This patch provides a one-shot method to ease the process.
As always, my hope is that we'll use this to remove fixed messages (so that we can eventually remove all …
> Add resave mode to check_with_errors.R

- modules/data.land/DESCRIPTION
- modules/data.land/R/gis.functions.R
- modules/data.remote/DESCRIPTION
- modules/data.remote/R/NLCD.R
- modules/data.remote/R/download.thredds.R
- modules/data.remote/tests/Rcheck_reference.log
Per issue https://github.com/PecanProject/pecan/issues/2914 made changes to data.land. It's a very small change, rgdal functions were being used for printing info only.
I just removed rgdal from data.remote `DESCRIPTION` as well, although there was an `require(rgdal)` in the `extract_NLCD` function, no rgdal package function was being used within this function, also seems to be the case in #3222.
See https://github.com/PecanProject/pecan/issues/2914.
> removed rgdal from data.land and data.remote

- base/workflow/R/start_model_runs.R
On docker, workflow writes rabbitmq.out to rundirs, but [start_model_runs()](https://github.com/PecanProject/pecan/blob/develop/base/workflow/R/start_model_runs.R#L294) try to read it from outdir, workflow hangs, further description here: #3236 
Fixes #3236
> reverting back lines that read rabbitmq.out

- CONTRIBUTING.md
- DEBUGING.md
- DEV-INTRO.md
- README.md
- contrib/README.md
- documentation/README.md
- modules/benchmark/inst/scripts/benchmarking.documentation.md
Improved the quality of `CONTRIBUTING.md` and other markdown files:
+ places where code block was left unidentified, for example `bash` blocks, were changed to bash code blocks. 
+ Linting and Alignment issues fixed in documentations.
I do not have permission to select labels and would like admins to add `enhancement` and `documentation` label to the PR
It does not actually fix #3245 because I do not have access to modified links, but I surely can change them if provided with the links.
Fixes markdown linting issues in `CONTRIBUTING.md`
#3245
> Fix Typo Errors and Errors in Markdown documentations

- .github/workflows/depends.yml
As discussed in Slack -- If I did this right, should let us manually trigger a new build of the Depends image rather than wait for midnight in cases where it's blocking other merges.
Also drops build of the R 4.0 image -- we gave it a good run, but have dropped support for it and will not be going back.
(I think this means we can now start using `|>` in place of `%>%`, if we want to)
> Allow manual trigger of depends build

- modules/data.atmosphere/R/temporal.downscaling.R
- modules/data.atmosphere/tests/testthat/test.cf-downscaling.R
I think this was a flipped multiply/divide -- the now-replaced `0:(23 * output.dt)/output.dt` (which has been there for a looong time!) works when output.dt == 1, but gives too many rows for larger timesteps. 
I assume the original intention was to write `0:(23/output.dt)*output.dt`, but I replaced it with `seq(0, 23, by = output.dt)` -- that behaves identically and is a lot clearer to me.
Noticed while reviewing #3218
> [met downscaling] Fix for non-hour timesteps in cfmet.downscale.daily

- apps/api/tests/test.auth.R
- apps/api/tests/test.formats.R
- apps/api/tests/test.inputs.R
- apps/api/tests/test.models.R
- apps/api/tests/test.pfts.R
- apps/api/tests/test.ping.R
- apps/api/tests/test.runs.R
- apps/api/tests/test.sites.R
- apps/api/tests/test.workflows.R
This Fix is similar to this issue in our `rpecanapi` Repository : https://github.com/PecanProject/rpecanapi/issues/21
Refracted server URLs to use localhost PEcAn URLs
> Update API endpoint URLs

- models/stics/R/met2model.STICS.R
- models/stics/R/write.config.STICS.R
Priority: 02 - Normal
Status: Ready
Updates to SticsRFiles meant using the `javastics` argument of `convert_xml2txt` caused an error in generating input files for STICS. Removed these arguments and the now-unused `javastics_path` variable.
Also changed met2model to use the proper datetime origin.
Required due to SticsRFiles package being updated. Run generation does not work with the latest package versions without these changes.
> Remove extra arguments for STICS convert_xml2txt

- base/logger/R/logger.R
- base/logger/tests/testthat/test.logger.R
Replaces [robkooper/pecan/#83](https://github.com/robkooper/pecan/pull/83)
> Remove copyright notice that references outdated license

- .github/workflows/docker.yml
(moved from robkooper#82)
Should fix Docker build failure in release branch that arises because the existing code tries to test-build the `depends` image by updating an existing `pecan/depends:<base branch>` and we (1) don't have a `depends:master` (we were calling it `depends:latest`), and (2) if we did, it would usually be so out of date it makes more sense to build a fresh image than to update it. 
This was one of two approaches I proposed. See https://github.com/robkooper/pecan/pull/79 for the other and speak up if you like that better, but I now prefer this one. 
Note that this will change behavior of non-PR calls to the Docker action:
* Non-PR Action runs with dependency changes do not build depends (which may or may not cause other failures)
* PRS with dependency changes try to …
> build depends fresh if no existing tag to update

- modules/data.atmosphere/R/read.register.R
This is an example demonstration of how we may proceed with : Refactor `convert_input.R` to Optimise Workflow #3307
> Combine multiple `PEcAn.db` calls in a single query
